### ISSUE TITLE
VCS write metadata in image

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1000]
It would be very useful to have a capability to write metadata into an image file.  Most image file formats support this.

We need to start with an API in VCS. I think that all metadata could be expressed as strings. So on input to VCS, the metadata could be expressed as a dictionary of attribute_name:value_string pairs.

The file formats which would be most useful to the ACME project are png (for raster graphics) and svg (for vector graphics).

**Comment by doutriaux1** [comment]
moving to 2.3 not going to happen in 2.2
