### ISSUE TITLE
2D plots with latitude and height

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1001]
For both the command line and GUI we need a latitude-height (level) plot with log for the vertical levels. I don't know if this is already in the diagnostics - but when you plot from 1000 hPa to 1 hPa it is important to see the detail of upper  levels (even down to 0.1 hPa). I have attached an NCL plot that also shows the height in km on the right hand scale. 

Also, all the CMIP5 models use Pa for the levels, we need a quick conversion to hPa for the levels too.

The example should go into the gallery - much like NCL has
![merra_corrected](https://cloud.githubusercontent.com/assets/2963950/5982668/3010427e-a87a-11e4-81f5-cd7159de9065.png)

**Comment by doutriaux1** [comment]
@potter2 this is a uvcmetrics issue please repost there.

**Comment by doutriaux1** [comment]
I'll do it actually don't worry about it.
