### ISSUE TITLE
Refresh problem with 2.1

### ISSUE THREAD

**Issue by stott** [UV-CDAT/uvcdat#1007]
On our system, we have centos 6.5 (2.6.32-504 kernel) installed.  We downloaded UVCDAT 2.1.0 and Qt 4.8.4 from UVCDAT's sourceforge page, set the environment variables as specified on the website.

We can launch and plot an initial plot okay, but the application's GUI doesn't refresh or render if we maximize the window or try to plot something else.  The menus are technically there, but we can't see them.

I'm not sure if it's related, but this happens often when we load a file that has error messages about time units.  The smaller examples that come with UVCDAT all seem to work fine.

If we do the same thing on version 1.5 with it's appropriate Qt, we still get the warnings about time units, but we do not encounter the refresh problem with graphics.

We tried the same with Ubuntu and get exactly the same refresh problem

**Comment by hgohil2805** [comment]
Hi,
I am using Ubuntu. For me the re sizing works fine and I am also able to plot after changing the window size. Can someone else also try this ?

Also, is this for the same system? There are some issues with the graphics card for UVCDAT so it'd be great if you can test it on other computers as well.

**Comment by doutriaux1** [comment]
@hgohil2805 I think it wa because of #1008 then the GUI was becoming completely unresponsive. I'm leaving this open until we can confirm it's better. @stott could you try a build from master? the fix is in.

Thanks.

**Comment by stott** [comment]
Yes. We'll rebuild and try it.
Thanks

Lowell

On Thursday, February 26, 2015, Charles Doutriaux <notifications@github.com>
wrote:

> @hgohil2805 <https://github.com/hgohil2805> I think it wa because of #1008
> <https://github.com/UV-CDAT/uvcdat/issues/1008> then the GUI was becoming
> completely unresponsive. I'm leaving this open until we can confirm it's
> better. @stott <https://github.com/stott> could you try a build from
> master? the fix is in.
>
> Thanks.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76298235>.
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by hgohil2805** [comment]
@doutriaux1  Sounds good. If it works then we should close the issue. Thanks

**Comment by stott** [comment]
Hi Charles,
My apologies for not knowing this already, but where is the "master"
located?

thanks,
Lowell

On Thu, Feb 26, 2015 at 3:33 PM, Hardik Gohil <notifications@github.com>
wrote:

> @doutriaux1 <https://github.com/doutriaux1> Sounds good. If it works then
> we should close the issue. Thanks
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76298977>.
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
no worries
```
git clone git://gituhb.com/UV-CDAT/uvcdat.git
```
More at: https://github.com/UV-CDAT/uvcdat/wiki/Build

**Comment by stott** [comment]
Thanks. I downloaded 2.1.0 from ResourceForge over the weekend but I
couldn't get that one to run. I retry with this one this morning.

Lowell

On Monday, March 2, 2015, Charles Doutriaux <notifications@github.com>
wrote:

> no worries
>
> git clone git://gituhb.com/UV-CDAT/uvcdat.git
>
> More at: https://github.com/UV-CDAT/uvcdat/wiki/Build
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76723753>.
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by stott** [comment]
Charles,

After multiple attempts I'm unable to build the 2.1.0 version from git.
You have an account on Atmosphere. Perhaps if you have a little time you
could try? I'd appreciate your help.
Our system analyst is tied up this week unable to help trouble shoot with
me.

thanks,
Lowell

On Mon, Mar 2, 2015 at 7:10 AM, Lowell Stott <stott@usc.edu> wrote:

> Thanks. I downloaded 2.1.0 from ResourceForge over the weekend but I
> couldn't get that one to run. I retry with this one this morning.
>
> Lowell
>
>
> On Monday, March 2, 2015, Charles Doutriaux <notifications@github.com>
> wrote:
>
>> no worries
>>
>> git clone git://gituhb.com/UV-CDAT/uvcdat.git
>>
>> More at: https://github.com/UV-CDAT/uvcdat/wiki/Build
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76723753>.
>>
>
>
> --
> Professor
> Department of Earth Sciences
> University of Southern California
> Los Angeles, CA 90089
>
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
ok doing this right away

**Comment by stott** [comment]
Thanks!

On Mon, Mar 2, 2015 at 10:51 AM, Charles Doutriaux <notifications@github.com
> wrote:

> ok doing this right away
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76778620>.
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
@stott ok I built on your system it is at 
```
source /home/atmosphere-01/doutriaux1/doutriaux1/UV-CDAT/2015-03-02/bin/setup_runtime.sh
```
for me via X11 there's a lot of hanging.

I still an pop-up error message about the bad time units but it doesn't seem to prevent resizing.

I chmoded everything 777 so you can give it a try, let me know if it is also painfully slow for you or not and if the reszie issue seems to be worked out

**Comment by stott** [comment]
I just tried your build on Atmosphere. There does not appear to be a lot of
hanging, at least on this initial look.

The refresh problem is fixed and resizing works fine.

 However, the time steps do not display so that when stepping through time
steps in the simulation there is no way of knowing where/when you are.

And, when clearing a plot, the "Clear cell" pop-up window hangs (does not
close) after selecting "yes". And at that point it will not refresh

Lowell

On Mon, Mar 2, 2015 at 1:48 PM, Charles Doutriaux <notifications@github.com>
wrote:

> @stott <https://github.com/stott> ok I built on your system it is at
>
> source /home/atmosphere-01/doutriaux1/doutriaux1/UV-CDAT/2015-03-02/bin/setup_runtime.sh
>
> for me via X11 there's a lot of hanging.
>
> I still an pop-up error message about the bad time units but it doesn't
> seem to prevent resizing.
>
> I chmoded everything 777 so you can give it a try, let me know if it is
> also painfully slow for you or not and if the reszie issue seems to be
> worked out
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76833188>.
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
yes the "time" cannot disply because your time units are broken. I guess we could fallback on simply plotting the plain time value (not converted to time since we cant) in such cases? Or should we use index? @stott if you think it is something useful please submit a new issue for this and i will put it in for 2.3

**Comment by stott** [comment]
This worked fine in version 1.5. It is absolutely necessary to display time
units in Isofill (and similar) displays of time series results.

And what about freezing while clearing the plot?  I left this open if you
want to log on to Atmosphere to see it.

On Monday, March 2, 2015, Charles Doutriaux <notifications@github.com>
wrote:

> yes the "time" cannot disply because your time units are broken. I guess
> we could fallback on simply plotting the plain time value (not converted to
> time since we cant) in such cases? Or should we use index? @stott
> <https://github.com/stott> if you think it is something useful please
> submit a new issue for this and i will put it in for 2.3
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76844884>.
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
@stott can you point me to the data on atmosphere please

**Comment by stott** [comment]
The data is at: atmosphere-00/stott/GENIE-Output

On Mon, Mar 2, 2015 at 5:25 PM, Charles Doutriaux <notifications@github.com>
wrote:

> @stott <https://github.com/stott> can you point me to the data on
> atmosphere please
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76868650>.
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by stott** [comment]
sorry, a more explicit link would be:

atmosphere-00/stott/GENIE-Output/TEST71a/biogem


with in the folder biogem you'll see two .nc files.

Use the "fields_biogem_3d.nc"

On Mon, Mar 2, 2015 at 5:37 PM, Lowell Stott <stott@usc.edu> wrote:

> The data is at: atmosphere-00/stott/GENIE-Output
>
> On Mon, Mar 2, 2015 at 5:25 PM, Charles Doutriaux <
> notifications@github.com> wrote:
>
>> @stott <https://github.com/stott> can you point me to the data on
>> atmosphere please
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UV-CDAT/uvcdat/issues/1007#issuecomment-76868650>.
>>
>
>
>
> --
> Professor
> Department of Earth Sciences
> University of Southern California
> Los Angeles, CA 90089
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089
