### ISSUE TITLE
Traceback creating VCS plot

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1019]
```
Traceback (most recent call last):
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 930, in dropEvent
    self.sheet.selectCell(row, col, False)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_sheet.py", line 507, in selectCell
    self.setActiveCell(row, col)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_sheet.py", line 517, in setActiveCell
    toolBar = self.parent().getCellToolBar(row, col)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 252, in getCellToolBar
    container.toolBar = toolBarType(self)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/spreadsheet/spreadsheet_cell.py", line 326, in __init__
    self.createToolBar()
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1559, in createToolBar
    if cell.inputPorts[0][0].var.var.rank()>2:
AttributeError: 'QCDATWidget' object has no attribute 'inputPorts'
```

**Comment by remram44** [comment]
It looks like the `inputPorts` attribute is only set in `updateContents()`, which doesn't necessarily occurs before `selectCell()`. In fact, `updateContents()` will only set it if `fromToolBar` is false. It doesn't look like this attribute should be used.

**Comment by aashish24** [comment]
@remram44 who is looking into fixing this?

**Comment by remram44** [comment]
I don't know what this does and I don't know who broke it.

@vvpalav and @hgohil2805 are supposed to be working on GUI issues, I'm sure they'll get around this one sometime.

**Comment by remram44** [comment]
Ran into this again. @vvpalav, @hgohil2805: any updates?

**Comment by vvpalav** [comment]
I am still looking into this .. will post updates in some time

**Comment by remram44** [comment]
I'm looking into this. It looks like it comes from a change in VTK again.

On uvcdat b8d44ef3, this call works: `SetDisplayId('_c35650_void_p')`
UV-CDAT is b8d44ef3 build Feb 19 afternoon, VTK-gitinfo.txt says `tag='uvcdat-2.1.0'`; VisTrails is cb2220ba.

On uvcdat 66cfd540, this call fails: `SetDisplayId('_f02100_void_p')`
`TypeError('SetDisplayId argument 1: value is _f02100_void_p, required type is p_void',)`
UV-CDAT is 66cfd540 built Feb 19 morning, VTK-gitinfo.txt says `tag='uvcdat-master'`; VisTrails is cb2220ba.

The `QCDATWidget`'s (inheriting `QVTKWidget`) `updateContents()` fails in `QVTKWidget#SetRenderWindow()` and the widget is invalid from there on.

I don't know what the versions mean in term of VTK since that seem to happen outside of version control?

**Comment by remram44** [comment]
From Github's reflog, looks like VTK 'uvcdat-master' would have been [32966e7](https://github.com/UV-CDAT/VTK/compare/uvcdat-2.1.0...32966e790327bff54b2260338f7d8817169a61ae), hope that helps.

**Comment by dlonie** [comment]
Interesting. A couple questions:

1) I assume the `SetDisplayId` is on some `vtkRenderWindow` instance?

2) If so, can you print the exact name of the class that this is failing on? I'll need to know the subclass we're using to dig much deeper.

3) Can you point me at the location in uvcdat/vistrails that is failing? This will help me track this down a bit further.

**Comment by remram44** [comment]
Sure!

Location is [vtkcell.py line 356, in QVTKWidget#SetRenderWindow()](https://github.com/UV-CDAT/VisTrails/blob/cb2220ba88e957006c3dcc098ef29c5c08461117/vistrails/packages/vtk/vtkcell.py#L356)
```
(Pdb) p self.mRenWin
(vtkXOpenGLRenderWindow)0x7f531d901110
(Pdb) p vp
'_10793e0_void_p'
(Pdb) p type(vp)
<type 'str'>
```

**Comment by dlonie** [comment]
I suspect something might have changed with how the python wrappers handle conversions to the void* type. I'll check with the maintainer of the wrapping code to see if he knows what's happening.

**Comment by remram44** [comment]
Alright, thanks. This might affect VisTrails 2 as well; @rexissimus do you know anything about `SetDisplayId()` failing on new versions of VTK?

**Comment by rexissimus** [comment]
VisTrails does not use the latest version of VTK yet so this will probably will affect VisTrails as well. The code will probably have to be modified but I don't know if this use of SetDisplayId documented somewhere.

**Comment by rexissimus** [comment]
According to https://github.com/Kitware/VTK/commit/e12eb1f415029a537a6eb52e0adfc02a81c74a5d, it should be enough to change `void_p` to `p_void` (For the appropriate VTK version) in [vtkcell.py](https://github.com/UV-CDAT/VisTrails/blob/cb2220ba88e957006c3dcc098ef29c5c08461117/vistrails/packages/vtk/vtkcell.py#L349).

**Comment by dlonie** [comment]
@rexissimus is correct -- this is what our wrapping guru said as well. Does that fix the issue for you?

**Comment by dlonie** [comment]
Looks like the new syntax is required in v6.2.0 and up.

**Comment by remram44** [comment]
Filed UV-CDAT/VisTrails#16 that should fix this (please review, my build is broken)
Also filed against VisTrails 2 since this is probably going to hit us eventually (VisTrails/VisTrails#1001)
