### ISSUE TITLE
Configure travis to additionally test "full" builds

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1033]
It seems that currently travis is only testing "default" builds, which exclude a number of packages that are built during a "full" build (Cython, Matplotlib, Spyder, iPython and many others).

It would be good to configure travis to additionally test "full" builds so that any issue cropping up with these additional libraries will be discovered when the PR is issued - may as well get travis tests working across the full build system.

The issue is discussed within #1025, #1023, #921, #941, #856..

@doutriaux1 @aashish24 can you set this as a 2.2+ milestone?

**Comment by durack1** [comment]
@doutriaux1 another 2.3 candidate..

**Comment by durack1** [comment]
@doutriaux1 @aashish24 it would seem that travis-ci has a build timeout of [120 mins vs 50 for travis](http://docs.travis-ci.com/user/build-configuration/#Job-Timeouts).

It also seems that using the [build matrix](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix) differing build options should be configurable..

It would be very helpful to convert builds to test `ALL` as I've just managed to introduce a couple of problems with recent PRs that should have been identified if the added packages were in fact built

**Comment by durack1** [comment]
@doutriaux1 @aashish24 has this issue been rendered obsolete with the new build_bot testing? If so please close.

**Comment by aashish24** [comment]
Yes, it is obsolete.
