### ISSUE TITLE
Adding h5py to "full" builds

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1034]
Folks I've been using the HDF5Tools which is a fairly old python wrapper for HDF5 which has required a number of tweaks to get it working on very recent data.

The [h5py project](http://www.h5py.org/) seems to be a currently supported and more up-to-date library that would certainly benefit me - it's available from github: https://github.com/h5py/h5py

@doutriaux1 @aashish24 what do I need to do to get this library into the repo, as a library built under a "full" build? I can upload the tar ball, but am wondering where I should create these files `CMake/cdat_modules` or `CMake/cdat_modules_extra`?

**Comment by doutriaux1** [comment]
@durack1  take a look at matplotlib that should do it.

**Comment by durack1** [comment]
@doutriaux1 another 2.3 candidate..

**Comment by durack1** [comment]
@doutriaux1 @aashish24 would it be possible to get this in as a 2.2 item? It would seem that both this and #800 both need some very subtle tweaks... @aashish24 I think this depends on you..

**Comment by doutriaux1** [comment]
I sure hope so! @aashish24 ther's also the pyclimate issue that is similar.
