### ISSUE TITLE
Provide a 'transparent' color for missing values (isofill/boxfill/etc... plots)

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#1042]
Would it be possible to **plot the missing values with a transparent color**? That could probably best be achieved by, when requested, *not plotting anything where there is a missing value*

This would *make it possible to emulate outfill with boxfill* (if we have to say goodbye to outfill, https://github.com/UV-CDAT/uvcdat/issues/999#issuecomment-74843597) and would be useful when you want to overlay an isofill/boxfill plot on top of another plot, and want to see some of the data below

The user could specify it the following way
```
isof = x1.createisofill(None)
isof.missing = None
bf = x1.createboxfill(None)
bf.missing = None
```

Maybe there is already a way to do this that I don't know of. It's a feature I have needed from time to time, but I did not have time to formally request it

**Comment by doutriaux1** [comment]
@jypeter I am planning on adding transparency to the colortables, but not for this version. Maybe 2.3 or 3.x

**Comment by jypeter** [comment]
Will you be using some alpha channel opacity stuff?

What about the *not plotting masked cells when the specified missing value is None*? This may be naive, but is not the code mostly already in place for that?

**Comment by doutriaux1** [comment]
@sankhesh I think we pretty much implemented this by now, so I'm reassigning to you so that you can close via git commit.
