### ISSUE TITLE
Use zlib 1.2.8 rather than 1.2.5

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1054]
I'm just wondering if there is a reason that we're still building 1.2.5 rather than the updated 1.2.8 source which was uploaded a while back - the zlib_pkg.cmake file seems to be a fair bit more confusing than it needs to be:

https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/zlib_pkg.cmake#L1-13

Are there problems building 1.2.8? Does it conflict with something?

**Comment by durack1** [comment]
@doutriaux1 a 2.3 candidate..

**Comment by durack1** [comment]
@doutriaux1 from the [ChangeLog](http://www.zlib.net/ChangeLog.txt) it looks like some nasty bugs were fixed in the latest release 1.2.8 and using 1.2.3 (or the system defaults - redhat6.6 1.2.3) is not really the best idea.. It'd be great to force all packages to use a 1.2.8 built version in 2.3+

**Comment by doutriaux1** [comment]
@durack1 we don't build zlib anylonger, we use system one.
