### ISSUE TITLE
test failing because mean is different 

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1063]
https://open.cdash.org/testDetails.php?test=315268558&build=3704218

**Comment by doutriaux1** [comment]
that one is odd. I reuploaded a new value for mean because on my mac it seems different than on my ubunutu! LEt me retest that one.

**Comment by doutriaux1** [comment]
looking into this one. Turns out the actual data sent to plot is slightly different between mac and linux...
the test code does:
```
  nm_xtra="_amplitude"
  U=numpy.cos(lons[:])
  V=numpy.sin(lats[:])
  A=MV2.array(V[:,numpy.newaxis]*U[numpy.newaxis,:])
  A.setAxis(0,lats)
  A.setAxis(1,lons)
  u*=A  
  v*=A  
```
That could explain the precision difference
diff plot:
![diff](https://cloud.githubusercontent.com/assets/2781425/6363094/33a0de20-bc49-11e4-9f71-b4faae624e30.png)
