### ISSUE TITLE
Remove x.png size parameters ?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#1068]
Should the *width* and *height* parameters of x.png (and possibly other canvas output functions) be removed, if they are not used any more, because you now have to use x.setbgoutputdimensions()?

Or can you have x.png automatically call x.setbgoutputdimensions()? This may not be possible, because I vaguely remember that you have to call setbgoutputdimensions first

**Comment by doutriaux1** [comment]
fixed
