### ISSUE TITLE
Pyclimate not built with build mode all

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1071]
I think build mode all still skips this and maybe a few others pysphram, windfield eof etc...

**Comment by durack1** [comment]
@doutriaux1 this should fix pyclimate.. Was anything else having problems (pyspharm should be fixed by #1074)

**Comment by durack1** [comment]
@doutriaux1 it seems like this is being prompted to build:
`[INFO] These are the packages that we will try to build: basemap;CDAT;CURL;Cython;FFMPEG;g2clib;gdal;GEOS;gui_support;h5py;HDF5;ZMQ;pyzmq;tornado;IPYTHON;jasper;jpeg;LAPACK;lepl;libcf;Matplotlib;SIX;DATEUTILS;PYPARSING;Mpi4py;PYOPENSSL;setuptools;MyProxyClient;NetCDF;NetCDFPLUS;Numexpr;NUMPY;MPI;OSMesa;Python;VTK;pkgconfig;png;pyspharm;PyTables;readline;R;scikits;SCIPY;pip;Shapely;pygments;markupsafe;jinja2;docutils;Sphinx;freetype;zlib;libXML2;libXSLT;png;pixman;fontconfig;tiff;Curses;CMOR;udunits2;uuid;UVCMETRICS;vistrails;YASM;PYLIBXML2;CDATLogger;**pyclimate**;scientificpython;windspharm;eof2;eofs;windfield`
