### ISSUE TITLE
Resize makes the GUI sleep on a powerful system

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1092]

**Comment by doutriaux1** [comment]
assigning to myself until @chaosphere2112 and I looked at it closer.

**Comment by vvpalav** [comment]
@doutriaux1 @aashish24 @chaosphere2112 we will look into this one from our side, but we didn't change anything major GUI code so it will be better if someone from backend also start looking into this issue.

@remram44 Can you please comment if you have any idea about this one???

**Comment by remram44** [comment]
What is the issue? I don't think I have a "powerful system" anyway.

**Comment by vvpalav** [comment]
I am trying this on my virtual box ubuntu 14.04 .. tried resizing GUI several times, its little slow but not sleeping for considerable time. Probably its slow cause I am on VBox. 
@aashish24  can you please give us more info like is it happening on specific system or configuration.

**Comment by chaosphere2112** [comment]
@aashish24 Can you try commenting out all of the lines with `self.configurator` in Canvas.py and retrying? That will tell us if it's an issue with my VCS Interactivity code or something else.

**Comment by ThomasMaxwell** [comment]
Vcs3 d hide 3d controls for 2d plots #1095
 Open
ThomasMaxwell<https://github.com/ThomasMaxwell> wants to merge 2 commits into master from vcs3D-hide_3d_controls_for_2d_plots

**Comment by doutriaux1** [comment]
@aashish24 I see the super slowness when plotting via Xforwarding from a centos to a ubuntu.
will test @chaosphere2112 suggestion now.

**Comment by doutriaux1** [comment]
@chaosphere2112 "good" news "configurator" does noit cause the slow down, it is happening when rendering the template, each text string takes for ever to be drawn.

**Comment by chaosphere2112** [comment]
Cool, glad I didn't break this :smile:

**Comment by vvpalav** [comment]
This doesn't seems to be a GUI issue. Tried on ubuntu on virtual box. when we resize, vcs is recreating all plots as per new size. @remram44 is going to take a deep look. Please post any recent updates if this still exists.

**Comment by vvpalav** [comment]
reassigning this to @aashish24 for tracking purpose as it doesn't seem to be a gui issue, but me and @remram44 will take a look as time permits. Please feel free to reassign to me if you find something wrong with GUI which is doing this.

**Comment by doutriaux1** [comment]
@aashish24 feel free to re-open I think this is not worth looking at in the light of the GUI changes coming in soon.
