### ISSUE TITLE
invalid framebuffer operation

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1100]
When I used the AMWG diagnostics to draw an isofill lat-lon contour plot (set 5), I got thousands of these messages:

ERROR: In /Users/painter1/tmp/uvcdat/build/VTK/Rendering/OpenGL/vtkOpenGLPolyDataMapper2D.cxx, line 442
vtkOpenGLPolyDataMapper2D (0x7fcaa2506220): failed after RenderOverlay 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation

The plots are correct, but my screen is still scrolling them by them many minutes later.

**Comment by doutriaux1** [comment]
@painter1 do you have a fresh build? Looks like your vcs and VTK might be out of sync, I'd recommend a fresh build from scratch first.

**Comment by painter1** [comment]
You're right.  I reinstalled a bug fix I had done in VCS (not in this issue tracker yet) and this problem went away.
