### ISSUE TITLE
colormap editor behaves weirdly

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1104]
Colormap editor behaves weirdly when editing color table from color picker. Please check below screenshot.

![687474703a2f2f692e696d6775722e636f6d2f6e6d32787535752e706e67](https://cloud.githubusercontent.com/assets/6840965/6467523/cf59f77c-c19c-11e4-83c6-5fe4b5f2d61d.png)

**Comment by doutriaux1** [comment]
@chaosphere2112 should we replace this with your widget? Do you have blend and save capabilities?

**Comment by chaosphere2112** [comment]
Maybe in 2.3; all I have right now is a color picker that will let you choose a color out of the existing colormaps. Shouldn't be too hard to leverage some of that code to build a fully-VTK colormap builder, but not by tomorrow :wink:

**Comment by vvpalav** [comment]
Pull request created for this issue.
https://github.com/UV-CDAT/VisTrails/pull/20
