### ISSUE TITLE
Isofill are off

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1105]
When plotting isofill data for a user we noticed her max was 89.999 but isofill on plot stop at the 70-80 interval . Using version 1.5.1 isofill are correct.  2.0 and 2.1 are wrong
Will post pix soon

**Comment by doutriaux1** [comment]
@dlonie @aashish24 I think/hope it's a bug in my look-up table. Boxfill custom works. Can you please take a look at it at same time as me. This is MAJOR we can't release with this bug.

**Comment by doutriaux1** [comment]
our version (BAD)
![bad](https://cloud.githubusercontent.com/assets/2781425/6473566/0d72ca5e-c1af-11e4-9f5e-ccb18af166eb.png)

1.5.1 version (good)
![good](https://cloud.githubusercontent.com/assets/2781425/6473577/1e35cab2-c1af-11e4-895d-54e4bc164432.png)

**Comment by doutriaux1** [comment]
@aashish24 @dlonie no idea what is wrong here.

I'm looking at:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/VisualizationAlgorithms/BandedPolyDataContourFilter
and it seems we're doing it right here. Please take a look it is very critical.
putting script and data in an email soon.

**Comment by doutriaux1** [comment]
@dlonie @aashish24 I think the problem might be at the VTK level. Bellow is a plot with an isoline at "70"
That seems to confirm isoline and isofill both agree there's no data greater than 80... I thought it might be a lookup table issue but it seems to be a contouring issue.
![bad](https://cloud.githubusercontent.com/assets/2781425/6476858/2fa28850-c1d0-11e4-907a-968083a3075b.png)

**Comment by doutriaux1** [comment]
notice how the "10" level seems to be identical between both 2.X and 1.5. It might be VTK algorithm that is just weak

**Comment by doutriaux1** [comment]
if that's case I thik we need to very quickly re-implement the old algoritthm from vcs_legacy source code (look at: https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs_legacy/Src/library/isolines.c ) @williams13 what do you think?

**Comment by doutriaux1** [comment]
@aashish24 @dlonie should we try this?

http://www.vtk.org/doc/release/5.0/html/a01702.html

**Comment by doutriaux1** [comment]
nope... no difference...

**Comment by aashish24** [comment]
@doutriaux1 I or @dlonie will look into it later tomorrow.

**Comment by doutriaux1** [comment]
Thanks @aashish24 two possibilities come to my mind right now. 1) pole points maybe treated differently between both methods. 2) not many points with the max value maybe causing The diff

**Comment by williams13** [comment]
We have to have this fixed before the release! We don't want users to compare our output with NCL and say that our software is wrong. 

Our old algorithms work and have been vetted for over 3 decades.

**Comment by dlonie** [comment]
Looking into it.

**Comment by williams13** [comment]
Thanks David. This is a big deal.

**Comment by dlonie** [comment]
Toss this back my way if I'm missing something, but it looks like the data going into the contour generator doesn't match the data you describe -- the max value in the input is 75.49:

    --- Packages/vcs/Lib/VTKPlots.py
    +++ Packages/vcs/Lib/VTKPlots.py
    @@ -975,6 +975,8 @@ class VTKVCSBackend(object):
                       r,g,b = cmap.index[color]
                       lut.SetTableValue(j,r/100.,g/100.,b/100.)
                   luts.append([lut,[0,len(l)-1,True]])
    +              print "data range (pre contour):",sFilter.GetOutput().GetPointData().GetScalars().GetRange()
    +              print "data range (post contour):",cot.GetOutput().GetPointData().GetScalars().GetRange()
                   mapper.SetLookupTable(lut)
                   mapper.SetScalarRange(0,len(l)-1)
                   mapper.SetScalarModeToUseCellData()
 
Prints:
    data range (pre contour): (0.0, 75.48797607421875)
    data range (post contour): (0.0, 75.48797607421875)

The contours appear correct for the data.

**Comment by doutriaux1** [comment]
hum... let me look into this. It's weird... But if that's the case that's great news that means quick fix!

**Comment by doutriaux1** [comment]
@dlonie 

```
diff --git a/Packages/vcs/Lib/VTKPlots.py b/Packages/vcs/Lib/VTKPlots.py
index 474334a..0ea07b4 100644
--- a/Packages/vcs/Lib/VTKPlots.py
+++ b/Packages/vcs/Lib/VTKPlots.py
@@ -772,17 +772,14 @@ class VTKVCSBackend(object):
       sFilter = vtk.vtkDataSetSurfaceFilter()
       if cellData:
           # Sets data to point instead of just cells
+          print "CELL2POINT"
           c2p = vtk.vtkCellDataToPointData()
           c2p.SetInputData(vtk_backend_grid)
           c2p.Update()
-          if self.debug:
-            vcs2vtk.dump2VTK(c2p)
           #For contouring duplicate points seem to confuse it
           if vtk_backend_grid.IsA("vtkUntructuredGrid"):
               cln = vtk.vtkCleanUnstructuredGrid()
               cln.SetInputConnection(c2p.GetOutputPort())
-              if self.debug:
-                vcs2vtk.dump2VTK(cln)
               sFilter.SetInputConnection(cln.GetOutputPort())
           else:
               sFilter.SetInputConnection(c2p.GetOutputPort())
@@ -975,6 +972,9 @@ class VTKVCSBackend(object):
                   r,g,b = cmap.index[color]
                   lut.SetTableValue(j,r/100.,g/100.,b/100.)
               luts.append([lut,[0,len(l)-1,True]])
+              print "User data range (pre VTK):",vcs.minmax(data1)
+              print "data range (pre contour):",sFilter.GetOutput().GetPointData().GetScalars().GetRange()
+              print "data range (post contour):",cot.GetOutput().GetPointData().GetScalars().GetRange()
               mapper.SetLookupTable(lut)
               mapper.SetScalarRange(0,len(l)-1)
               mapper.SetScalarModeToUseCellData()
```
gives:
```
CELL2POINT
User data range (pre VTK): (0.0, 89.231689453125)
data range (pre contour): (0.0, 75.48797607421875)
data range (post contour): (0.0, 75.48797607421875)
```

So I thin kthe issue comes from cell2point filter, is there a way to avoid calling cell2point? I will look into this but you will probably beat me to this.

**Comment by doutriaux1** [comment]
also setInputData should probably be changed to setInputConnections right?
```
        if cellData:
          cot.SetInputData(sFilter.GetOutput())
```

**Comment by dlonie** [comment]
On Wed, Mar 4, 2015 at 2:15 PM, Charles Doutriaux <notifications@github.com>
wrote:

> also setInputData should probably be changed to setInputConnections right?
>
>         if cellData:
>           cot.SetInputData(sFilter.GetOutput())
>
>
Eventually, yes, but it really doesn't matter at this point. There really
isn't a pipeline design built into the VTK/vcs layer, so connecting two
isolated filters won't make any difference.

It really only makes a difference when you have an unbroken chain of
persistent filters running from the data source to the mapper/actor. Since
most filters in UVCDAT are isolated and the mapper/actor are thrown away
and replaced a few times before being added to a renderer, the automatic
pipeline execution cannot work.

**Comment by doutriaux1** [comment]
I agree it's a side problem that will fix after 2.2 is out. The real issue here is  how to avoid cell2point? can't you send directly a structuredGrid with cellData to vtkBandedCountour?  c2p is doing some sort of interpolation which is kind of what we are really asking isoline to do anyway.

**Comment by doutriaux1** [comment]
@dlonie should I construct the grid differently if going to isofill? i.e use nodes rather than cellData?

**Comment by dlonie** [comment]
You are correct -- the vtkCellDataToPointData filter is interpolating the celldata for the points and none of the interpolated values are above 75.

It looks like the vtkBandedPolyDataContourFilter only contours around the point scalars, so if  it's possible to construct the grid differently to set the point data as vcs expects, that should work.

**Comment by doutriaux1** [comment]
Ok I will do that this afternoon

**Comment by doutriaux1** [comment]
@aashish24 @dlonie I pushed my changes to: https://github.com/UV-CDAT/uvcdat/tree/isofill_on_pointdata_struct_grid

Still my datasetsurfacefilter comes out with no data! I'm sure it's a 10 minute fix. Use the code/data I sent yesterday by email for testing. 

Thanks.

**Comment by dlonie** [comment]
The dataset coming out of genGridOnPoints is a 1D line along the Y axis:

Dimensions: (1, 4785, 1)
Extent: (0, 0, 0, 4784, 0, 0)

Shouldn't it be a 2D plane on x/y?

Looks like there's a problem with how that function is interpreting the points. I'm not familiar with the format of the data going into genGridOnPoints(), so I'll let you take a look.

**Comment by doutriaux1** [comment]
Hum. That is the same function that we use for vector plots. I will take a look again. Thanks

**Comment by doutriaux1** [comment]
Yeah ! got it! It did fix the continetns as well! Need to regenrate all baselines now. Will push a PR soon. Thanks @dlonie

**Comment by dlonie** [comment]
@doutriaux1 Great! I'll take a look once it's pushed.
