### ISSUE TITLE
Continents are off

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1106]
When plotting data with a user we noticed the continents seem to be a bit to much up north.
1.5.1 is ok. Png to follow soon

**Comment by doutriaux1** [comment]
our version (BAD)
![bad](https://cloud.githubusercontent.com/assets/2781425/6473566/0d72ca5e-c1af-11e4-9f5e-ccb18af166eb.png)

1.5.1 version (good)
![good](https://cloud.githubusercontent.com/assets/2781425/6473577/1e35cab2-c1af-11e4-895d-54e4bc164432.png)

**Comment by doutriaux1** [comment]
actually the continents look good, it's almost as if the data is shifted rather than continents

**Comment by doutriaux1** [comment]
@dlonie I think it is because we set the data on "cellData" rather than "pointData" I'm using ployDataMApper and DatasetMAppers, do they do anything with the grid if data is on cells? It is odd.

Please use the same script/data (bad.nc) I sent earlier and switch between isofill or boxfill for gms, you will see the data shift dramatically when switching. Moving isoline/fills from cellData to pointData seems to have fixed this.

Any idea?

Bellow the good (isofill) and bad/shifted (boxfill) data
good:
![ok](https://cloud.githubusercontent.com/assets/2781425/6518139/c9757ed2-c357-11e4-9bea-1a807813c276.png)
and bad:
![bad](https://cloud.githubusercontent.com/assets/2781425/6518142/d7b1b042-c357-11e4-99d0-7e2aefd10996.png)

**Comment by doutriaux1** [comment]
and good version of boxfill, generated with 1.5.1 (excpet for colors)
![bad](https://cloud.githubusercontent.com/assets/2781425/6518283/6569bac8-c359-11e4-9da1-2c628f673895.png)

**Comment by doutriaux1** [comment]
@dlonie any ideas?

**Comment by dlonie** [comment]
I suspect it has something to do with the transforms that are used to
resize / translate the data (the fitToViewport stuff, IIRC). I'd start
looking there.

It seems to me that it'd be more robust to not rescale/stretch/etc the data
with a transform, but rather leave the data in the same coordinate system
and adjust the viewport/camera to get the desired view -- It's fewer things
to keep track of and less error prone. Is there a reason for using the
transforms that I'm missing?

**Comment by doutriaux1** [comment]
@aashish24 you designed this at the very beginning of the VTK rewrite, can you take a look please? 
@dlonie the problem though is we do want to stretch/squeeze the data to fit the viewport, is that doable w//o a transform?

**Comment by dlonie** [comment]
@doutriaux1 Yes, the `vtkCamera` class provides complete control over the modelview and projection matrices, which allow anisotropic stretching/scaling. The `vtkPerspectiveTransform` class can be used to help define the matrices, in particular `vtkPerspectiveTransform::Ortho` method looks like what we'd want.

**Comment by dlonie** [comment]
BTW, I'm not suggesting that as a fix for 2.2. If we make the camera/viewport-instead-of-actor-transforms change, it would be as part of the post-2.2 work.

**Comment by doutriaux1** [comment]
@williams13 I think @dlonie is right. It's part of making everything "the-right-vtk-way" It's slightly off on boxfill plots for noew but isoline/isofill are correct. I'd say let ship 2.2 like that and fix it for 2.3/3.0. Thoughts?

**Comment by williams13** [comment]
I just don’t want users to compare the output with other packages and say UV-CDAT gives wrong output. This will be very bad!

**Comment by aashish24** [comment]
@doutriaux1 this is still broken right?

**Comment by doutriaux1** [comment]
Oh! I have the data now, I need to double check.

**Comment by aashish24** [comment]
@doutriaux1 did you check?

**Comment by aashish24** [comment]
@sankhesh do you think @danlipsa can look into this? Can you help?

**Comment by sankhesh** [comment]
Yes. This should have been fixed already. @doutriaux1 was going to check.

@danlipsa may be able to verify.

**Comment by doutriaux1** [comment]
doh! I'm on it.

**Comment by aashish24** [comment]
thanks @doutriaux1

**Comment by danlipsa** [comment]
@doutriaux1 @sankhesh @aashish24 I run the script that Charles gave me and the bad.nc that Dave Lonie gave me and got an image identical with the good image that Charles sent on March 5th -- see attached. Charles, can you check and close the issue - Thanks.

![bad](https://cloud.githubusercontent.com/assets/6180727/11195066/c53ad11a-8c7d-11e5-832c-b6ea2e645430.png)

**Comment by sankhesh** [comment]
@danlipsa Could you also post an image of the boxfill plot?

**Comment by danlipsa** [comment]
I commented out createisofill() and uncommented createboxfill(). Here is the image:
![bad](https://cloud.githubusercontent.com/assets/6180727/11195235/f78fa126-8c7e-11e5-8cd3-fa3a754c21b6.png)

**Comment by doutriaux1** [comment]
@danlipsa it still seems that we have a lot of seance inside greenland and greenland should be empty. If you look at my "good" (purple) png I posted on this thread, Greenland is mostly w/o any sea-ice in it.

**Comment by danlipsa** [comment]
I see. So isofill is correct but boxfill is not?

**Comment by doutriaux1** [comment]
yes, exactly. I believe it is because one is using cellmate and the other point data filters.

**Comment by danlipsa** [comment]
Sounds good. I will take a look.

**Comment by aashish24** [comment]
@danlipsa any update?

**Comment by danlipsa** [comment]
@aashish24 no result yet.

**Comment by danlipsa** [comment]
@doutriaux1 Can I have the bad.nc you have? I am not sure but the data I have seems slightly different. Notice the maximum occurs in level 4 for my image (magenta color) and in level 3 for your good image (deep red color). Thanks.

**Comment by danlipsa** [comment]
@doutriaux1 As we have discussed in the meeting, the missing row at 90 degrees seem to be the problem. All rows are shifted up by one, which explains why we have ice over Greenland and also answers why the maximum occurs in different rows for the two images.
