### ISSUE TITLE
test_isolines_label

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1111]
no labels on it... even baseline does not have them... What hapend? Some merge undid @dlonie work?

**Comment by doutriaux1** [comment]
on the bright spot:
https://github.com/UV-CDAT/uvcdat/blob/master/testing/vcs/test_vcs_isoline_labels_multi_label_input_types.py
still works, maybe just an issue with passing no text or string texts, will check, re-assignig to me

**Comment by dlonie** [comment]
Both pass for me on current master.

**Comment by doutriaux1** [comment]
they pass but one is wrong, there's no label on test_isolines_label :wink:

**Comment by doutriaux1** [comment]
see: https://github.com/UV-CDAT/uvcdat-testdata/blob/master/baselines/vcs/test_isoline_labels.png

no labels
