### ISSUE TITLE
Needs to remove default method in GUI

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1117]
I am using UVCDATv2.1-GUI on Rhea.
I need to control the color scale for Boxfill plots.   It is particularly important  that the colorscales are the same when trying to compare two plots of the same variable from different simulations.  Note that it is not the colors that I need to change, but the assignment of colors to values of each cell.  The problem is that when I bring up the vizualization properties, the section for the colorscale is greyed out, and cannot be changed.

**Comment by doutriaux1** [comment]
yes you can't edit default. in 2.2 we re-introduced copies of "default" named "a_boxfill" which is editable.

**Comment by doutriaux1** [comment]
actually I reopen for 2.3 we shouldn't be listing "default" graphic method inside the GUI at all.

**Comment by vvpalav** [comment]
Hey @doutriaux1 .. so we want to remove default from available color scales on colormap editor?
then what happens when we change color scale and apply it to the plot and wanted to reset back to default? Can you please give more information about this so that we don't end up breaking something else.

**Comment by doutriaux1** [comment]
@vvpalav the "Default" cannot be edited. SO we should remove it from the list, instead there are currently "copies" of the "default" gm named "a_boxfill" for example. This can be edited. 
I have no idea how vistrails works under the sheets but it probably makes a copy of "whatever graphic method (gm) was dropped in" so you can revert back to that. The better way to do it would probably be to "copy" the gm and then edit the copy directly, this will actually solve the "default" can't be edited issue as well. 
At one point it used to work like that because Emanuel was worried that if you change the "dropped" method directly and used it in other plots it would change the other plots as well. I have no idea how it works these days within Vistrails.

**Comment by cameronsmith1** [comment]
I just tested version 2015-3-5.  The a_boxfill was available and worked as expected.

Can I suggest adding a note in the properties box for the 'default' boxfill that alerts the user to the fact that "the color scale cannot be changed for the default, but can be changed for the other boxfill types".     This will help cut down on other people asking the same question.

**Comment by vvpalav** [comment]
@doutriaux1 I was talking with @remram44 and decided to work on this if its really necessary and hurting something badly. Currently needs to start some other urgent stuff in GUI. Please let me know the priority and we can plan accordingly.

**Comment by doutriaux1** [comment]
@vvpalav ye sit is absolutely not urgent, @cameronsmith1 is happy with the a_boxfill solution for 2.2

**Comment by vvpalav** [comment]
changed the title to appropriate topic.

**Comment by vvpalav** [comment]
Instead of removing this completely from dropdown, I simply disabled colortable for default. So now user just can't modify colors when default is selected. I will commit my changes so that you guys can take a look. Any suggestions are welcome.

**Comment by vvpalav** [comment]
@doutriaux1 .. Is it possible to rename "default" gm to "default (non-editable)" ?
I have disabled color buttons when default is selected, so that user cannot edit anything. 
if we rename gm to "default (non-editable)" then It will be more clear to user, why color table is disabled.

**Comment by doutriaux1** [comment]
@vvpalav if it's at the vistrails level feel free to do whatever you need. the "default" at the vcs level though does need to stay named "default" lots of places in the code expect that (mostly new objects creations and attribute setting verifications)
