### ISSUE TITLE
UV-CDAT docs website: cdms/cdtime manual page problem

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1136]
@mattben @chaosphere2112

It seems that the time constructor section of http://uvcdat.llnl.gov/documentation/cdms/cdms_3.html needs a tweak or two..

**Comment by durack1** [comment]
@doutriaux1 maybe a new "website" label could be useful here

**Comment by doutriaux1** [comment]
Done. Good idea

**Comment by chaosphere2112** [comment]
@durack1 @doutriaux1 We were hoping to have website issues get filed against the website's repo: https://github.com/UV-CDAT/uvcdatsite

I'll add this to my list of documentation fixes.

**Comment by durack1** [comment]
@chaosphere2112 thanks for the tipoff, I should have thought of that.. Migrated to https://github.com/UV-CDAT/uvcdat-site/issues/46
