### ISSUE TITLE
Colormap open saved color table

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1150]
@williams13 @doutriaux1 @potter2
I have opened this issue to implement new feature to import saved color table into colormap editor.
Can you please provide more information or expectations which might help me in this.

**Comment by doutriaux1** [comment]
@vvpalav few pointers "colormap" objects (and all vcs objects) have a .script function.

I think what @williams13 and @potter2 really want is a button somewhere to read back in these user-saved scripts which can be loaded with:
```
import vcs
x=vcs.init()
x.scriptrun("/path/to/my/script.json")
```

**Comment by vvpalav** [comment]
@williams13 @doutriaux1 @remram44 .. I finished this one on 1150_open_saved_colormap branch. Added open button to select json file. can you please take a look and let me know if its good?

**Comment by vvpalav** [comment]
@aashish24 @chaosphere2112 @doutriaux1 .. can you please review this?

**Comment by doutriaux1** [comment]
@vvpalav will do. You don't want to generate a PR yet?

**Comment by remram44** [comment]
It's UV-CDAT/VisTrails#25
