### ISSUE TITLE
Zonal regridding seg faults unless regridTool='regrid2'

### ISSUE THREAD

**Issue by katemarvel** [UV-CDAT/uvcdat#118]
I have zonally averaged data I need to re-grid to a common grid g.
> print data.getAxisList()

[   id: lat
   Designated a latitude axis.
   units:  degrees_north
   Length: 145
   First:  -90.0
   Last:   90.0
   Other axis attributes:
      long_name: latitude
      standard_name: latitude
      axis: Y
   Python id:  0x35911d0
,
    id: axis_2
   Designated a longitude axis.
   units:  degrees_east
   Length: 1
   First:  180.0
   Last:   180.0
   Other axis attributes:
      axis: X
      modulo: 360.0
      topology: circular
   Python id:  0x3587e90
]
The following code leads to a seg fault:

>gl = cdms.createZonalGrid(g)
>regridded = data.regrid(gl)  

But this code works fine:
>gl = cdms.createZonalGrid(g)
>regridded = data.regrid(gl,regridTool='regrid2')

Finally, trying
>gl = cdms.createZonalGrid(g)
> regridded = data.regrid(gl,regridTool='esmf')

gives the following error:
NameError: ESMC_FieldRegridStore() failed with rc = 6.  Please check the log files (named "PET*.ESMF_LogFile").

**Comment by doutriaux1** [comment]
#1060 fixes this
