### ISSUE TITLE
Box Fill edit error

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1191]
When I make a boxfill plot in any version 2.1 or 2.2 then try to modify the intervals the screen goes blank.

Here is a video of the way I generated the error using the standard clt.nc file. Has anybody else ever done this? 

https://www.dropbox.com/s/8svme0kcbd3sd03/box_fill_edit_error.mov?dl=0

**Comment by chaosphere2112** [comment]
This is the same issue as #1198; I'm working on the fix right now.
