### ISSUE TITLE
Update scipy to 0.16

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1193]
As noted in #966 the then scipy repo master was obtained to resolve the build issue. Scipy 0.16 is very close to being released (https://github.com/scipy/scipy/milestones - was due 30th March 2015) so it would be good to get back to a specific scipy version when it's available

**Comment by aashish24** [comment]
:100:

**Comment by durack1** [comment]
@doutriaux1 can you assign build, enhancement labels and milestone 2.3 please?

**Comment by aashish24** [comment]
why don't we add @durack1 to developer group?

**Comment by doutriaux1** [comment]
@aashish24 already did earlier this afternoon :wink: he definitely earned his stripes.

**Comment by durack1** [comment]
The first beta just landed.. Will watch this and await the final release..

https://github.com/scipy/scipy/releases/tag/v0.16.0b1
