### ISSUE TITLE
time slider should be disabled when running animation

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1195]
or at least pause animation if we move it

**Comment by chaosphere2112** [comment]
@doutriaux1  How about I make the time slider stop the animation? That's a pretty easy fix and I think would work slightly more comfortably than having the animation resume as soon as you stop sliding.

**Comment by doutriaux1** [comment]
works for me even though the slider animation needs to be turned off, but @chaosphere2112 is going to do this in a separate PR.

**Comment by chaosphere2112** [comment]
Submitted #1206 to address that issue.
