### ISSUE TITLE
Ext1 and Ext2 are rendering incorrectly

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1204]
Looks like the baselines for ext_1 and ext_2 are incorrect...

![](https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/fff99d3026a38baf23de03f8c14a5b27298f7bd1/baselines/vcs/test_boxfill_lev1_lev2_ext1.png)

![](https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/fff99d3026a38baf23de03f8c14a5b27298f7bd1/baselines/vcs/test_boxfill_lev1_lev2_ext1_ext2.png)

![](https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/fff99d3026a38baf23de03f8c14a5b27298f7bd1/baselines/vcs/test_boxfill_lev1_lev2_ext2.png)

**Comment by chaosphere2112** [comment]
Also, we need baselines to cover the other GMs using ext_1 and ext_2; they render differently on each of those.

**Comment by doutriaux1** [comment]
@chaosphere2112 what is incorrect about them?

**Comment by doutriaux1** [comment]
ok i see it now, will fix this
