### ISSUE TITLE
Document for manual testing of GUI

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1215]
This issue is to create documentation for manual testing of UVCDAT gui before release.
Reference: #1214

**Comment by vvpalav** [comment]
@aashish24 @doutriaux1 I am about to finish this document. I have tested all the plots present in UVCDAT. I need your help to write description of each plot present in our application. Just a line or two about what these plots and subcategories does. Like what is Isofill and what is a_robinson_isofill under isofill. My intention is that, this document could work as a guide for new users of UVCDAT in some way.
Please let me know about this.

**Comment by vvpalav** [comment]
Hello,

This is the initial draft of the document user or developer can use for testing UVCDAT GUI. 
I wanted to add more details, but will need help from everyone to make it more better. 
TODO represents things I am not sure of, so someone needs to fill in details there.
As I commented earlier, It is nice if we can put couple of lines of information about each plot and its subcategory. Please let me know if any suggestions.
Link: https://drive.google.com/file/d/0B2ACuiq8tB3RMnZDbS1QaDREUFE/view?usp=sharing

**Comment by doutriaux1** [comment]
thanks @vvpalav that is very nice! Is there any way we could make this more edit friendly, like put it on some wiki or something?

**Comment by doutriaux1** [comment]
What I don't like about this is that it unnecessarily increases the size of the repo and it is harder to see what changed between version. But I will do like this for now.

**Comment by vvpalav** [comment]
Thats an interesting point. Well lets make the changes offline for now and publish 1.0 version. meanwhile I will try to find out if we can upload it somewhere online so that we can track changes and everyone can edit the same document. 

@williams13 @potter2 @aashish24 @remram44 .. will you please take a look at the document and suggest anything that needs to be add/modify/remove from the doc.

There are couple of sections in the doc where I was not sure how those works, like visualization properties, diagnostics, animation, climate data tools etc. we need to complete this sections.

My main intention with this document is to make it a one stop solution for brief testing and a guide for the UVCDAT GUI for new comers or existing developers and users.

**Comment by vvpalav** [comment]
I have also posted a document containing all the issues/suggestions I come across while testing GUI.
Issue for reference: #1214 
Link: https://drive.google.com/file/d/0B2ACuiq8tB3Rem9zVWJRenhwMGc/view?usp=sharing

we need to confirm if this issues are valid and then we can start fixing them for 2.3

**Comment by doutriaux1** [comment]
@vvpalav as far as explaining each a_isofill etc... I think it is worth mentioning that any customized graphic method that the user saves to it's initial.attribute will show up here, so this window can potentially look different for every users (especially ones that have been using UV-CDAT for a while).
We can explain generally what each of these "pre-defined" method do, but the user should understand that these are merely "customized" plots with various values pre-set for them.

**Comment by vvpalav** [comment]
@doutriaux1 I am going to create Wiki Page named "Manual Testing of UVCDAT using GUI" and put the content of the document inside it. As I said earlier, I think there are still some parts where we need inputs from other users. I'll let you know once page is ready.

**Comment by remram44** [comment]
@hgohil2805 is checking whether automatically testing this scenario using a tool like [Sikuli](http://www.sikuli.org/) -- the idea would be to update both the scenario on this wiki page and the Sikuli script as new features are added

**Comment by vvpalav** [comment]
Just created a wiki page [Manual Testing of UVCDAT using GUI](https://github.com/UV-CDAT/uvcdat/wiki/Manual-Testing-of-UVCDAT-using-GUI). Link is also present on [UVCDAT wiki](https://github.com/UV-CDAT/uvcdat/wiki) under **Documentation and Tutorials** as **Manual Testing of UVCDAT using GUI**. Please review this and let me know.

**Comment by williams13** [comment]
This is awesome! Thanks for putting this together!
