### ISSUE TITLE
uvcdat gui can not drag and drop templates

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1223]
Now that we can modify templates within gui we need to be able to drag and drop them as well (like graphic methods)

**Comment by doutriaux1** [comment]
@remram44 feel free to reassign.

**Comment by aashish24** [comment]
@doutriaux1 what do we do with this bug?

**Comment by aashish24** [comment]
@chaosphere2112 I assigned it to you for now. Feel free to modify as needed.

**Comment by chaosphere2112** [comment]
@aashish24 I've got this in the new GUI already. I don't think I'm going to bother getting it into Vistrails.

**Comment by aashish24** [comment]
@chaosphere2112 sounds good to me. I am closing this then.
