### ISSUE TITLE
Add message at the end of setup_runtime script

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1224]
Some users reported being unsure if the script ran or did anything since nothing goes to the screen when sourcing it.

**Comment by ThomasMaxwell** [comment]
Getting the following error when starting up a newly build version of UVCDAT ( master branch ) this morning:


Location: /usr/local/uvcdat-test/build/install
['Adelon', 'Arabic', 'AvantGarde', 'Chinese', 'Clarendon', 'Courier',
'Greek', 'Hebrew', 'Helvetica', 'Maths1', 'Maths2', 'Maths3', 'Maths4',
'Russian', 'Times', 'default']
Uncaught exception on initialization: KeyError: 'path'
Traceback (most recent call last):
  File "/usr/local/uvcdat-test/vistrails/vistrails/uvcdat.py", line 89,
in <module>
    v = gui.application.start_application()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 160, in init
    self.createWindows()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 554, in createWindows
    self.uvcdatWindow = UVCDATMainWindow()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 74, in __init__
    self.createDockWindows()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 166, in createDockWindows
    self.diagnosticsWidget = DiagnosticsDockWidget(self)
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py",
line 56, in __init__
    self.opts._opts['path'].append(str(self.DS1PathLabel.text()))
KeyError: 'path'
Uncaught exception on initialization: KeyError: 'path'
Traceback (most recent call last):
  File "/usr/local/uvcdat-test/vistrails/vistrails/uvcdat.py", line 89,
in <module>
    v = gui.application.start_application()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 160, in init
    self.createWindows()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 554, in createWindows
    self.uvcdatWindow = UVCDATMainWindow()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 74, in __init__
    self.createDockWindows()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 166, in createDockWindows
    self.diagnosticsWidget = DiagnosticsDockWidget(self)
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py",
line 56, in __init__
    self.opts._opts['path'].append(str(self.DS1PathLabel.text()))
KeyError: 'path'
