### ISSUE TITLE
isoline labels text color broken

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1230]
text colors seem to be messed up if you look at the test baselines: https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/master/baselines/vcs/test_isoline_labels.png or https://github.com/UV-CDAT/uvcdat-testdata/blob/master/baselines/vcs/test_vcs_isoline_labels_multi_label_input_types.png

If you look at the pngs carefully you will realize that the text colors change for isolines of same values (look at 50 or 80 for example in the second png) this is wrong, all isolines of the same value should have the same color.

Also I think the code will need more tweaks beacuse right now we are using the same "lut" for both isolines and textcolors but it is conceivable that the user ask for different colors (isolines in shades of blue, but text in shades of red for readibilty)

**Comment by dlonie** [comment]
I have local fix, just need to update the unit tests on the VTK side of things. Will push soon.

**Comment by dlonie** [comment]
VTK merge request in at https://gitlab.kitware.com/vtk/vtk/merge_requests/144. I'll cherry-pick this onto our VTK head in a moment.

**Comment by dlonie** [comment]
Should be fixed by #1203.

See also UV-CDAT/uvcdat-testdata#36 and UV-CDAT/VTK#3
