### ISSUE TITLE
Style guide?

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1272]
@aashish24 @doutriaux1 
I'm a little confused by a git config that I apparently now have on my home computer, but not my work one.

Are we supposed to be using tabs instead of spaces? In https://github.com/UV-CDAT/uvcdat/blob/master/scripts/git_setup/.gitattributes it looks like whitespace=indent-with-non-tab is in use, and my global .gitconfig has whitespace=indent-with-non-tab (but only on my home computer, which I just setup for development yesterday). We have quite a lot of code indented with spaces (which is pretty much the standard for Python). Should I just switch this off on my computer?

**Comment by jbeezley** [comment]
I think `indent-with-non-tabs` means replace tabs with spaces.  Anyway, I don't think any of those rules  apply to any files that exist in this repository.  (i.e. `config*` doesn't match anything)

**Comment by chaosphere2112** [comment]
@jbeezley 
From https://www.kernel.org/pub/software/scm/git/docs/git-config.html:
> `indent-with-non-tab` treats a line that is indented with space characters instead of the equivalent tabs as an error (not enabled by default).

I'm just curious because it's in my global config, and I'm pretty sure it wasn't before (though, hard to check now). I'm more than happy to remove it and carry on, just wanted to make sure I wasn't doing anything dumb.

**Comment by jbeezley** [comment]
I guess you're right.  I still don't think it matters though because it only results in a warning message when using `git diff` or `git apply`.  It does seems like a bad setting for a python programmer. :stuck_out_tongue_winking_eye:

**Comment by chaosphere2112** [comment]
It actually won't let me commit as-is (hence the discussion :wink:)

**Comment by jbeezley** [comment]
Ahhh, okay.  I would remove it from your global config.  Or if you really want to keep it change the setting in the local `.git/config`.

**Comment by chaosphere2112** [comment]
Cool, I'll go ahead and nuke it out of my global config. No idea why it's there, just wanted to make sure I wasn't breaking anything :+1:

**Comment by aashish24** [comment]
Can you run SetForDevelopement.sh script on these machines to confirm whether or not its adding it ?

**Comment by aashish24** [comment]
https://github.com/UV-CDAT/uvcdat/blob/master/scripts/setup_for_development.sh

**Comment by chaosphere2112** [comment]
@aashish24 Looks like it was just something that was already on my computer. Removed it, everything is fine.

**Comment by aashish24** [comment]
sounds good. thanks for this info. 

- aashish

**Comment by jbeezley** [comment]
If `SetForDevelopement.sh` modifies the global git config, we should kill it with fire.

**Comment by chaosphere2112** [comment]
Looks like it doesn’t, I must have had something weird in my config at home.

**Comment by aashish24** [comment]
thanks for the info @chaosphere2112
