### ISSUE TITLE
Unresolved references in VCS code

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1274]
I don't know what you guys code in, but opening VCS in PyCharm shows a lot of unresolved references in VCS code; one of them is causing the taylor diagram error identified by @vvpalav. You should really make a pass on the code with a real IDE and fix the missing imports and misspelled variable names.

These are relatively easy to catch, and will cause crashes 100% of the time their branch is reached.

**Comment by doutriaux1** [comment]
Hard core my friend! There's only ONE real IDE and it is vi. :wink: 
With that said @durack1 is routinely uvcdat with Spyder which is arguably THE standard IDE for Python. And @mcenerney1 is using Eclipse... So it sounds more like a problem with Pycharm not sourcing setup runtime or just a user error.

**Comment by doutriaux1** [comment]
http://codegeekz.com/best-python-ide-for-developers/ :wink: checkout number 1

**Comment by remram44** [comment]
Oh no, [these](https://github.com/UV-CDAT/uvcdat/blob/df355f9d70b32e20027603d0dc6c0650abae7d93/Packages/vcs/Lib/Canvas.py#L739) [are](https://github.com/UV-CDAT/uvcdat/blob/df355f9d70b32e20027603d0dc6c0650abae7d93/Packages/vcs/Lib/Canvas.py#L889) [actual](https://github.com/UV-CDAT/uvcdat/blob/df355f9d70b32e20027603d0dc6c0650abae7d93/Packages/vcs/Lib/Canvas.py#L902) [errors](https://github.com/UV-CDAT/uvcdat/blob/df355f9d70b32e20027603d0dc6c0650abae7d93/Packages/vcs/Lib/utils.py#L1443), not PyCharm glitches. Sorry for the confusion.

```
  File "/home/remram/Documents/programming/uvcdat-vistrails/vistrails/packages/uvcdat_cdms/widgets.py", line 135, in getValueFromFunction
    value = get_canvas().match_color(f.params[0].strValue)
  File "/home/remram/uvcdat-builds/builds/32f3893f053107374d2b4b8fb0feee5efbcaedee/install/lib/python2.7/site-packages/vcs/Canvas.py", line 2377, in match_color
    return vcs.match_color(color,colormap)
  File "/home/remram/uvcdat-builds/builds/32f3893f053107374d2b4b8fb0feee5efbcaedee/install/lib/python2.7/site-packages/vcs/utils.py", line 1443, in match_color
    vals=genutil.colors.str2rgb(color)
NameError: global name 'genutil' is not defined
```

I like my yank registers and instant macros as much as the next guy, but I just wouldn't code anything important in an environment that doesn't report forgotten imports or wrong number of passed arguments.

**Comment by durack1** [comment]
@doutriaux1 I think @remram44 is pointing out that some more "feature complete" IDEs (such as Spyder with [rope](https://github.com/python-rope/rope), [pyflakes](https://github.com/pyflakes/pyflakes/) and [pylint](http://www.pylint.org/)) will highlight issues in the code that VI and other less featured IDEs will not..

In particular these things optional packages are great in the spyder IDE to point out miss-spelled variable names, missing or unused module imports etc etc.. They also can assist in indentation errors, which can cause nasty bugs like #1048

**Comment by doutriaux1** [comment]
@durack1 I know what @remram44 meant. I was just pointing out we DO use other IDEs and they seem to work.

**Comment by doutriaux1** [comment]
anyhow thanks for catching these for us working on unimportant projects I will approve the PR when it comes in.

**Comment by remram44** [comment]
You can't seriously ask me to fix all the missing imports and mistyped variable names in your code. If you can't use an IDE that reports these as you type them, I would be trying to hit a moving target anyway...

The missing imports in vcs.utils is one of the crashes listed in vvpalav's document, fix it or don't, I think working code is best but that's only my opinion.

**Comment by doutriaux1** [comment]
@remram44 you fix whatever you want my friend nobody is forcing you to do anything. You spotted a bug, took the time to report it and spot. I was just assuming you'd be issuing a PR for it. No worries I will fix it.

**Comment by doutriaux1** [comment]
oh relabeling this to "vcs" since it appears to be in the vcs code not cdms2.
@remram44 correct labeling saves time for developers.

**Comment by remram44** [comment]
Oops!
