### ISSUE TITLE
Clearing cell doesn't remove toolbar

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1275]
The previous cell's toolbar is still displayed until the next click. This is problematic, since depending on the cell type, some of the buttons on the toolbar might lead to crashes.

Also affects VisTrails: [#1072](https://github.com/VisTrails/VisTrails/issues/1072)

From @vvpalav

**Comment by vvpalav** [comment]
More Info to recreate:

1) Plot into any cell, additional button like colormap etc will appear on toolbar.
2) now just clear the cell, those buttons are still present on toolbar while cell is emptied.
3) click on any button (ex: colormap) exception is thrown and entire gui becomes unresponsive.

Exception:

Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat/15-03-30/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1880, in triggeredSlot
    canvas = cellWidget.canvas
AttributeError: 'QPromptCellWidget' object has no attribute 'canvas'


Image View:

![screen shot 2015-05-05 at 8 24 22 pm](https://cloud.githubusercontent.com/assets/6840965/7485575/08a5f80a-f366-11e4-8b95-7be655996f36.png)

**Comment by remram44** [comment]
The fix (VisTrails/VisTrails#1073) has been merged into VisTrails, but it doesn't seem to do for UV-CDAT because of QCDATWidget's toolbar relying on inputPorts, which only gets set once the widget has been updated... QCDATWidget looks insane, I don't know if we want to fix that.
