### ISSUE TITLE
Cosmetic Bug: dots in Scatter plot are hardly visible. 

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1281]
Plot Scatter with u and v. Dots are hardly visible on smaller screen.

![screen shot 2015-05-05 at 9 01 47 pm](https://cloud.githubusercontent.com/assets/6840965/7485867/2580915c-f36a-11e4-9a09-bc3edb6f1695.png)

Maybe we should change the color of the dots or the size.
I am not sure of labels, please remove if its unrelated.

**Comment by doutriaux1** [comment]
you're rgiht we should probably increase the default size.
