### ISSUE TITLE
Boxfill pixels are too scattered

### ISSUE THREAD

**Issue by vvpalav** [UV-CDAT/uvcdat#1282]
Pixels are too scattered for clt and boxfill

![screen shot 2015-05-05 at 11 01 20 pm](https://cloud.githubusercontent.com/assets/6840965/7486883/adaeebea-f37a-11e4-95df-8f319d76f6de.png)

I am not sure if this an issue. Please let me know if this is fine or we need to fix this issue.

**Comment by remram44** [comment]
Sorry, what is the problem here?

**Comment by vvpalav** [comment]
plot pixels are not smooth, nothing wrong with the plot except its pixels are too scattered. I am not sure what is the reason behind this, so need confirmation if this is an issue or not.

**Comment by aashish24** [comment]
@vvpalav thats because the data is pretty low res.

**Comment by vvpalav** [comment]
Alright Thanks

**Comment by aashish24** [comment]
Try high res dataset and you should not see pixelated image

**Comment by doutriaux1** [comment]
@vvpalav yes it's low resolution data that's why. That is actually the whole idea behind boxfill/meshfill, see the data as it actually is represented by the model. isolines can give a false feeling.
