### ISSUE TITLE
dv3d list broken

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1285]
```
In [1]: dsc=x.create3d_scalar()

In [2]: dsc.list()
 ---------- DV3D (Gfdv3d) member (attribute) listings ---------
name = __3d_scalar_642267851670046
axes = xyz
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b9c9df306f2c> in <module>()
----> 1 dsc.list()

/lgm/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/dv3d.pyc in list(self)
    185         print 'axes =',self.axes
    186         for pname in self.parameter_names:
--> 187             print ' = '.join( [ pname, self.getParameter( pname ) ] )
    188 
    189 class Gf3Dvector(Gfdv3d):

TypeError: sequence item 1: expected string, NoneType found

```

**Comment by doutriaux1** [comment]
try:
```
        for pname in self.parameter_names:
            pval = self.getParameter( pname )
            print pname,'=',repr(pval)
```

**Comment by doutriaux1** [comment]
@ThomasMaxwell lots of default are initialized as None, you might to initialize with actual values?
```
ToggleVolumePlot = None
BasemapOpacity = None
Camera = '{}'
PointSize = None
Configure = None
ScaleColormap = None
ChooseColormap = None
ToggleSurfacePlot = None
SliceThickness = None
ScaleOpacity = None
Colorbar = None
ToggleClipping = None
Animation = None
ZSlider = None
IsosurfaceValue = None
YSlider = None
ScaleTransferFunction = None
VerticalScaling = None
XSlider = None
ToggleSphericalProj = None
```

**Comment by doutriaux1** [comment]
also should the default for axes really be "xyz" ? Could we set it to (-3 -2 -1) or None which would mean that ? So that sending ANY 3D array would work (just no basemap)

**Comment by ThomasMaxwell** [comment]
These are given default values elsewhere, e.g. ‘interactionButtons.addSliderButton’.

**Comment by ThomasMaxwell** [comment]
Dv3d has never been designed to handle raw 3D arrays.   It expects datasets that are at least close to COARDS or CF compliant.

**Comment by ThomasMaxwell** [comment]
Fixed in branch vcs3D_fix_dv3d_list.

**Comment by ThomasMaxwell** [comment]
Can whoever is in charge of the diagnostics gui please catch the following UVCDAT gui startup error?:


Location: /usr/local/uvcdat-test/build/install
['Adelon', 'Arabic', 'AvantGarde', 'Chinese', 'Clarendon', 'Courier',
'Greek', 'Hebrew', 'Helvetica', 'Maths1', 'Maths2', 'Maths3', 'Maths4',
'Russian', 'Times', 'default']
Uncaught exception on initialization: KeyError: 'path'
Traceback (most recent call last):
  File "/usr/local/uvcdat-test/vistrails/vistrails/uvcdat.py", line 89,
in <module>
    v = gui.application.start_application()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 160, in init
    self.createWindows()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 554, in createWindows
    self.uvcdatWindow = UVCDATMainWindow()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 74, in __init__
    self.createDockWindows()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 166, in createDockWindows
    self.diagnosticsWidget = DiagnosticsDockWidget(self)
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py",
line 56, in __init__
    self.opts._opts['path'].append(str(self.DS1PathLabel.text()))
KeyError: 'path'
Uncaught exception on initialization: KeyError: 'path'
Traceback (most recent call last):
  File "/usr/local/uvcdat-test/vistrails/vistrails/uvcdat.py", line 89,
in <module>
    v = gui.application.start_application()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 703, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 160, in init
    self.createWindows()
  File "/usr/local/uvcdat-test/vistrails/vistrails/gui/application.py",
line 554, in createWindows
    self.uvcdatWindow = UVCDATMainWindow()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 74, in __init__
    self.createDockWindows()
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/mainwindow.py",
line 166, in createDockWindows
    self.diagnosticsWidget = DiagnosticsDockWidget(self)
  File
"/usr/local/uvcdat-test/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py",
line 56, in __init__
    self.opts._opts['path'].append(str(self.DS1PathLabel.text()))
KeyError: 'path'

**Comment by ThomasMaxwell** [comment]
One way to support the input of raw 3D arrays into vcs3D would be to provide some scripts to easily wrap the arrays as cdms TransientVariables, which vcs3D can ingest.

From: <Maxwell>, "Maxwell, Thomas P. (GSFC-606.2)[SCIENCE APPLICATIONS INTL CORP]" <thomas.maxwell@nasa.gov<mailto:thomas.maxwell@nasa.gov>>
Date: Wednesday, May 6, 2015 at 12:06 PM
To: UV-CDAT/uvcdat <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [uvcdat] dv3d list broken (#1285)

Dv3d has never been designed to handle raw 3D arrays.   It expects datasets that are at least close to COARDS or CF compliant.

**Comment by doutriaux1** [comment]
so you mean if I pass a 3D MV2 with axis axis_0 axis_1 and axis_2 it is not supposed to work right?
I'll try it just for fun
