### ISSUE TITLE
Thumbdrive UV-CDAT install fails on MacOSX 10.10.3

### ISSUE THREAD

**Issue by czender** [UV-CDAT/uvcdat#1297]
The thumbdrive version of UV-CDAT distributed at the ACME PI meeting does not work on my MacBoook Pro. The CentOS VM did not complete booting. Aashish Chaudhary made valiant efforts to fix it, as he has the same type of laptop, but was unable to resolve the issue. Until this issue is resolved must I install UVCDAT from source in order to  use it on my laptop (because precompiled binaries for Yosemite are not available from uvcdat.llnl.gov)? Or are there some Yosemite versions available? Thanks!
cz

**Comment by doutriaux1** [comment]
@czender you are correct 2.1 on the site does not have Yosemite, but the binaries for 10.9 should work on it.
building from source should be smooth. if @aashish24 is still with you he can guide you though it.
2.2 will have yosemite binaries
