### ISSUE TITLE
Fix vcs3d failing test 

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1305]

**Comment by durack1** [comment]
@aashish24 if this is the same issue as https://open.cdash.org/testDetails.php?test=334149793&build=3808629 - it's DVD3D not VCS3D that's got the problem.

It looks to me like it's a case of continental bounds missing a single point, so the start not returning to the exact end point, closing the polygon.

**Comment by dlonie** [comment]
Agreed -- shouldn't the DV3D team be looking at this?

**Comment by ThomasMaxwell** [comment]
The code that generates the boundaries is in shapeFileReader.getPolyLines in Packages/DV3D/Shapefile.py.

— Tom

**Comment by chaosphere2112** [comment]
If I'm reading the file that @ThomasMaxwell pointed at correctly, the continents are defined in a GIS shapefile, which is then rendered using `vtkPolyData`. I'm guessing it's an OpenGL or VTK quirk, not an issue with DV3D; it works perfectly fine on my mac, so it must be something platform dependent.

**Comment by chaosphere2112** [comment]
@dlonie Looks like the shapefile is converted to VTK here:

https://github.com/UV-CDAT/uvcdat/blob/3f99c8e3ab0278e6f9b7c6083c3396c7edd61c54/Packages/DV3D/Shapefile.py#L1136-L1250

**Comment by aashish24** [comment]
@dlonie @ThomasMaxwell is busy with other tasks and we discussed that vcs3D (visualization related) changes will be taken care by you and me (obviously with @ThomasMaxwell's help).

**Comment by doutriaux1** [comment]
and @chaosphere2112 we also discussed that @aashish24 and @dlonie are very busy and wouldn't want you guys charging your precious time on things we an also fix :wink:

**Comment by aashish24** [comment]
@doutriaux1 we are never too busy for you :+1:

**Comment by doutriaux1** [comment]
Awwww... You're too nic :wink: Anyhow you do run out of money though :stuck_out_tongue_winking_eye:

**Comment by aashish24** [comment]
I think we all do -:)
