### ISSUE TITLE
gui python script extensions are written as string when they should be boolean

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1306]
b=x.createboxfill()
b.ext_1 # is stored in VisTraisl python script as 'False' were it should be False

I think VisTrails input prots need to be updated to reflect that they are boolean.

Note: b.ext_1 = "y" is valid, user can send "y",1,True

But it is stored internally as True

**Comment by durack1** [comment]
@doutriaux1 just added the "bug" label to hopefully reduce editing for the auto-gen release notes from @chaosphere2112

**Comment by remram44** [comment]
[The port is currently String](https://github.com/UV-CDAT/VisTrails/blob/e396737c50b692c6079da7de08b493001a674900/vistrails/packages/uvcdat_cdms/init.py#L1913), so if you changed it, you just have to reflect it there.

**Comment by vvpalav** [comment]
What about this one: [here](https://github.com/UV-CDAT/VisTrails/blob/2a04fba28222ac9ad3ad71a0798e755dda68e76c/vistrails/packages/cdat/cdat_cell.py#L236)

**Comment by vvpalav** [comment]
Changed ports in uvcdat_cdms/init.py .. pull request: https://github.com/UV-CDAT/VisTrails/pull/45

**Comment by doutriaux1** [comment]
still broken removed gatekeeper label
