### ISSUE TITLE
try different opendap url to bypass what seems to be firewall issues on opendap ctest

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1311]

**Comment by doutriaux1** [comment]
ok I found the error on my ubunutu. I did not have the curl.h on my system. I will add this to the list of pre-requistes. @aashish24 @jbeezley can you make sure it is installed on your systems please.
```
sudo apt-get install libcurl4-openssl-dev
```

**Comment by durack1** [comment]
@doutriaux1 just note that there do appear to be some ongoing issues with netcdf4 and opendap data access, particularly in the latest 4.3.3.1 netcdf-c release https://github.com/Unidata/netcdf-c/issues/115

**Comment by doutriaux1** [comment]
@durack1 yes but this is not related, once I added the header files everything works like a charm while the older version still fails. So it is definitely linked to the fact that netcdf needs curl headers while building.

**Comment by durack1** [comment]
@doutriaux1 yes, you're right.. My point above was that as we move from 4.3.2 to the latest netcdf-c release we'll have to pay a little more attention to this opendap issue.. It should most likely be created as a new issue (update netcdf to 4.3.3.1)

**Comment by aashish24** [comment]
@doutriaux1, yes, I will have it installed on my buildbot machine.

**Comment by jbeezley** [comment]
I installed it this morning.

**Comment by doutriaux1** [comment]
https://github.com/UV-CDAT/uvcdat/pull/1314
