### ISSUE TITLE
can't change isoline interval in overlay

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1315]
If I overlay isolines over an isofill plot and then try to change the contour interval of the isolines, I get an error:

Traceback (most recent call last):
  File "/Users/potter/uvcdat/build-uvcdat/install/vistrails/vistrails/gui/uvcdat/graphicsMethodsWidgets.py", line 503, in generateRanges
    if str(self.ext1ButtonGroup.buttonGroup.button(self.ext1ButtonGroup.buttonGroup.checkedId()).text()).lower()[0]=="y":
AttributeError: 'QIsolineEditor' object has no attribute 'ext1ButtonGroup'

**Comment by doutriaux1** [comment]
https://github.com/UV-CDAT/VisTrails/pull/46
