### ISSUE TITLE
sample data doesn't get re-downloaded if it's deleted

### ISSUE THREAD

**Issue by acbauer** [UV-CDAT/uvcdat#133]
If the sample_data directory in the install directory gets deleted, CDAT_DOWNLOAD_SAMPLE_DATA gets set to OFF, and then CDAT_DOWNLOAD_SAMPLE_DATA gets set back to ON, it won't re-downloaded the sample data. I haven't tested if the configure is initially done with CDAT_DOWNLOAD_SAMPLE_DATA set to OFF and then set to ON after UV-CDAT has been built but it may suffer the same issue.

**Comment by doutriaux1** [comment]
@aashish24 moving 2.3
