### ISSUE TITLE
pep8 unit test

### ISSUE THREAD

**Issue by dlonie** [UV-CDAT/uvcdat#1344]
Add a test that runs `pep8` against the `vcsvtk` module. Make it easy to extend to other modules as well.

**Comment by doutriaux1** [comment]
good idea! @dlonie can you also always add a milestone when you create an issue. It makes it easier to track via filters. Especially when we get close from a release. Thanks.

**Comment by dlonie** [comment]
Sure, no problem.

**Comment by dlonie** [comment]
@aashish24 Here's the pep8 test (#1351) -- it was merged already :+1:
