### ISSUE TITLE
CDMS3DPlot -> CDMSCell connections are invalid

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1346]
`CDMS3DPlot`'s 'self' output port has type `CDMS3DPlot`, but `CDMSCell`'s 'plot' input port has type `CDMSPlot`.

The connection is built programmatically by the pipeline helper, but it is invalid. A common base `CDMSBasePlot` should have been introduced (or `CDMSPlot` renamed to `CDMS2DPlot`?).

I don't know if we can change this without breaking previously saved workflows, UV-CDAT doesn't use the pipeline upgrades mechanism (and doesn't even version packages).

Everything would be fine if `CDMS3DPlot` was a subclass of `CDMSPlot` but it's not.

**Comment by doutriaux1** [comment]
@remram44 at this point I don't think there are many saved workflows. I think it's ok to break it early, before many people have saved workflows, and make it right.

**Comment by doutriaux1** [comment]
@remram44 for extreme/desperate cases do you think it would be possible for users to manually edit their workflow to make it work again?
