### ISSUE TITLE
`size` keyword argument has no effect in `vcs.init`

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1347]
I'm poking through cleaning up the docstrings in VCS, and I found the `size` keyword argument on `vcs.init`. It passes it through to Canvas.Canvas; shouldn't we use that instead of hardcoding in default sizes that look nice on @doutriaux1's monitor (:wink:)?

**Comment by chaosphere2112** [comment]
Ah, digging further into the code I see that it should take a string that specifies an existing size. Hm, that's nonintuitive.

**Comment by doutriaux1** [comment]
@chaosphere2112 I have a bug report on VTK repo ( @aashish24 @dlonie if you could push to have it fixed) that prevents me from getting the user's desktop size. That would be the right way to fix this "nice for @doutriaux1 screen issue).

**Comment by doutriaux1** [comment]
@aashish24 @dlonie the issue is/was: http://www.vtk.org/Bug/view.php?id=14882

It is apparently fixed and in master. Is it in "our" uvcdat-master ? Last I tried it didn't work.

**Comment by dlonie** [comment]
I'll run the tests against a more up-to-date VTK and bump if all goes well.

**Comment by dlonie** [comment]
There have been a few API changes in VTK master that are affecting VCS. I'll get these ironed out and push a branch when it's ready.

**Comment by doutriaux1** [comment]
thanks!

**Comment by dlonie** [comment]
UV-CDAT/uvcdat#1348 should do it. I need someone to manually test it (buildbot won't handle the VTK update) and regenerate the dv3d vector baseline, since that's a buggy test for me on arch linux.

**Comment by doutriaux1** [comment]
the `size` was supposed to be for A4 vs postscript etc... It's more an `page_aspect_ratio` than anything

**Comment by chaosphere2112** [comment]
Yeah, I figured that out after poking it enough. At some point (post-2.4) it would be nice to have an easier way to specify window size, since it's a bit wonky right now.
