### ISSUE TITLE
cdatgui repository

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1352]
There is a [UV-CDAT/cdatgui](https://github.com/UV-CDAT/cdatgui), apparently an outdated copy of [UV-CDAT/VisTrails](https://github.com/UV-CDAT/VisTrails) (with exactly two more commits: UV-CDAT/cdatgui#1). Delete it?

**Comment by doutriaux1** [comment]
yes. Thanks for reporting. Deleting right now.
