### ISSUE TITLE
Merge contents of images and resources subdirs

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1353]
@doutriaux1 @aashish24 would it be possible to merge the contents of the [images](https://github.com/UV-CDAT/uvcdat/tree/master/images) and [resources](https://github.com/UV-CDAT/uvcdat/tree/master/resources) subdirs - they seem to both contain *.icns, *.jpg or other image (or font) files which could be merged to simplify the directory structure..

Additionally, there are a bunch of font files etc in [images](https://github.com/UV-CDAT/uvcdat/tree/master/images) which I wonder if they're still required?

**Comment by durack1** [comment]
@doutriaux1 this will require your input - it seems things need a really good clean out as these all end up in the installed `bin` dir.. Not the best..

**Comment by durack1** [comment]
As noted in https://github.com/PCMDI/pcmdi_metrics/issues/161 here is a more specific listing of the installed files/dirs to cleanup, which relate to the source above

- Cleanup deprecated subdirs/files during install: **bin/{.gif, .ttf, .png, .scr, .xmb}**, **bin/images**, **bin/tutorials**, **include**, **man**, **share/man**

**Comment by durack1** [comment]
@doutriaux1 I have a feeling that the creation of the `resources` subdir by @aashish24 was in preparation for packaging as a `*.dmg` - as per the [Apple Docs for an OS X Application Bundle](https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19)

It may pay to consider their standard directory naming when things are being rearranged..

**Comment by durack1** [comment]
@aashish24 I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs.. Can you chime in here?

**Comment by durack1** [comment]
@aashish24 I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs.. Can you chime in here?

**Comment by durack1** [comment]
@aashish24 I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs.. Can you chime in here?

**Comment by durack1** [comment]
@aashish24 I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs.. Can you chime in here?

**Comment by durack1** [comment]
@aashish24 I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs.. Can you chime in here?

**Comment by durack1** [comment]
@doutriaux1 @aashish24 this is another that I've moved to `3.0` it's a parallel issue to #788 and #1341

**Comment by doutriaux1** [comment]
@durack1 I will provide a brand new PR

**Comment by durack1** [comment]
@doutriaux1 up to you whether you close this or leave it open as a `3.0`er.. I don't think it should be forgotten about..

**Comment by doutriaux1** [comment]
I'm sure it will not be forgotten, I have a feeling someone will be nagging us about this :stuck_out_tongue_winking_eye:
