### ISSUE TITLE
older git checkout error

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1355]
```
remote: Total 8042 (delta 5120), reused 5720 (delta 3157), pack-reused 0
Receiving objects: 100% (8042/8042), 79.33 MiB | 22.41 MiB/s, done.
Resolving deltas: 100% (5120/5120), done.
warning: Remote branch uvcdat-2.2.0 not found in upstream origin, using HEAD instead
error: pathspec 'origin/uvcdat-2.2.0' did not match any file(s) known to git.
make[2]: *** [vistrails-prefix/src/vistrails-stamp/vistrails-install] Error 1
make[1]: *** [CMakeFiles/vistrails.dir/all] Error 2
```
git used (RedHat 6)
```
git version 1.7.1
```

**Comment by aashish24** [comment]
@doutriaux1 what you are trying to do? You can use tag as branch name in git. It works on certain versions on on others it doesn.t

**Comment by doutriaux1** [comment]
@aashish24 I'm not trying to do anything. Checked out "release" ran cmake, got this.

**Comment by doutriaux1** [comment]
@aashish24 I'm not sure what's up with this system. I built w/o any problem on other RH6. I think we fixed this issue for other packages (uvcmetrics ?) before, we probably simply need to tweak this one to make sure it works on all systems as well.

**Comment by aashish24** [comment]
I know the problem. We need to push uvcdat-2.2.0 as branch as well.

**Comment by doutriaux1** [comment]
yes it would be nice, that's why I opened the issue so we don't forget about it

**Comment by doutriaux1** [comment]
@mcenerney1 branch fixed this i think, if someone runs into it again feel free to reopen.
