### ISSUE TITLE
Line width is inconsistent across platforms

### ISSUE THREAD

**Issue by dlonie** [UV-CDAT/uvcdat#1359]
The VTK ui tests are producing different results on our mac and linux clients:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=3842533

I'll dig into this a bit.

**Comment by doutriaux1** [comment]
@chaosphere2112 looks like you need to turn off antialiasing in your tests.

**Comment by doutriaux1** [comment]
@dlonie do you know how to do this? Mind adding it to @chaosphere2112 tests? He's on leave for another couple of weeks.

**Comment by dlonie** [comment]
I'll take a look. I thought antialiasing was off by default for vcs canvases?

**Comment by doutriaux1** [comment]
i thought so too, but from the cdast it's not

**Comment by dlonie** [comment]
Ahh, I see now, the vtk_ui_test framework creates it's own vtkRenderWindow and does it a little differently than the vcs. *phew* that'll be a quick fix at least!
