### ISSUE TITLE
uvcdat-devel repository

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1366]
[UV-CDAT/uvcdat-devel](https://github.com/UV-CDAT/uvcdat-devel) looks unused. However it has branches that are not in UV-CDAT/uvcdat.

Hopefully these have been rebased and merged by now, but there's no easy way to check.

* [ ] vcsDV3D-features_for_scripted_execution
* [ ] 655-fix-curses
* [ ] issue_689_cdms_load_and_plot_axis_variable_baseline
* [ ] bad-master
* [ ] 685-cdash-upload
* [ ] vcsDV3D-separate_plot_constituent_config
* [ ] issue_691_interact_mac
* [ ] vcsDV3D-fix_button_issues
* [ ] issue_663_fix_pcmdi11_dashboard
* [ ] fix_cdms_load_and_plot_baseline
* [ ] uvcatDV3D-fix_buttonbar_issues
* [ ] issue_637_inverted_axis
* [ ] fix_test_failure_text_related
* [ ] dashboard-updates
* [ ] issue_550_vector_mask
* [ ] vcsDV3D-update_interaction-without-logo
* [ ] vcsDV3D-update_interaction
* [ ] vcsDV3D-add-gui_widget
* [ ] fix-animation-background
* [ ] animate-cmd-line-adds
* [ ] vcsDV3D-more-for-2.0
* [ ] vcsDV3D-add_testing_rebased
* [ ] vcsDV3D-add_testing
* [ ] vcsDV3D-provenance
* [ ] devel/vcsDV3D-provenance
* [ ] vcsDV3D_update_scripting_rebased
* [ ] vcsDV3D-fix_unstructured_grid_issues
* [ ] osmesa
* [ ] vcsDV3D-fix_unstructured_grid_issues_updated1
* [ ] vcsDV3D_update_scripting
* [ ] vcsDV3D-expose-animation
* [ ] vcs_jeff_none_no_getsize
* [ ] vcsDV3D-USG_performance_issues
* [ ] vcsDV3D-vistrails_integration
* [ ] fix_travis_macos
* [ ] devel-master
* [ ] vcsDV3D-api-devel
* [ ] vcsDV3D-gui-integration
* [ ] uvcdat-dv3d-add-vector-plots
* [ ] vcs-dv3d-devel
* [ ] uvcdat-lite-system
* [ ] rhea_fixes
* [ ] system-python
* [ ] bug425_dotdir_Set_only_once
* [ ] fix_master_vesion
* [ ] python_libxml2_deps
* [ ] ocgis
* [ ] improve_git_protocol_config
* [ ] uvcdat_bug#95_support_mpi_flavors

**Comment by doutriaux1** [comment]
Thanks @remram44 except for "maybe" the last one (mpi_flavors) I think the rest has either made it to master or has been abandoned. I will take a look at mpi one.

**Comment by doutriaux1** [comment]
I'll look at "rhea_fixes" as well.

**Comment by ThomasMaxwell** [comment]
The dv3d branches should all be merged.

**Comment by aashish24** [comment]
uvcdat-devel should be deleted. @doutriaux1 okay to delete?

**Comment by doutriaux1** [comment]
yes but let me look at these two branches first ok?

**Comment by aashish24** [comment]
I won't delete those two branches, i will just delete the uvcdat-devel if I can wait on that as well if thats what you want :smile:
