### ISSUE TITLE
buildbot should restart if master is changed

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1372]
If master gets changes (a PR is accepted). All other pending PR should be automatically restarted by buildbot to make sure they are still compatible.

**Comment by doutriaux1** [comment]
@jbeezley feel free to re-assign if you're not in charge of the buildbot anymore.

**Comment by aashish24** [comment]
@doutriaux1 let's rethink about this some more. The amount of time and the delay between may not make this as a ideal choice. May be you, me can discuss further on this and then suggest some changes to @jbeezley ?

**Comment by jbeezley** [comment]
We don't currently do any integration testing with master.  In fact, buildbot doesn't currently know anything about pull requests at all.  Any push to the repository generates a build of the hash that was pushed.  I agree this is something that integration testing should do once we implement it, but doing so will take a couple of days work.  As Aashish mentioned, there is also the issue of limited compute resources, which is only going to get worse as we include more tests.

**Comment by doutriaux1** [comment]
ah... well that's not what @aashish24 desbribes at: https://github.com/UV-CDAT/uvcdat/blob/developers_documentation/CONTRIBUTE.md

**Comment by doutriaux1** [comment]
@aashish24 let's talk about it today or tomorrow.
