### ISSUE TITLE
Error when clicking on a_boxfill to get point values.

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1374]
After plotting a variable in UVCDAT with a_boxfill, I then click within the plot to see the parameter value and coordinates.   When I do that I get the error below.   I am using UVCDAT v2.2.0 on Rhea.

Traceback (most recent call last):
  File "/lustre/atlas/world-shared/csc121/uvcdat/2015-05-06/lib/python2.7/site-packages/vcs/VTKPlots.py", line 127, in leftButtonPressEvent
    if numpy.allclose(gm.datawc_y1,1.e20):
  File "/lustre/atlas/world-shared/csc121/uvcdat/2015-05-06/lib/python2.7/site-packages/numpy/core/numeric.py", line 2219, in allclose
    xinf = isinf(x)
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by doutriaux1** [comment]
@cameronsmith1 I will double check, can you please point me to your dataset in case I can't reproduce with sample data?

**Comment by doutriaux1** [comment]
@cameronsmith1 can you please point me to the file please so I can see if it is still true

**Comment by cameronsmith1** [comment]
I can't remember what data I used.   However, I just tried it on some typical data, and it worked correctly.
I did this test on Rhea with Version: 2.2.0-283-g21e26d0
