### ISSUE TITLE
Configuring travis/buildbot testing to be more robust

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1384]
@jbeezley @doutriaux1 @aashish24 this creates a dedicated issue to attempt to resolve a bunch of errors that continue to recur in the travis and buildbot build tests as discussed in #1381 and a number of other issues/PRs.
Specific changes to implement:
- [x] Add redhat `6.6` platform (`6.6 - crunchy.llnl.gov - ALL`) to the buildbot suite
- [x] Add redhat `6.7` platform (`6.7 - oceanonly.llnl.gov - NOGUI`) to the buildbot suite
- [x] Add mac `10.10` platform (`10.10 - macbot.llnl.gov - LEAN`) to the buildbot suite
- [ ] Add mac `10.11` platform (`10.11 - ALL`) to the buildbot suite
- [ ] Add redhat `7.x` platform (`7.1 - pcmdi10.llnl.gov - ALL` available) to the buildbot suite (#457)
- [ ] Use `travis_wait` before the `cmake` call to prevent failures due to long waits between build steps (see [here](https://travis-ci.org/UV-CDAT/uvcdat/builds/66444379) and [here](https://travis-ci.org/UV-CDAT/uvcdat/builds/64653952)) - Is there a switch for cmake which will allow retrying dropped source download attempts too?
- [x] Deal with timeouts during `cdms` tests to opendap servers (see [here](https://open.cdash.org/testDetails.php?test=344170858&build=3855046), [here](https://open.cdash.org/testDetails.php?test=342344087&build=3844793) and [here](https://open.cdash.org/testDetails.php?test=342348597&build=3844806))
- [x] Deal with race conditions in `vtk` image checks (see [here](https://open.cdash.org/testDetails.php?test=345112405&build=3859769), [here](https://open.cdash.org/testDetails.php?test=345112405&build=3859747), [here](https://open.cdash.org/testDetails.php?test=345008217&build=3859113) and [here](https://open.cdash.org/testDetails.php?test=344953662&build=3858836) - these errors show where the right-side image pixels are randomized on the canvas [also here](https://open.cdash.org/testDetails.php?test=345358793&build=3861277), an attempt to add a `time.sleep(1)` to prevent a race condition in another test was used in #1341 [here](https://github.com/UV-CDAT/uvcdat/blob/issue788_durack1_removeDeprecatedFoldersAndFiles/testing/vcs/vtk_ui/test_vtk_ui_manager_resize.py#L20)) - fixed by #1393 

This might also be useful:
http://docs.travis-ci.com/user/build-timeouts/

**Comment by chaosphere2112** [comment]
@jbeezley It looks like all of the failures are on the same buildbot; the test-laptop one. Is that a particularly slow device?

**Comment by chaosphere2112** [comment]
Also, just submitted #1393 to help with some race conditions in my tests.

**Comment by durack1** [comment]
@potter2, @doutriaux1 and I were wondering if you may have any under-utilized mac hardware that would be suitable as a `mac-buildbot` candidate? We currently don't have any mac hardware available to run build tests, and a `10.9`, `10.10` and possibly even a `10.11` machine would certainly be helpful if available..

**Comment by durack1** [comment]
@potter2, @doutriaux1 and I were wondering if you may have any under-utilized mac hardware that would be suitable as a `mac-buildbot` candidate? We currently don't have any mac hardware available to run build tests, and a `10.9`, `10.10` and possibly even a `10.11` machine would certainly be helpful if available..

**Comment by potter2** [comment]
I really don't have anything. Sorry

Jerry

Sent from my iPad

On Jun 22, 2015, at 11:25 AM, Paul J. Durack <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2>, @doutriaux1<https://github.com/doutriaux1> and I were wondering if you may have any under-utilized mac hardware that would be suitable as a mac-buildbot candidate? We currently don't have any mac hardware available to run build tests, and a 10.9, 10.10 and possibly even a 10.11 machine would certainly be helpful if available..

**Comment by durack1** [comment]
@potter2 this is what @doutriaux1 and I spoke to you about last week, getting another mac to run build tests.. @doutriaux1 already has a server configured, but we need more clients and you indicated you have a mac machine at home that could be used within the buildbot test suite..?

**Comment by potter2** [comment]
Paul,
I am at GSFC/NASA this week but I will be home next week. Maybe we can get it set up then. Will the build work on a home network?

Jerry


Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

On Sep 1, 2015, at 11:49 AM, Paul J. Durack <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> this is what @doutriaux1<https://github.com/doutriaux1> and I spoke to you about last week, getting another mac to run build tests.. @doutriaux1<https://github.com/doutriaux1> already has a server configured, but we need more clients and you indicated you have a mac machine at home that could be used within the buildbot test suite..?

**Comment by durack1** [comment]
Great @potter2 yeah the build will work, as long as it is permanently connected.. @doutriaux1 can explain specifics, but simply when a pull request is issued through github, that new branch is built on the buildbot suite, in which we currently don't have a mac `ALL` test running.. If you have a fairly powerful machine that is always on, we could then use this to test an `ALL` mac build and improve the testing and build robustness on mac platforms..

**Comment by potter2** [comment]
I need to think about the mac connection. I’ll get back t you next week..

Jerry


Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

On Sep 1, 2015, at 1:44 PM, Paul J. Durack <notifications@github.com<mailto:notifications@github.com>> wrote:


Great @potter2<https://github.com/potter2> yeah the build will work, as long as it is permanently connected.. @doutriaux1<https://github.com/doutriaux1> can explain specifics, but simply when a pull request is issued through github, that new branch is built on the buildbot suite, in which we currently don't have a mac ALL test running.. If you have a fairly powerful machine that is always on, we could then use this to test an ALL mac build and improve the testing and build robustness on mac platforms..

**Comment by doutriaux1** [comment]
@durack1 no it is not a given, for example at my place ATT blocks me from talking over 9982... I tried to open the port but no luck so far, even tried using other ports. From talking to ATT they have no idea my port stays blocked even after I tell my router to open it... So it's not 100% sure.

**Comment by doutriaux1** [comment]
@potter2 any progress with ucdavis?

**Comment by durack1** [comment]
@doutriaux1 could a routing rule be setup?

**Comment by doutriaux1** [comment]
I tried that and talked with ATT they were baffled it didn't work...

**Comment by jbeezley** [comment]
There is always [ngrok](https://ngrok.com/).

**Comment by doutriaux1** [comment]
oh that's looks nice, maybe i will try that.

**Comment by doutriaux1** [comment]
will add a mac 10.11 when it's out officially (and bug have been ironed out)

**Comment by doutriaux1** [comment]
i think we aare pretty much abandoning travis at that point @chaosphere2112 are we getting a pro licence or not? If not let's dump travis

**Comment by durack1** [comment]
@doutriaux1 [`Xcode 7` was released today](https://itunes.apple.com/us/app/xcode/id497799835?mt=12) which goes along with `OS X 10.11`, so probably worth dropping that into the buildbot suite as soon as an `OS X` machine becomes available..

**Comment by doutriaux1** [comment]
Once the lab has an approved image for the green network will do.

**Comment by doutriaux1** [comment]
http://github.com/UV-CDAT/uvbot
