### ISSUE TITLE
vcs.Canvas.setantialiasing unusable

### ISSUE THREAD

**Issue by dlonie** [UV-CDAT/uvcdat#1400]
`vtkRenderWindow` needs to have multisampling settings specified before the first render, but currently `setantialiasing` can only be used before the window is created (which triggers an error) or after initialization (which has no effect).

The easy fix would be to make an antialiasing ivar in the canvas or backend that can be set between calls to `vcs.init` and `Canvas.plot`, and warns if called after the window is already initialized.

**Comment by aashish24** [comment]
@dlonie I would assign it to @sankhesh

**Comment by dlonie** [comment]
@sankhesh Grab me if you want to go over this -- this one should be higher priority than the other issues.

**Comment by dlonie** [comment]
@sankhesh The code of interest is in `Packages/vcs/Lib/VTKPlots.py`, the `setantialiasing` and `getantialiasing` methods.

To visually determine whether or not antialiasing is working the following command line can be used to produce a line plot with aliasing artifacts:

`[build dir]/install/bin/runtest [source dir]/testing/vcs/test_vcs_basic_gms.py --gm_type=yxvsx --show`

**Comment by sankhesh** [comment]
Fixed and merged
