### ISSUE TITLE
vcs removeobject function broken

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1423]

**Comment by doutriaux1** [comment]
@durack1 can you please refresh my memory on this?

**Comment by durack1** [comment]
@doutriaux1 was it something like:

```python
x = vcs.init()
x.plot(something,t2,iso2)
x.clear() ; # <- This doesn't work, doesn't clear all x objects
x.removeobject() ; # <- neither does this
```

**Comment by doutriaux1** [comment]
x.removeobject does need an object to be passed to it I believe.

**Comment by doutriaux1** [comment]
x.clear() should only clear the screen

**Comment by durack1** [comment]
@doutriaux1, yes and when you pass it an object, it doesn't remove it.. Hence it's `broken`
