### ISSUE TITLE
fetching uvcdat-testdata broken on mac

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1427]
```
[ 91%] Updating uvcdat-testdata repo.
Cannot update uvcdat-testdata checkout at "/Users/mcenerney1/build_latest/uvcdat-testdata". Error updating remote branches with 'git fetch --update-shallow --depth=1':
.error: unknown option `update-shallow'
usage: git fetch [<options>] [<repository> [<refspec>...]]
   or: git fetch [<options>] <group>
   or: git fetch --multiple [<options>] [(<repository> | <group>)...]
   or: git fetch --all [<options>]
```

my git

```
git --version
git version 1.8.3.4 (Apple Git-47)
```

**Comment by aashish24** [comment]
@dlonie do we really need update-shallow option? What does it do?

**Comment by dlonie** [comment]
We can get rid of it, but we'd need to do a full clone of the test data instead of a shallow one.

That is a very old git....any way you can easily update it? The current Arch package is at 2.3.6 for comparison.

We'll either need to fetch the entire history of the testdata repo, or bump the minimum git version (do we have a minimum git version? I don't see one on https://github.com/UV-CDAT/uvcdat/wiki/System-Requirements ).

**Comment by aashish24** [comment]
@dlonie I was thinking about old version as well but I don't know how it is on Mac recently. May be we should check for git version and if we find it lower than < X.Y.Z then we stop the build right there.

**Comment by dlonie** [comment]
I know nothing about macs, so I'll let someone more familiar with them comment on that. 

If it's easy to upgrade git on mac, let's just (a) set a minimum git version. This isn't the first time we've had issues from outdated git installs.

If we need to support the old git versions, we'll have to abandon either (b) the shallow clone, or (c) the automatic updates.

(a) seems the cleanest to me, as long as it's not a huge hassle to update git for the users.
(b) will increase the time taken to checkout the testdata repository considerably.
(c) will break buildbots and create a bit more work for devs that are testing as well.

I suppose there's also an option (d): Add git to the superbuild and use our UV-CDAT-installed git to checkout/update the testdata repository at build-time, but hopefully we all agree that this solution would be ridiculous ;)

I vote for (a).

**Comment by doutriaux1** [comment]
@dlonie it's not "easy" to update the mac at national labs, most user do NOT have admin privileges... 
Keep in mind UV-CDAT is trying hard to be "root" independent. So when there's a way for us to fix things without requiring any user action we should go that route.

**Comment by dlonie** [comment]
Per-user local installations don't need admin access, but its up to you guys how we proceed. Let me know.

**Comment by doutriaux1** [comment]
yes but they are clueless.... i vote for no extra work for user

**Comment by doutriaux1** [comment]
@aashish24 reassigning this to you.

**Comment by aashish24** [comment]
@doutriaux1 @mcenerney1 I believe this is no longer an issue?

**Comment by doutriaux1** [comment]
yes fixed.
