### ISSUE TITLE
 uvcdat writing thousands of tempfiles to users' .uvcdat directory

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1428]
We have been having problems with uvcdat writing thousands of tempfiles to users' .uvcdat directory and maxing out their disk space.  For example, one of our users has found 39500 files (totaling 1.5 GB) of the form:  %2Fhome%2Flcarrier%2F.uvcdat%2Funtitled.vt_tmp_9999.   Anyone know why this would be happening?

— Tom

**Comment by aashish24** [comment]
@doutriaux1 do you want to look into this? It seems to me that .vt files are vistrails files but I could be wrong.

**Comment by doutriaux1** [comment]
yes they are vistrails files, I'm not sure what the best way to move forward is here, considering recent development

**Comment by aashish24** [comment]
@ThomasMaxwell did the user ran the GUI? these files could the provenance files used. If that's the case, we may have to put a workaround for now.

**Comment by ThomasMaxwell** [comment]
Yes, the user was using the GUI.   These could be provenance files but I don’t know why there would be so many of them.

**Comment by aashish24** [comment]
There could be multiple reasons. Vistrails create temporary file for few things. I will see if I can reproduce.

**Comment by doutriaux1** [comment]
@chaosphere2112 @rexissimus can one of you take a quick stab at this?

**Comment by rexissimus** [comment]
These are autosave files that are created every 2 minutes. They are deleted when closing uv-cdat. But it could lead to problems when leaving uv-cdat running for long periods of time. In this case it looks like uv-cdat has been running for 2 months?

We could fix this by limiting the number of temporary files somehow, but I am not sure this is worth looking into at this point?

**Comment by chaosphere2112** [comment]
@rexissimus We're shipping a release of the existing GUI, so, yeah, it'd be nice to clean this up. Can you just shove them into /tmp instead of .uvcdat?

**Comment by rexissimus** [comment]
Then you would probably lose the autosave if the machine reboots and /tmp is wiped. I will look into limiting the number of temporary files instead.

**Comment by doutriaux1** [comment]
why do we need a new file every two minutes? Can't the new file contain the necessary informations from the previous one and delete the old one?

**Comment by rexissimus** [comment]
Having 2 autosaves may be useful if there is a crash while writing it. Having more could possibly be useful if the loaded file gets corrupted while in memory and you need to restore from some time before. But this is unlikely to happen. I added a fix that limits the files to between 30-60: https://github.com/UV-CDAT/VisTrails/issues/55
