### ISSUE TITLE
cdutil import error

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1434]
What happened to cdutil; this used to work.

Python 2.7.10 (default, Jun 26 2015, 15:45:45) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cdutil

**Comment by doutriaux1** [comment]
@mcenerney1 had an incomplete build
