### ISSUE TITLE
isofill flip fails

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1438]
This used to work for diagnostics, in particular #4

import vcs
x=vcs.createisofill()
>>> x.flip=True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gfi' object has no attribute 'flip'

**Comment by doutriaux1** [comment]
@mcenerney1 this was actually an error in your code. VCS has been "fixed" and now informs you of invalid attribute setting.
