### ISSUE TITLE
Fix test-laptop not booting up (for buildbot)

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1445]

**Comment by aashish24** [comment]
@sankhesh you can ping sys-admins on this.

**Comment by sankhesh** [comment]
@aashish24 Where is this laptop?

**Comment by aashish24** [comment]
In my office, next to my screen toward the RHS

**Comment by aashish24** [comment]
@doutriaux1 @sankhesh we fixed the issue. I should have it up and running by tomorrow.

**Comment by doutriaux1** [comment]
@aashish24 want to keep on your buildbot? Or slave it to our uvbot master?

**Comment by aashish24** [comment]
@doutriaux1 yeah it was using older version of buildbot and it is a slave.

**Comment by doutriaux1** [comment]
I meant a slave of the uvcbot on aims4.llnl.gov
