### ISSUE TITLE
setantialiasing not working if set too early

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1447]
```
429: /lgm/uvcdat/2015-07-06/lib/python2.7/site-packages/vcs/VTKPlots.py:950: UserWarning: no RenderWindow ready, skipping setantialiasing call, please reissue at a later time
429:   warnings.warn("no RenderWindow ready, skipping setantialiasing call, please reissue at a later time")
```
I think if the rendering window is not present, this call should still set some value somewhere that will be used when the rendering window is created.

**Comment by sankhesh** [comment]
This issue is fixed with my antialiasing branch and is merged in master.
The antialiasing value is cached and later used when creating the render window

Ref: https://github.com/UV-CDAT/uvcdat/commit/de85f8f36ed69b84f3f42ace6a857d5e72515cf5?diff=unified
