### ISSUE TITLE
update bUILD_MODE instructions

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1455]
https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options

@aashish24 you volunteered to fill the table at the end of this page a while back, it is very very usefull information, please update.

**Comment by aashish24** [comment]
Sure!

**Comment by jypeter** [comment]
:+1: 

I have documented the options I used for 2.1 below. I found out about the available options by making a ccmake dry-run and checking all the options (and asking you questions...). Having more details on the web would be nice
https://wiki.lsce.ipsl.fr/pmip3/doku.php/other:uvcdat:installed#ccmake_options

If you review the options, it would be nice to check the description of each option you get inside ccmake. Sometimes there is some help, sometimes there is no description of what the option is for

I may try to make an offline build of 2.1 on our remote and secure supercomputer. I kinda remember there was a cmake option about that, and it should be listed there!

**Comment by doutriaux1** [comment]
@aashish24 don't forget about this please.

**Comment by doutriaux1** [comment]
@aashish24 ping!!!!

**Comment by doutriaux1** [comment]
@aashish24 we are closing in on a year of waiting for you on this. :sob: :disappointed: :-1:

**Comment by aashish24** [comment]
@doutriaux1 its like wine, the older it gets the better. I am revamp the entire document since there is no sane way of doing it in github wiki. I have moved it to 2.6

**Comment by doutriaux1** [comment]
be careful though after too long wine turns to vinegar :stuck_out_tongue_winking_eye: thanks for revamping the doc.

**Comment by jypeter** [comment]
Thanks! We'll get some nice balsamic vinegar! :+1:

**Comment by doutriaux1** [comment]
sort of not an issue since we are moving to conda

**Comment by jypeter** [comment]
I did not know about the *conda* plans. Can you give me some details, or some document about that? At least:

- when will you move?
- does this mean we install anaconda first, and then UV-CDAT specific packages?

Thanks!

**Comment by doutriaux1** [comment]
We're hoping to move for 2.6, and yes install anaconda first then use it to get uvcdat.
