### ISSUE TITLE
g2clib makefile typo

### ISSUE THREAD

**Issue by dnadeau4** [UV-CDAT/uvcdat#1460]
George Britzolakis found a typo in a Makefile where $(DEFS) is defined but $(DEPS) is use in the command line for the compiler.

Here is his email:

> Yesterday, I was able to find the solution to the grib2 file problem we were having. Now you can read grib2 files without getting the usual:
```
g2_getfld: return from g2_unpack7 = 4
GRIB2 I/O Error: g2_getfld failed, ierr=14
g2_unpack7: Data Representation Template 5.40 not yet implemented.
```
> As you can see below:
```python
>>> import cdms2;
>>> tt=cdms2.open("/home/gbritzol/judyInputs/cdas1.20140102.pgrbh.ctl")
>>> vvelprs=tt.variables['vvelprs']
>>> vv=vvelprs.getValue()
```
>I can now read those problematic files.
>
>For the UV-CDAT developers this seems to be in the g2clib version and compilation. After tracking the problem I upgraded the g2clib to version v1.4.0 and changed the makefile so the $(DEFS) (which corresponds to DEFS=-DUSE_JPEG2000 -DUSE_PNG) needs to be added to the linking step. It seems that the UV-CDAT team misspelled the $(DEFS) environment variable with $(DEPS) and this is causing this format mismatches when reading the grib2 files. This fix might fix other also problems related to g2clib library so I would recommend emailing the UV-CDAT team. If they would like me to give them the patch I can always provide them with my tar file.
>
>Let me know if you have any questions.
>
>Thanks,
>
>George.

**Comment by durack1** [comment]
@dnadeau4 I wonder if #1408 will solve this and similar issues?

**Comment by dnadeau4** [comment]
I have donwnloaded g2lib-1.4.0.tar in my home directory on aims4. 

I will copy them under:
* /var/www/uvcdat-dev/cdat/resources/
* /var/www/cdat/resources

**Comment by dnadeau4** [comment]
@durak1 #1408 is more about coding convention or coding style using pep8 or flake8.  This one is about some CFLAGS not being passed to the compiler and grib2 can't be read correctly in some cases.

**Comment by durack1** [comment]
@dnadeau4 oh well, I was hoping that mis-typed/unused variables might also be caught by these checks.. I know they alert for unused module loads within python..

**Comment by doutriaux1** [comment]
@dnadeau4 don't forget to update: https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/g2clib_pkg.cmake

**Comment by dnadeau4** [comment]
Ok Thanks,   Got the MD5 right so far.

**Comment by durack1** [comment]
@dnadeau4, @doutriaux1 can correct me if I'm wrong but `$LLNL_URL` points only to `/var/www/cdat/resources` as far as I know.. There is no need to duplicate in the `uvcdat-dev` tree..

**Comment by dnadeau4** [comment]
@durack1, @doutriaux1 Is this URL still active.  In points to uvcdat-dev 
http://uvcdat-dev.llnl.gov/cdat/

**Comment by doutriaux1** [comment]
no it's deprecated.

**Comment by doutriaux1** [comment]
well... I think it's used only by web devs to "preview" their changes.

**Comment by dnadeau4** [comment]
When I add g2clib1.4.0 I get an png error for Mac OS.   Need to find out how to add or link with libpng.  The current version is libpng16 which probably need to be installed in the EXTERNALS directory.

**Comment by doutriaux1** [comment]
@dnadeau4 let's get together on monday. also take a look at the makefile in our "llnl" tarball, I remenber i had to tweak it. download "ours" and "their" previous versions and make a diff to see what I changed.

**Comment by dnadeau4** [comment]
Pushed g2clibupdate branch this morning.  I re-enabled png library, to make grib2 work with g2clib 1.4.0.  I also updated the makefile in g2clib 1.4.0 Please take a look when you get a chance.
