### ISSUE TITLE
Is there a way to do animations of plots in v2.2.0?

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1473]
I would like to animate over one of the dimensions in a 3D-array to produce an animation within the GUI.  However, I don't see the capability in v2.2.0, and the 'slicer' doesn't appear to be available.  Am I missing these options?   Any easy work-around?  
I am running on Rhea.

**Comment by durack1** [comment]
@cameronsmith1 I can't help with GUI queries, but if you want to dive into scripting this might get you an animation (warning it's not interactive as I assume you're wanting):
```python
x = vcs.init()
x.ffmpeg('out.mp4',outFileList,rate=5,bitrate=2048)
x.close()
```
If you want to hack a script there's one at:
https://github.com/PCMDI/amipbcs/blob/master/make_newVsOldDiffs.py#L170-226

The way I did it was to generate each step (a single output file: `*.png`), create a list of these while processing and then pass the list (`outFileList` above) to `vcs.ffmpeg()` with a couple of arguments (or more above) and you should get an output animation

**Comment by chaosphere2112** [comment]
@cameronsmith1 Yup, there is; it's a little bit buried right now, and I apologize for that.

![screen shot 2015-07-29 at 2 30 24 pm](https://cloud.githubusercontent.com/assets/718512/8970427/84c62be6-35fe-11e5-88cc-aa364b6991dd.png)

Click on the "Edit" pencil

![screen shot 2015-07-29 at 2 30 32 pm](https://cloud.githubusercontent.com/assets/718512/8970428/84c7c83e-35fe-11e5-98ae-1ff2224ee106.png)

This will also bring up a configuration pane; you can ignore it. Click on the "Open Configure" button that showed up on the screen.

![screen shot 2015-07-29 at 2 30 40 pm](https://cloud.githubusercontent.com/assets/718512/8970431/84c95546-35fe-11e5-85ab-2dbb516c790a.png)

Now click "Open Animation"

![screen shot 2015-07-29 at 2 30 43 pm](https://cloud.githubusercontent.com/assets/718512/8970429/84c7e10c-35fe-11e5-94ed-75caaacc7e1f.png)

If you click "Run Animation", the animation will start playing.  You can click Show Speed (Step Delay) to change how quickly the animation happens.

![screen shot 2015-07-29 at 2 30 45 pm](https://cloud.githubusercontent.com/assets/718512/8970430/84c81b90-35fe-11e5-83e4-8d40ef2526ee.png)
![screen shot 2015-07-29 at 2 30 49 pm](https://cloud.githubusercontent.com/assets/718512/8970432/84c970e4-35fe-11e5-9171-4dcfc8910ef9.png)

If you want to save the animation (and I know this is a terrible UI, again, work in progress), click Save Animation. Some output will show up in your console's log, and it will save the animation at `~/.uvcdat/animation/ANIMATION.mp4`. It names the animation file based on the graphics method and variables used– for this one, it saved as `boxfill_Total_cloudiness.mp4`.

An upgraded UI for this is on the shortlist of things I'm working on.

**Comment by cameronsmith1** [comment]
OK.   That works.  Thanks.

**Comment by durack1** [comment]
@cameronsmith1 if you're happy with this, I suggest closing the issue..
