### ISSUE TITLE
isoline labels still defective

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1487]
I just bult UVCDAT from master and the isoline labels now work. The spacing is still broken but something needs to be fixed about the round-off.
![isoline_example](https://cloud.githubusercontent.com/assets/2963950/9189597/72985994-3f9f-11e5-8514-7691823c8eed.png)

**Comment by williams13** [comment]
Thanks Jerry for testing. Can you test two things: (1) change the color of the isoline text labels to “white”; and (2) change the background of the text labels to “white”? This should allow better viewing of the isoline labels.

-Dean

**Comment by doutriaux1** [comment]
@sankhesh can you look into the roundoff please?
@dlonie can we control the label background color? @sankhesh we can add to the python interface if/when the feature exists in VTK.

**Comment by potter2** [comment]
Thank you Charles, I was just going to ask you how do do this.


On Aug 11, 2015, at 9:14 AM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@sankhesh<https://github.com/sankhesh> can you look into the roundoff please?
@dlonie<https://github.com/dlonie> can we control the label background color? @sankhesh<https://github.com/sankhesh> we can add to the python interface if/when the feature exists in VTK.

—
Reply to this email directly or view it on GitHub<https://github.com/UV-CDAT/uvcdat/issues/1487#issuecomment-129951806>.

--
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by dlonie** [comment]
See `vtkTextProperty::SetBackgroundColor` and `vtkTextProperty::SetBackgroundOpacity` for background coloring.

**Comment by sankhesh** [comment]
@doutriaux1 @potter2 

I can add the background color and opacity API to VCS. 
I'm not sure I understand what the roundoff issue is?

**Comment by sankhesh** [comment]
@potter2 

You have to explicitly set the `labelskipdistance` parameter on the isoline to make the spacing work. Here is an [example] (https://github.com/UV-CDAT/uvcdat/blob/294d67d904c83e19ac060a668c5152e30671de3e/testing/vcs/test_isoline_labelskipdistance.py#L22).

`labelskipdistance` represents the minimum distance between two isoline labels. By default, it is 0.

**Comment by doutriaux1** [comment]
@sankhesh look at @potter2 pix, the "0" (zero) isoline labels do not say "0" but 1.E-16 or something like that.

**Comment by doutriaux1** [comment]
actullay it says -4.4E16

**Comment by sankhesh** [comment]
I see. I can take a look at that as well.

**Comment by glpotter** [comment]
![isoline_labels](https://cloud.githubusercontent.com/assets/14208252/9863806/372b7f34-5af8-11e5-94d6-05a615bb08df.png)

I just built from "master" and this is still broken. I thought somebody said it was fixed.

**Comment by doutriaux1** [comment]
no the zero thing is not fixed it is part of the last bit that @sankhesh needs to do.

**Comment by doutriaux1** [comment]
@potter2 but does the distance thing work as you want?

**Comment by aashish24** [comment]
@sankhesh I remember we talked about it. I thought you had a branch. Is that mixed in another label branch?

**Comment by sankhesh** [comment]
Label skip distance is merged in master. I'll get to the background and precision issue once I get back on Wednesday.

**Comment by sankhesh** [comment]
@potter2 @doutriaux1 

Could you please post a script to reproduce the floating point precision issue?

**Comment by sankhesh** [comment]
Regarding precision issue, I have a fix on the [VTK repo](https://gitlab.kitware.com/vtk/vtk/merge_requests/674)
