### ISSUE TITLE
VTK build error on Linux

### ISSUE THREAD

**Issue by bekozi** [UV-CDAT/uvcdat#1494]
Hi. I am attempting to build from source and getting the VTK error below. The output from cmake is here: https://gist.github.com/bekozi/7d7b68f9198e4373e124. I am building at the 2.2.0 release commit (https://github.com/UV-CDAT/uvcdat/commit/45488cb2a93fc3c0b1052e8ea26e404766038dc9).

I may need to install OpenGL?

Thanks!

```sh
  -------------------------------------------------

  CMake Error at
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138
  (message):

    Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)

  Call Stack (most recent call first):

    /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
    /usr/local/share/cmake-3.2/Modules/FindOpenGL.cmake:168 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    Rendering/OpenGL/CMakeLists.txt:196 (find_package)

  

  

  CMake Error: The following variables are used in this project, but they are
  set to NOTFOUND.

  Please set them or make sure they are set and tested correctly in the CMake
  files:

  OPENGL_INCLUDE_DIR (ADVANCED)

     used as include directory in directory /home/benkoziol/src/build-uvcdat/build/VTK/Geovis/Core

  

  -------------------------------------------------



make[2]: *** [VTK-prefix/src/VTK-stamp/VTK-configure] Error 1
make[1]: *** [CMakeFiles/VTK.dir/all] Error 2
```

**Comment by aashish24** [comment]
@bekozi I would suggest uvcdat-support@llnl.gov is the best forum for such discussions. On your question: Yes, you would need to install GL libraries (mesa or proprietary). What system you are using?

**Comment by bekozi** [comment]
Thanks @aashish24. I missed the bit about OpenGL on the system requirements wiki page. I was able to build successfully after running ``sudo apt-get install mesa-common-dev freeglut3-dev``. I am using Linux Mint 17.1 (Ubuntu 14.04).

**Comment by aashish24** [comment]
great..thanks. I believe we do have that listed (which I hope you are saying as well). If not, we will make sure its there.

**Comment by bekozi** [comment]
Yeah, it's listed here: https://github.com/UV-CDAT/uvcdat/wiki/System-Requirements#ubuntu. It wasn't in the "must have" category...

**Comment by aashish24** [comment]
Thanks. I will fix that. If you have the graphics is ON, it is a must

**Comment by bekozi** [comment]
I built more or less exactly from the Linux build instructions: https://github.com/UV-CDAT/uvcdat/wiki/Build-on-Linux. No special arguments.
