### ISSUE TITLE
Install PyNCO as part of UV-CDAT

### ISSUE THREAD

**Issue by czender** [UV-CDAT/uvcdat#1550]
Hi UV-CDAT folks,

PyNCO, the Python wrappers for NCO, are at

http://github.com/nco/pynco

I would like to start implementing a plan to get PyNCO into UV-CDAT. Please take a look and let us know whether anything about the package needs to change before it can be distributed with UV-CDAT. The goal is

from nco import Nco

works in any Python script that uses UV-CDAT. Joe Hamman (who wrote PyNCO) and I will try to make any necessary PyNCO changes. First we need to know what would make integration/distribution with UVCDAT go smoothly...

Obviously NCO needs to be installed for PyNCO to do anything. However, I thought starting this issue/ticket with the smaller and more familiar task of adding a Python library might get the ball rolling, and we can tackle any issues that arise with installing NCO as they arise from installing testing PyNCO. Or if you'd prefer a different strategy that's fine too...

Thanks!
Charlie

**Comment by williams13** [comment]
This is great! Thanks Charlie for working on this.

Best regards,
Dean

**Comment by doutriaux1** [comment]
Charlie,

I will take a look as soon as possible, it’s too close from the relase to make it in I think, so probably right after it.

BUT I will do my best to take a look before we release so that if everything goes super smooth we can stick it into the upcoming release.

C.

**Comment by aashish24** [comment]
@czender this is great!!!!~ I will have a look as well as I wanted to use combination of NCO and VCS for some time.

**Comment by czender** [comment]
I'm closing this issue as NCO itself is now included in ACME-unified, and there has been little call for the Python wrappers PyNCO.
