### ISSUE TITLE
generate range and pattern broken from GUI

### ISSUE THREAD

**Issue by dnadeau4** [UV-CDAT/uvcdat#1573]
generating range 24 to 36 n = 6 ext on misses one color when geenrated

pattern is never generated
manually applying pattern is not picked up

**Comment by chaosphere2112** [comment]
@dnadeau4 First half is solved in the PR I just submitted, second half is documented further in #1577

**Comment by dnadeau4** [comment]
@chaosphere2112 thanks!  It is hard to detect these kind of bugs.   The software did not crash or anything, just did not answer back with patterns, but with filled colors.

**Comment by chaosphere2112** [comment]
Yup, took a bit of nosing around to determine where to point the finger.

**Comment by aashish24** [comment]
@chaosphere2112 should we close this issue?

**Comment by doutriaux1** [comment]
@chaosphere2112 I think you fixed this no?

**Comment by chaosphere2112** [comment]
Hasn't been merged yet (UV-CDAT/Vistrails#59), but yeah, it's fixed.

**Comment by doutriaux1** [comment]
merged now.
