### ISSUE TITLE
Warning: Stenciling is not enabled on Isoline

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1576]
On a clean build from yesterday, I was testing isolines and I receive this warning message on every re-render:

```
Warning: In $PATH/VTK/Rendering/Core/vtkLabeledContourMapper.cxx, line 522
vtkOpenGLLabeledContourMapper (0x7ff1762c1b40): Stenciling is not enabled in the render window. Isoline labels will have artifacts. To fix this, call vtkRenderWindow::StencilCapableOn().
```

This is showing up in the GUI; just plot an isoline there and resize the window.

**Comment by aashish24** [comment]
I think its not a VCS/VTK issue but rather a issue with the GUI context which does not support Stencil operation. Who creates the context in the case of GUI? Does the command line works?

**Comment by chaosphere2112** [comment]
@aashish24 Looks like you're right; submitting a quick fix to vistrails now.
