### ISSUE TITLE
Patterns & Hatches on Boxfill, Isofill

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1577]
Looks like patterns and hatches work correctly for `fillarea`s and `isofill` plots, but not for `boxfill`.

```python
import vcs, cdms2

x = vcs.init()

f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

box = x.createboxfill()
box.fillareastyle = "hatch"
box.fillareacolors = [20, 50, 75]
box.fillareaindices = [5, 10, 15]
box.levels = [10, 50, 75, 100]
box.boxfill_type = "custom"

x.plot(s, box)
x.png("hatch_box.png")

isofill = x.createisofill()
isofill.fillareastyle = "hatch"
isofill.fillareacolors = [20, 50, 75]
isofill.fillareaindices = [5, 10, 15]
isofill.levels = [10, 50, 75, 100]

x.clear()

x.plot(s, isofill)
x.png("hatch_isofill")
```

Produces these two:
![hatch_box](https://cloud.githubusercontent.com/assets/718512/10198182/c3620b04-674f-11e5-9e1f-12a9a976c90d.png)
![hatch_isofill](https://cloud.githubusercontent.com/assets/718512/10198184/c363d0f6-674f-11e5-820e-dccdfc5d4fcb.png)

```python
import vcs, cdms2

x = vcs.init()

f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

box = x.createboxfill()
box.fillareastyle = "pattern"
box.fillareacolors = [20, 50, 75]
box.fillareaindices = [5, 10, 15]
box.levels = [10, 50, 75, 100]
box.boxfill_type = "custom"

x.plot(s, box)
x.png("pattern_box.png")

isofill = x.createisofill()
isofill.fillareastyle = "pattern"
isofill.fillareacolors = [20, 50, 75]
isofill.fillareaindices = [5, 10, 15]
isofill.levels = [10, 50, 75, 100]

x.clear()

x.plot(s, isofill)
x.png("pattern_isofill")
```

Produces these two:
![pattern_box](https://cloud.githubusercontent.com/assets/718512/10198183/c3628796-674f-11e5-9cf3-acdb9ae5f938.png)
![pattern_isofill](https://cloud.githubusercontent.com/assets/718512/10198185/c372da10-674f-11e5-8472-5e719066f348.png)

In addition, the performance of plotting the patterns/hatches for the isofill is pretty slow:

```python
import datetime, vcs, cdms2

x = vcs.init()
f = cdms2.open(vcs.sample_data + '/clt.nc')
s = f('clt')

def t():
   return datetime.datetime.now()

isofill = x.createisofill()
isofill.fillareaindices = [1, 5, 10]
isofill.fillareacolors = [50, 100, 150]
isofill.levels = [0, 25, 75, 100]

for style in ("hatch", "pattern", "solid"):
   isofill.fillareastyle = style
   before = t()
   x.plot(s, isofill)
   after = t()
   print after - before
```
gives us these times:
0:00:03.027187 (hatch)
0:00:03.077247 (pattern)
0:00:00.559602 (solid)

So, that's some pretty serious overhead.

**Comment by aashish24** [comment]
@chaosphere2112 the performance will be slow because we need to add lot more steps for the pattern but its worth investigating more post 2.4

**Comment by sankhesh** [comment]
@aashish24 is right. The time performance is slow because of the whole set of tasks involved. It can be improved by reducing the size of the texture created per fill area. Currently, the size is 4 times the bounds of the polydata. However, reducing the size would reduce resolution of the patterns/hatches.

**Comment by aashish24** [comment]
@chaosphere2112 is this really critical? If yes, then @sankhesh let's reduce the size for now and we can think about a better solution for 3.0.

**Comment by chaosphere2112** [comment]
@sankhesh @aashish24 Well, the critical part is the first half of the bug report (where boxfill isn't getting patterns and hatches). Performance isn't super critical; I just tested it in the GUI, and it actually goes quite a bit faster than I was experiencing in the command line, so that's weird.

**Comment by aashish24** [comment]
thanks @chaosphere2112 that sounds reasonable. Roger that. That is weird.. may be try again?

**Comment by chaosphere2112** [comment]
@aashish24 @sankhesh  Looks like specific patterns/hatches are the problem, not all of them.

Pattern Number | Pattern Time | Hatch Time
--------------------- | ----------------- | ---------------
1 | 0:00:00.487568 | 0:00:00.414466
2 | 0:00:00.288609 | 0:00:00.295397
3 | 0:00:00.268531 | 0:00:00.402500
4 | 0:00:00.273018 | 0:00:00.271401
5 | 0:00:00.270258 | 0:00:00.271995
6 | 0:00:00.268783 | 0:00:00.271023
7 | 0:00:00.269698 | 0:00:00.279364
8 | 0:00:00.275035 | 0:00:00.288632
9 | **0:00:42.809225** | **0:00:42.989813**
10  | 0:00:03.376930 | 0:00:03.116200
11  | 0:00:03.138273 | 0:00:03.060134
12  | 0:00:03.127413 | 0:00:03.048566
13  | 0:00:03.072687 | 0:00:03.132620
14  | 0:00:00.278787 | 0:00:00.271428
15  | 0:00:00.272481 | 0:00:00.278344
16  | 0:00:00.282526 | 0:00:00.280305
17  | 0:00:00.371303 | 0:00:00.366816
18  | 0:00:00.299080 | 0:00:00.298072

**Comment by aashish24** [comment]
Great.. this is very useful finding! thanks.

**Comment by sankhesh** [comment]
Ahh.. Thanks for sharing @chaosphere2112 
I can look at why pattern number 9 generation takes so much time.

**Comment by chaosphere2112** [comment]
That's certainly the most urgent, yeah. If you could get 10-13 to be faster as well, that'd be cool.

**Comment by sankhesh** [comment]
For reference, here are all the patterns/hatches: 
![Patterns/hatches in UV-CDAT](https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/722bc991d32c295fe270d1bc2b5cbb06d3736437/baselines/vcs/test_vcs_hatches_patterns.png).

**Comment by sankhesh** [comment]
**Update:**

Custom boxfill plot:
![boxfill_patterns](https://cloud.githubusercontent.com/assets/936354/10269938/77956012-6ab1-11e5-9b13-26f63cb44ef4.png)


Should non-custom boxfill plots also support patterns/hatches?

**Comment by chaosphere2112** [comment]
@sankhesh Nope, just the custom ones.

**Comment by doutriaux1** [comment]
@sankhesh non-custom never did support it because they do not use the filler attributes. I don't think we need to revise this. But now that I think of it we probably should update the attribute setting method to check if the type is custom and raise a warning if we set any of these.

**Comment by sankhesh** [comment]
Thanks @doutriaux1 @chaosphere2112 

Created #1582 for boxfill patterns/hatches support.

Timing improvements to follow.
