### ISSUE TITLE
Update netcdf to 4.4.0

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1579]
`netcdf 4.4.0` is [expected to land in October 2015](https://github.com/Unidata/netcdf-c/issues/121#issuecomment-144826484). It provides inclusion for [`cdf-5` "big-netCDF" support](https://bugtracking.unidata.ucar.edu/browse/NCF-163) which would be a nice augmentation to current `netcdf` functionality in UV-CDAT to keep things bleeding edge.

Here are some links about the `cdf-5` format - it would seem to me that it just extends from the `netcdf-3` to `netcdf-4` data model (allowing unsigned types etc) and also [includes support for BIG variables (>4GB)](http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg11545.html):
http://cucis.ece.northwestern.edu/projects/PnetCDF/CDF-5.html
http://cdf.gsfc.nasa.gov/html/FAQ.html

**Comment by aashish24** [comment]
:+1:

**Comment by durack1** [comment]
@doutriaux1 it'd be great to get this merged.. [`4.4.1` is also nearing release too](https://github.com/Unidata/netcdf-c/releases/tag/v4.4.1-rc2)

**Comment by doutriaux1** [comment]
again it doesn't matter since 2.6 is distributed via conda. This goes away with my conda PR. Now I'm open to use 4.4 with conda build system

**Comment by durack1** [comment]
@doutriaux1 why close this when the conda build system should be updated to use the latest `4.4.0` release? There's even a closed PR ready to roll https://github.com/UV-CDAT/uvcdat/pull/1676
