### ISSUE TITLE
GEOS5_sample.nc not copied to correct sample_data directory for OSX

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1581]
On OSX, `vcs.sample_data` points to `$INSTALL/share/uvcdat/sample_data`. `GEOS5_sample.nc`, a data file provided by DV3D, installed to `$INSTALL/Library/Frameworks/Python.framework/Versions/2.7/share/uvcdat/sample_data`.

**Comment by aashish24** [comment]
@chaosphere2112 I believe @doutriaux1 fixed this issue.

**Comment by doutriaux1** [comment]
not yet...

**Comment by aashish24** [comment]
@doutriaux1 I thought you had a branch for it no?

**Comment by doutriaux1** [comment]
nope

**Comment by aashish24** [comment]
I am going to take over this bug..

**Comment by doutriaux1** [comment]
@aashish24 moving to 2.6

**Comment by doutriaux1** [comment]
fixed in conda
