### ISSUE TITLE
Isoline Labels don't show up initially in GUI

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1619]
If you plot `clt` using `a_isoline`, it should display labels on the lines by default. If you open the plot configuration menu, it shows that labels are enabled for that graphics method, but they aren't displayed. If you click "apply", the labels appear.

**Comment by doutriaux1** [comment]
@chaosphere2112 the default is to have the labels off:
```python
import vcs
x=vcs.init()
iso=x.createisoline()
iso.list()
 ----------Isoline (Gi) member (attribute) listings ----------
graphics method = Gi
name = __isoline_430098060900995
projection = linear
xticlabels1 = *
xticlabels2 = *
xmtics1 = 
xmtics2 = 
yticlabels1 = *
yticlabels2 = *
ymtics1 =  
ymtics2 =  
datawc_x1 = 1e+20
datawc_y1 =  1e+20
datawc_x2 =  1e+20
datawc_y2 =  1e+20
datawc_timeunits =  days since 2000
datawc_calendar =  135441
xaxisconvert =  linear
yaxisconvert =  linear
label =  False
labelskipdistance =  0.0
labelbackgroundcolors =  None
labelbackgroundopacities =  None
line =  ['solid']
linecolors =  [1]
linewidths =  [1.0]
text =  None
textcolors =  None
level =  [[0.0, 1.0000000200408773e+20]]
clockwise =  [0]
scale =  [1.0]
angle =  [35.0]
spacing =  [1.0]
```

labels are off by default.

I think the issue is with the GUI turning it on when it shouldn't.

**Comment by chaosphere2112** [comment]
Yup, I figured that out. Just finished sorting out the issue; blame VisTrails' tendency to turn things into strings and back out again. I now use vcs.VCS_validation_functions.checkFuzzyBoolean to validate the `label` setting.
