### ISSUE TITLE
isolines GUI editor not connected

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1625]

**Comment by chaosphere2112** [comment]
Actually, it turns out `isoline.linewidths` and `isoline.line` aren't being obeyed. I'll still fix it, already found the right chunk of code.

**Comment by doutriaux1** [comment]
@chaosphere2112 this one is fixed now correct?

**Comment by aashish24** [comment]
@doutriaux1 I don't think we exposed the spacing attribute in the GUI @chaosphere2112 correct me if I am mistaken.

**Comment by doutriaux1** [comment]
@aashish24 it seems to be in
![spacings](https://cloud.githubusercontent.com/assets/2781425/11066516/6a85059c-877d-11e5-98bc-e92901a54d46.png)

**Comment by chaosphere2112** [comment]
@doutriaux1 The specific issue that was referenced in this bug (which was that the fields that were present in the GUI didn't do anything) is addressed in #1627, which is on @sankhesh's plate (as it quickly left the depth of my VTK skills).

**Comment by aashish24** [comment]
> @aashish24 it seems to be in

@doutriaux1 where do you see it? Spacings if for streamlines..

**Comment by sankhesh** [comment]
Yes. I confirm it is on my plate. I should be able to get to it today.

**Comment by aashish24** [comment]
I have created a new issue for this and assigned it to @chaosphere2112

**Comment by sankhesh** [comment]
This issue is not fixed until #1688 is merged.
