### ISSUE TITLE
Plots initially too big for plot window.

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1632]
I am using UVCDAT v2.4 GUI on Rhea.

When I first do a plot (boxfill) the plot shows up the right size for its window.  After a few seconds, it then redraws itself in a way that it is much too big for its window.    

If I resize the window, that prompts it to redraw it, and it does so correctly.

**Comment by cameronsmith1** [comment]
I get a similar problem after I plot something using CDAT in scripts.   What is particularly troublesome is that when the window resizes, the text and plots change differently, and so get out of alignment.

**Comment by jbeezley** [comment]
The resizing issue here sounds an awful lot like the resizing problem I have observed with CDATWeb.  As a side note, it happens with Mesa as well, so it doesn't seem to be related to the window manager resizing weirdness that I have seen elsewhere.

**Comment by aashish24** [comment]
@cameronsmith1 for me its the other-way around but it only happens (so far) in the GUI. I haven't tested the command line yet

**Comment by doutriaux1** [comment]
@jbeezley @chaosphere2112 is going to take a look at the GUI side. There was an issue with png resizing that is now fixed in #1667 I had to call configureEvent to force a proper re-rendering after resizing. A simple renwin.Render() wasn't enough.

**Comment by chaosphere2112** [comment]
@jbeezley @aashish24 This is what it looks like, by the way:
![screen shot 2015-11-11 at 9 39 19 am](https://cloud.githubusercontent.com/assets/718512/11098197/3188a114-8858-11e5-994c-9b554dd1abde.png)

**Comment by aashish24** [comment]
@chaosphere2112 will review it today!

**Comment by durack1** [comment]
@chaosphere2112 @aashish24 is this fixed, it looks above like https://github.com/UV-CDAT/VisTrails/issues/65 may have solved it?

**Comment by chaosphere2112** [comment]
Yup, this is fixed.
