### ISSUE TITLE
Full screen plots do not work

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1638]
Steps to reproduce:

1) Run uvcdat
2) Make it full screen
3) Plot clt (as usual)
4) It resizes automatically to some smaller size (screenshot attached)
![ss](https://cloud.githubusercontent.com/assets/146527/10739073/cfde60f2-7bf0-11e5-972e-837b5613e244.png)

Using master as of today. 

@chaosphere2112 do you want to take a look at it?

**Comment by chaosphere2112** [comment]
@aashish24 Sure, I'll take a look at it. On first glance I wasn't able to replicate, but I'm doing a clean build that I haven't messed with as much.

**Comment by chaosphere2112** [comment]
@aashish24 On a fresh build this did not happen for me. What platform are you running on?

**Comment by aashish24** [comment]
Ubuntu 14.04

**Comment by chaosphere2112** [comment]
Ok; building on Ubuntu now.
