### ISSUE TITLE
build on Ubuntu 15.10

### ISSUE THREAD

**Issue by dnadeau4** [UV-CDAT/uvcdat#1639]
ncurse 5.9 (and ncurse 6.0) needs a patch for gcc 5.2.1

* https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-libs/ncurses/files/ncurses-5.9-gcc-5.patch

VTK is failing on libraries in IO/FFMPEG

libraries not found (missing -L${EXTERNALS})
* -lavformat
* -lavcodec
* -lavutil
* -lswscale

**Comment by dnadeau4** [comment]
@aashish24 do you know what is happening with IO/FFMPEG build with gcc 5.2.1?   I tried to use LDFLAGS without success, if I change link.txt and add -L.../Extenals/lib it compiles correctly.

**Comment by aashish24** [comment]
@dnadeau4 can you send me your CMakeCache.txt

**Comment by dnadeau4** [comment]
@aashish24  here it is:
[CMakeCache.txt](https://github.com/UV-CDAT/uvcdat/files/22056/CMakeCache.txt)

**Comment by dnadeau4** [comment]
After fixing VTK link problem,  I had to recomiple PyQt4 and everything worked.

**Comment by dnadeau4** [comment]
I created a patch for "ncurses" and update cmake to "3.4.0-rc2".   I rebuild and everything worked fine.

Will try a pull request to see what happens on different machines.

**Comment by aashish24** [comment]
@dnadeau4 as promised here is the branch: https://github.com/UV-CDAT/VTK/pull/12

I will need to create a new branch for UV-CDAT as well (will do today). Will need your help with review.

**Comment by aashish24** [comment]
@dnadeau4 also, I marked it for 2.4

**Comment by aashish24** [comment]
@dnadeau4 @doutriaux1 @sankhesh please review my VTK branch, I will push a minor change for it in UV-CDAT repo as well.
