### ISSUE TITLE
pattern are not wrapped around

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1644]
```python
import vcs
import cdms2
import os


f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))
s=f("clt")

print s.getLongitude()
x=vcs.init()

gm = x.createisofill()

gm.fillareastyle= "pattern"

levels = range(0,110,10)
cols = vcs.getcolors(levels)
gm.fillareacolors = cols
gm.levels = levels

gm.fillareaindices = range(1,12)
gm.datawc_x1 = 0.

gm.datawc_x2 = 360.
x.plot(s,gm)
x.png("pattern_wrapped")
```
![pattern_wrapped](https://cloud.githubusercontent.com/assets/2781425/10795159/a88821a8-7d55-11e5-960c-596523ce91b9.png)

**Comment by aashish24** [comment]
@sankhesh I think this would be next on your list?

**Comment by aashish24** [comment]
@sankhesh can @danlipsa look into this?

**Comment by sankhesh** [comment]
@aashish24 I would prefer to finish this myself. I am re-assigning it.

**Comment by aashish24** [comment]
Absolutely!! Let me find another bug that @danlipsa can help with then.. thanks.
