### ISSUE TITLE
Isofill Blank Spots on Solid with Indices/Levels

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1645]
@aashish24 @sankhesh @doutriaux1 Just ran into this one while testing my performance branch, then went back and found it on master.

```python
import vcs, cdms2
x = vcs.init()
f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

iso = x.createisofill()
iso.levels = range(0, 100, 10)
iso.fillareaindices = range(1, 11)
iso.ext_2 = True

x.plot(s, iso)
```
 
will give you this:

![out](https://cloud.githubusercontent.com/assets/718512/10796902/6b696c16-7d5d-11e5-9578-fbd053442c3e.png)

Obviously, `fillareaindices` shouldn't have any effect on a `solid` isofill, so that's a pretty weird behavior.

**Comment by chaosphere2112** [comment]
The `ext_2` is insignificant, but was in the script that I used to generate the image.

**Comment by chaosphere2112** [comment]
Also with patterns:

```python
import vcs, cdms2
x = vcs.init()
f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

iso = x.createisofill()
iso.levels = range(0, 100, 10)
iso.fillareastyle = "pattern"
iso.fillareaindices = range(1, 11)
iso.fillareacolors = range(20, 220, 20)
iso.fillareaopacity = [100] * 10

x.plot(s, iso)
```

![pattern_white_tri](https://cloud.githubusercontent.com/assets/718512/10798686/1f375d9a-7d66-11e5-8ee5-3e9b5189cc50.png)

**Comment by sankhesh** [comment]
@danlipsa Could you please look into this next?

**Comment by aashish24** [comment]
@danlipsa I am hoping this would a tiny bug somewhere. @doutriaux1 we may have to patch our release.

**Comment by danlipsa** [comment]
Seems the problem is how vtkBandedPolyDataContourFilter fills a band. Attached are two pictures: first isocontours at 40 and 50 then a band for 40-50.
![contours-40-50](https://cloud.githubusercontent.com/assets/6180727/11284386/6d8f02f4-8ed7-11e5-8017-8fa1799f27d0.png)
![contours-filled-40-50](https://cloud.githubusercontent.com/assets/6180727/11284387/6d9283a2-8ed7-11e5-95e3-acaa80f3e4d2.png)
