### ISSUE TITLE
Patterns and Opacity

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1650]
Let's continue the debate from #1637 here instead...

I'll leave this post as just stating the issues, and we can make our arguments below.

The issues at hand: the API for patterns, and the `opacity`/`fillareaopacity` attribute's behavior

## The historical behavior

Historically, there was no `opacity` attribute, so having one is a nice step forward.

The difference between a `pattern` and a `hatch` looked like this (though this is from the current version):

![pattern_vs_hatch](https://cloud.githubusercontent.com/assets/718512/10849111/6224f7a8-7edc-11e5-8c02-0f0ed5cd9d30.png)

```python
import vcs

x = vcs.init()
fa = x.createfillarea()
fa.x = [[.25, .5, .5, .25], [.5, .75, .75, .5]]
fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75]]
fa.style = ["pattern", "hatch"]
fa.color = 50
fa.index = 9

x.plot(fa)
```

A `pattern` would plot a black pattern, and a `hatch` would plot a colored pattern. That was basically the only difference.

## The current behavior

Currently, if you leave `opacity` at its default value, you get the same plot:

![pattern_vs_hatch](https://cloud.githubusercontent.com/assets/718512/10849111/6224f7a8-7edc-11e5-8c02-0f0ed5cd9d30.png)

```python
import vcs

x = vcs.init()
fa = x.createfillarea()
fa.x = [[.25, .5, .5, .25], [.5, .75, .75, .5]]
fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75]]
fa.style = ["pattern", "hatch"]
fa.color = 50
fa.index = 9

x.plot(fa)
```

If you set `opacity` on a hatch, you get something like this:

![hatch_opacity](https://cloud.githubusercontent.com/assets/718512/10849877/14cf58e6-7ee0-11e5-8810-06a53c9f5cf7.png)

```python
import vcs

x = vcs.init()
fa = x.createfillarea()
# Draw two hatches, one transparent, with the transparent one overlaid on a solid one
fa.x = [[.25, .5, .5, .25], [.5, .75, .75, .5], [.5, .75, .75, .5]]
fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75], [.25, .25, .75, .75]]
fa.style = ["hatch", "hatch", "solid"]
fa.opacity = [100, 25, 100]
fa.color = [50, 50, 100]
fa.index = 9

x.plot(fa)
```

But, if you set `opacity` to 100 for `pattern`, you get this:

![pattern_opacity](https://cloud.githubusercontent.com/assets/718512/10850037/c47cecd6-7ee0-11e5-8b92-1a62fe517ea7.png)

```python
import vcs

x = vcs.init()
fa = x.createfillarea()
fa.x = [[.25, .5, .5, .25], [.5, .75, .75, .5]]
fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75]]
fa.style = ["pattern", "pattern"]
fa.opacity = [100, 0]
fa.color = 50
fa.index = 9

x.plot(fa)
```

This effect was relatively straightforward to replicate with the old style API; instead of the above, you could do this:

```python
import vcs

x = vcs.init()
fa = x.createfillarea()
fa.x = [[.25, .5, .5, .25], [.25, .5, .5, .25], [.5, .75, .75, .5]]
fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75], [.25, .25, .75, .75]]
fa.style = ["solid","pattern", "pattern"]
fa.color = 50
fa.index = 9

x.plot(fa)
```

and get the same output:
![pattern_layered](https://cloud.githubusercontent.com/assets/718512/10850108/19bdd67e-7ee1-11e5-99d6-2de8e4cf167e.png)

The same went for isofill:

![two_layer](https://cloud.githubusercontent.com/assets/718512/10849618/d0391312-7ede-11e5-8d8a-1e0fe3ea2304.png)

```python
import vcs, cdms2
x = vcs.init()
f = cdms2.open(vcs.sample_data + "/clt.nc")

base_iso = vcs.createisofill("base")
base_iso.levels = range(0, 101, 10)

t = vcs.createtemplate("base")

x.plot(f("clt"), t, base_iso)

pattern_iso = vcs.createisofill("patterned", base_iso)
pattern_iso.fillareastyle = "pattern"
pattern_iso.fillareaindices = range(1, 11)

# Just draw the legend and the data
t2 = vcs.createtemplate("just_data", t.name)
t2.blank()
t2.data.priority = 1
t2.legend.priority = 1
x.plot(f("clt"), t2, pattern_iso)
```

(As an implementation note, this is in essence what is happening under the covers– a solid-colored object is placed beneath the patterned object)

**Comment by chaosphere2112** [comment]
From #1637:

> My biggest problem is that it's a weird and inconsistent API. opacity and fillareaopacity (henceforth referred to as opacity) have different behaviors depending on style, and default to 0 for one of the three styles but 255 for the other two. That's incredibly odd. I spent like 2 hours trying to figure out why my patterned fills were coming out black and white, when I knew that there were colored patterns in the tests. I was assuming that opacity referred to the overall opacity of the pattern and background color, but isn't the case. Having this kind of inconsistency in an API is really frustrating, and for the most part I think we've managed to keep the inconsistencies to a minimum.

**Comment by chaosphere2112** [comment]
@sankhesh @durack1 @doutriaux1

**Comment by sankhesh** [comment]
While, us developers can keep discussing, I think the final decision should be made considering the user's point of view and usability.

**Comment by chaosphere2112** [comment]
Yup, absolutely.

**Comment by durack1** [comment]
@sankhesh @chaosphere2112 I think I'm the closest thing we have to a bonafide `user`, so am happy to chime in with my `user

**Comment by aashish24** [comment]
> import vcs
> 
> x = vcs.init()
> fa = x.createfillarea()
> fa.x = [[.25, .5, .5, .25], [.5, .75, .75, .5]]
> fa.y = [[.25, .25, .75, .75], [.25, .25, .75, .75]]
> fa.style = ["pattern", "hatch"]
> fa.color = 50
> fa.index = 9
> 
> x.plot(fa)
> If you set opacity on a hatch, you get something like this:

Where does the yellow come from?

**Comment by chaosphere2112** [comment]
@aashish24 Scripts come after images they generate in the above
