### ISSUE TITLE
Add a minmax function to MV2 ?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#1659]
It could be useful (and nice for the user?) to add the *minmax* function to MV2

```
>>> type(v)
<class 'cdms2.tvariable.TransientVariable'>

>>> genutil.minmax(v)
(-78.82099151611328, -0.19727173447608948)
>>> vcs.minmax(v)
(-78.82099151611328, -0.19727173447608948)

>>> MV2.minmax(v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'minmax'`
```

**Comment by doutriaux1** [comment]
The MV2 is supposed to map as closely as possible numpy. I'm not sure adding this is a great idea, it is already part of genutil. Note that you should use the genutil one. The `vcs.minmax` function masks out anything greater than `1.E20` whereas the `genutil.minmax` does not.

**Comment by doutriaux1** [comment]
I will wait to see if anybody else chime on this before closing. @dnadeau4 @durack1 @bonfils2

**Comment by durack1** [comment]
After talking with @dnadeau4 on the `cdms3` development timeline it could be a good time to revisit the organization of functions, considering that `MV2` just wraps `numpy` calls.. I wonder if some reorg is a good idea? This would need a new dedicated issue..

**Comment by jypeter** [comment]
@doutriaux1 OK, you are right, I bow to the logic of MV2 only mapping numpy[.ma] functions! I did not remember that

I have found something *wrong*, when comparing my cdms documentation and the MV2 one on the uv-cdat site that you probably want to check: https://github.com/UV-CDAT/uvcdat-site/issues/100 and https://github.com/UV-CDAT/uvcdat-site/issues/101

I very often use vcs.minmax, because I tend to forget that a better minmax is available in genutil.

I knew about the 1e20 limit in vcs.minmax, but are you sur this is still the case? Because the following test shows the contrary:
```
>>> import numpy as np
>>> import vcs
>>> np.random.seed(12345)
>>> rnd_data = np.random.random((12, 100, 100))
>>> rnd_data.dtype
dtype('float64')
>>> rnd_data_masked = np.ma.masked_greater(rnd_data, 0.5)
>>> vcs.minmax(rnd_data_masked)
(3.52351951848906e-06, 0.49998545777347736)
>>> rnd_data_masked[5, 50, 50] = 1e20
>>> vcs.minmax(rnd_data_masked)
(3.52351951848906e-06, 1e+20)
>>> rnd_data_masked[6, 50, 50] = 2e20
>>> vcs.minmax(rnd_data_masked)
(3.52351951848906e-06, 2e+20)
>>> rnd_data_masked[6, 50, 50]       
2e+20

```

**Comment by doutriaux1** [comment]
nope you're right doesn't look like the 1.e20 is here anymore for vcs.

**Comment by durack1** [comment]
@doutriaux1 I would recommend that the `vcs.minmax` function is removed, if in fact it's replicating the functionality of `genutil.minmax` but in completely separate code..!

**Comment by doutriaux1** [comment]
we can't remove it. We have to preserve backward compatibility but we could link it to the genutil one. Reopening.

**Comment by durack1** [comment]
@doutriaux1 I think that's a much better idea.. It would be wise to do this across the system so that just one instance of any function is used across the UV-CDAT system.. @dnadeau4 and I were talking about this in regards to `CDMS3` development plans..

**Comment by jypeter** [comment]
Sounds good to me! You'll have to tell me about cdms3 and new stuff at the December meeting

**Comment by dnadeau4** [comment]
I am not sure I can preserver backward compatibility in CDMS3 if we want to make thinks faster with nice package like Cython and Numbar.   Something to discuss in December.

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 it would be good to clean up instances where duplicated functions existing between `numpy`, `cdmsX`, `MV2`, `cdutil` and `genutil` - I think a single instance of any function is the preferred situation and will also make maintenance much more tractable

I think the `cdms3` timeline provides and opportunity for this - we can discuss more next week
