### ISSUE TITLE
Add ability to add metadata to PNG using vtkPNGWriter

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1673]

**Comment by aashish24** [comment]
@sankhesh

**Comment by danlipsa** [comment]
Pushed merge request to gitlab
https://gitlab.kitware.com/vtk/vtk/merge_requests/902

**Comment by aashish24** [comment]
@danlipsa this looks great. Can you also create a pull-request against uvcdat-master here as well: https://github.com/UV-CDAT/vtk 

The UV-CDAT VTK is behind VTK master from gitlab/vtk but the idea is that to get the latest changes in UV-CDAT sooner than later.

**Comment by danlipsa** [comment]
Should I bring the whole VTK master after I merge the PNG change or should I only cherry-pick the PNG change?

**Comment by aashish24** [comment]
@danlipsa please only cherry-pick the change. Post 2.4, we should update to VTK master and bring all of the minor fixes we made in UV-CDAT/VTK(uvcdat-master) into VTK master. @doutriaux1 does this sounds good to you?
