### ISSUE TITLE
Provide UI option to control labels spacing

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1677]

**Comment by aashish24** [comment]
@chaosphere2112 we will need this for the release 2.4

**Comment by chaosphere2112** [comment]
@aashish24 Yup, I'll make sure to get a PR submitted today.

**Comment by chaosphere2112** [comment]
@aashish24 ... Or maybe on Monday. Sorry, got caught up in other tasks today.

**Comment by aashish24** [comment]
No problem @chaosphere2112 , I understand. Thanks for the update, appreciate it.
