### ISSUE TITLE
Data is clipped in interactive mode

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/uvcdat#1720]
Further more, data is OK when saving a PNG but annotations are off.
Also, data is scaled differently in interactive mode compared with the PNG.

I used the following script provided by @aashish24 

#!/usr/bin/env python
import cdms2, cdutil, genutil
import vcs

if __name__ == '__main__':
    import sys
    cdmsfile = cdms2.open('~/build/uvcdat/install/share/uvcdat/sample_data/clt.nc')
    clt = cdmsfile('clt')
    clt = clt(latitude=(-90.0, 90.0),squeeze=1,longitude=(-180.0, 175.0),time=('1979-01', '1988-12'),)
    axesOperations = eval("{'latitude': 'def', 'longitude': 'def', 'time': 'def'}")
    for axis in list(axesOperations):
        if axesOperations[axis] == 'sum':
            clt = cdutil.averager(clt, axis='(%s)'%axis, weight='equal', action='sum')
        elif axesOperations[axis] == 'avg':
            clt = cdutil.averager(clt, axis='(%s)'%axis, weight='equal')
        elif axesOperations[axis] == 'wgt':
            clt = cdutil.averager(clt, axis='(%s)'%axis)
        elif axesOperations[axis] == 'gtm':
            clt = genutil.statistics.geometricmean(clt, axis='(%s)'%axis)
        elif axesOperations[axis] == 'std':
            clt = genutil.statistics.std(clt, axis='(%s)'%axis)
    canvas = vcs.init()
    gmIsofill = vcs.getisofill('a_robinson_isofill')
    args = []
    args.append(clt)
    gmIsofill.datawc_calendar = 135441
    gmIsofill.datawc_timeunits = 'days since 2000'
    gmIsofill.datawc_x1 = 1e+20
    gmIsofill.datawc_x2 = 1e+20
    gmIsofill.datawc_y1 = 1e+20
    gmIsofill.datawc_y2 = 1e+20
    gmIsofill.levels = [[1.0000000200408773e+20, 1.0000000200408773e+20]]
    gmIsofill.ext_1 = False
    gmIsofill.ext_2 = False
    gmIsofill.fillareacolors = [1]
    gmIsofill.fillareaindices = [1]
    gmIsofill.fillareastyle = 'solid'
    gmIsofill.legend = None
    gmIsofill.missing = 241
    gmIsofill.projection = 'robinson'
    gmIsofill.xaxisconvert = 'linear'
    gmIsofill.xmtics1 = ''
    gmIsofill.xmtics2 = ''
    gmIsofill.xticlabels1 = '*'
    gmIsofill.xticlabels2 = '*'
    gmIsofill.yaxisconvert = 'linear'
    gmIsofill.ymtics1 = ''
    gmIsofill.ymtics2 = ''
    gmIsofill.yticlabels1 = '*'
    gmIsofill.yticlabels2 = '*'
    kwargs = {}
    kwargs[ 'cdmsfile' ] = cdmsfile.id
    args.append( gmIsofill )
    canvas.plot( *args, **kwargs )
    fnm = "bad.png"
    canvas.png(fnm)
    canvas.interact()

Here is a screenshot of the interactive display:
![bad-interactive](https://cloud.githubusercontent.com/assets/6180727/11565140/9d5ccc18-99aa-11e5-8204-574c21077a38.png)
Here is the PNG file saved:
![bad](https://cloud.githubusercontent.com/assets/6180727/11565154/ab826960-99aa-11e5-9508-51a4ae16d48c.png)

**Comment by doutriaux1** [comment]
wow! What happened to the labels? Let me see if i can reproduce this.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 It seems that there is a rearrangement of the data/labels that does not happen when saving the PNG. Interactive mode goes through this phase as well and then it rearanges the graphics elements to end up with the clipped image. Do you know why the images are scaled differently?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 A workaround for the PNG not matching the interactive image is to generate
the PNG after the interactive image.

**Comment by doutriaux1** [comment]
but... the interactive is wrong anyway!

**Comment by danlipsa** [comment]
@doutriaux1 So, the scaling in the interactive image is wrong?

**Comment by danlipsa** [comment]
@doutriaux1 The image does look stretched. This means there is another bug besides the two bugs I fixed with my recent pull request.

**Comment by danlipsa** [comment]
@doutriaux1 @chaosphere2112 @aashish24 In interactive mode, the image stretches with the window size. Is this a feature or a bug? :-)

**Comment by doutriaux1** [comment]
@danlipsa in the "bad" png there is no cropping of the image on the right size. That part is correct. The stretching part is due to bad templating it's trying to fill the entire template.data area. Not too  worried about that. What I and @williams13 are worried about is the cropped section on the right side.

**Comment by danlipsa** [comment]
@doutriaux1 OK, In that case the commits I pushed should fix that. It is strange though that in interactive mode, the way your data looks depends on your window ratio.

**Comment by doutriaux1** [comment]
you can `fix` that  by passing `ratio="autot"` for regular projections not sure it works for projections, but if you know your desired aspect ratio (let's say 1) you can pass `ratio="1t"`

**Comment by aashish24** [comment]
> @doutriaux1 @chaosphere2112 @aashish24 In interactive mode, the image stretches with the window size. Is this a feature or a bug? :-)

to me it not desirable. I complained about that in the past to @doutriaux1 and would like to discuss this post 2.4. Distorting a projected data looks just odd to me.

**Comment by doutriaux1** [comment]
that's why we have ratio="autot" @aashish24 but figuring out the desired aspect ratio is no easy task either. It's fairly easy for the whole globe but as soon as you start to look at region of the globe it gets tricky.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I will solve this in two steps. It seems that synchronizing the PNG with the interactive mode screws up animation tests, so I will first deal with the clipping issue, merge this and then address the sync issue.

**Comment by danlipsa** [comment]
We still need to synchronize the PNGs with the interactive mode screen

**Comment by danlipsa** [comment]
I filed a new issue for PNG versus interactive screen mode differences.
https://github.com/UV-CDAT/uvcdat/issues/1740
