### ISSUE TITLE
canvas.png writes a PNG with labels off if bg=0

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/uvcdat#1740]
Running this test
[test2.txt](https://github.com/UV-CDAT/uvcdat/files/65625/test2.txt)
produces
![bad](https://cloud.githubusercontent.com/assets/6180727/11874925/0eff8468-a4b0-11e5-959e-5c3d8b778f14.png)
Uncommenting the line that sets bg to 1 fixes the problem.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Is this important? Should we fix it before the release?

**Comment by doutriaux1** [comment]
actually yes! Lots of people run things in batch mode. Is it going to be long? Let's see if we can get the other PR in before we move to this one!

**Comment by doutriaux1** [comment]
@jbeezley do you think you can help with this one? Looks like it's `bugging` you as well.

**Comment by jbeezley** [comment]
Probably not, I know almost nothing about VTK.

**Comment by doutriaux1** [comment]
Is there such a person at Kitware? :wink: No worries.

**Comment by chaosphere2112** [comment]
@danlipsa @doutriaux1 This is the issue that I filed ages ago with VTK; we have it as #1148.

**Comment by aashish24** [comment]
@danlipsa I can look into it after I finish my sprint tasks let me know.

**Comment by aashish24** [comment]
thanks @chaosphere2112 for the reference.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 @chaosphere2112 I looked at this briefly when I filed is. The reason why the labels are off seems to be that  the display happens on a very large screen which is not available if bg=0. There these events that have to be dealt with properly: ModifiedEvent and ConfigureEvent. This is in VTKPlots.py

That is not to say that there is not a VTK bug somewhere as well :-) I have not seen Sam's bug report at all when I looked at this.

**Comment by danlipsa** [comment]
The case when you don't specify a window size (as the test is written) has been fixed by:
https://github.com/UV-CDAT/uvcdat/pull/1821
When we specify a window size bigger than the screen size:
x=vcs.init()
x.open(4000, 3000)
we still produce the wrong result.

**Comment by danlipsa** [comment]
This might be fixed when we switch VTK to OpenGL2 - a new, much faster, rendering backend in VTK

**Comment by doutriaux1** [comment]
@danlipsa is that coming soon?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This new backend is the default in VTK and ParaView now. So, we could bite the bullet and switch UVCDAT to it soon. I think there are some changes to export to PS/PDF which might cause some issues The new backend requires OpenGL: >= 3.2 and Mesa >= 11.2 I think. If one has a hardware driver there should not be any problems. Mesa might need a rebuild as certain distributions have older versions.

**Comment by doutriaux1** [comment]
@danlipsa we build our own mesa anyway so it shouldnt be an issue.

**Comment by danlipsa** [comment]
@doutriaux1 Sounds good. See
https://blog.kitware.com/messing-with-mesa-for-paraview-5-0vtk-7-0/
for some options for building the new mesa.

**Comment by aashish24** [comment]
There should be a new Mesa out so hopefully instead of the patch (which I believe the blog mentiond) we can try it directly.

**Comment by durack1** [comment]
@danlipsa: @chaosphere2112 @durack1 @doutriaux1 This works with vcs SHA f6a88670f89bcbd476c106c6d5695902581ca565 from Apr 5.
