### ISSUE TITLE
Meshfill plot does not wrap for bounds outside 0-360

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1746]

**Comment by aashish24** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/blob/duplicate-longitude-wrap/baselines/vcs/test_vcs_animate_projected_meshfill_mollweide.png

**Comment by aashish24** [comment]
ref: doWrap method in vcs2vtk.py

**Comment by doutriaux1** [comment]
@danlipsa is this fixed ?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I have a fix in the works. I should push it today. See also issue https://github.com/UV-CDAT/uvcdat/issues/1754. Not sure why but this issue does not show up in my list of issues even if it is assigned to my.

**Comment by danlipsa** [comment]
I'll close this as we have https://github.com/UV-CDAT/uvcdat/issues/1754
