### ISSUE TITLE
Option to change colorscale for each frame when animating?

### ISSUE THREAD

**Issue by cameronsmith1** [UV-CDAT/uvcdat#1750]
When animating plots (eg a_boxfill), UVCDAT currently uses the colorscale for the first frame for all the subsequent frames.   Sometimes this is the right choice.  However, sometimes the nature of the data is such that it is better to change the colorscale for each frame.  
Is there an option for this?   If not, I recommend such an option is added.

**Comment by doutriaux1** [comment]
@cameronsmith1 if your graphic method does NOT explicitly sets these levels then yes UV-CDAT looks at max/min of the whole dataset and apply it for all frames. If you wish to impose some levels you first need to edit the graphic method to do so and THEN run the animation.
