### ISSUE TITLE
openssl cmake error on RHEA

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1751]
```
Could not detect matplotlib, /lustre/atlas/world-shared/cli900/sw/rhea/uvcdat/2016-01-04brian_testbed/bin/python
CMake Error at CMake/cdat_modules/openssl_pkg.cmake:6 (get_filename_component):
  get_filename_component unknown component DIRECTORY
Call Stack (most recent call first):
  CMakeLists.txt:482 (include)
```

**Comment by jbeezley** [comment]
This is probably due to an old version of CMake.  The `DIRECTORY` component was added in 2.8.12. This could be cause to enforce this via the [`cmake_minimum_required`](https://github.com/UV-CDAT/uvcdat/blob/master/CMakeLists.txt#L2) command rather than issuing a depreciation warning.

**Comment by doutriaux1** [comment]
yes I figured it probably was. I commented out the line and it seems to be working ok.
