### ISSUE TITLE
test_vcs_animate_projected_meshfill_mollweide.png is not wrapped

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/uvcdat#1754]
Data is between -40 to 361. It should be wrapped between 0 and 360.

See the current baselines which are attached next.

**Comment by danlipsa** [comment]
![test_vcs_animate_projected_meshfill_mollweide](https://cloud.githubusercontent.com/assets/6180727/12121686/97f29e10-b3a4-11e5-8396-8864069d758d.png)
![test_vcs_animate_projected_meshfill_lambert](https://cloud.githubusercontent.com/assets/6180727/12121685/97ef715e-b3a4-11e5-882d-e091b6a8e171.png)

**Comment by doutriaux1** [comment]
thanks @danlipsa for looking into this. While you are at it you may be able to also fix #1265 it might be the same issue (look at comments I made at the end of this issue)

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Looking at the code it seems that vcs2vtk.doWrap works on poly data in lon/lat space. So it won't work on the mollweide or any other geographic projection. I want to wrap dirrectly the data in genGrid. Do you see any problem with this?

**Comment by danlipsa** [comment]
I'll have to cut cells as they span the wrap boundaries.

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat/pull/1778
