### ISSUE TITLE
cdscan giving error in UVCDAT 

### ISSUE THREAD

**Issue by somanathmoharana** [UV-CDAT/uvcdat#1761]
Hi,
 I installed uvcdat in my system from the source tar but I am facing some issues while running cdscan.
Finding common directory ...
Traceback (most recent call last):
  File "./cdscan", line 1680, in <module>
    main(sys.argv)
  File "./cdscan", line 840, in main
    firstpath = augmentedArgs[0][len(directory):]
IndexError: list index out of range

What i should do to resolve this ?

**Comment by doutriaux1** [comment]
@somanathmoharana cdscan needs to be sent a list of files you need to scan (usually something like *.nc)

example:
`./cdscan -x my_scanned_file.xml *.nc`

**Comment by somanathmoharana** [comment]
Thanks @doutriaux1 .Now it's working fine
