### ISSUE TITLE
lambert proj appears to be broken??

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1763]
old lambert over north america:

```
p=x.createprojection()
p.type = "lambert"
b=x.createboxfill()
b.projection=p
x.plot(s(longitude=(-120,-20),latitude=(20,60)),b)
```
![lambert](https://cloud.githubusercontent.com/assets/2781425/12148557/ef36598c-b453-11e5-9459-c8322e4176f7.png)

**Comment by doutriaux1** [comment]
new vcs
![lambert_bad](https://cloud.githubusercontent.com/assets/2781425/12148607/3a1177ca-b454-11e5-9669-0d6acd25d0b8.png)

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa if you beat me to it please feel free to fix it.

**Comment by doutriaux1** [comment]
ok making progress it looks like gctp was smarter than proj4 we need to set all parameters manually or it will not work
```
p.centralmeridian = -80
p.originlatitude=0
p.standardparallel1 = 20
p.standardparallel2=60
```

**Comment by doutriaux1** [comment]
fixed in 2.4.0 but on macs exposes proj4 issue listed @ #1777

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Do we need to pass +over to the lambert projection (or to polar (non gctp))? What I want to get at, is a test case, where we need to pass +over, it works on most machines but it does not work on certain macs and annie. If we don't have that we'll spend time to fix something that we don't really need. Maybe for these projections, +over does not work consistently because people don't need that so nobody tested for that.

**Comment by doutriaux1** [comment]
it's worth trying. I will do that now.

**Comment by doutriaux1** [comment]
@danlipsa I don't think that's the issue, looking at the code:
```python
no_over_proj4_parameter_projections = round_projections+["aeqd", "lambert conformal c"]
```
Then we have a section in vcs2vtk.py that does:
```python
        if projection.type not in no_over_proj4_parameter_projections:
            pd.SetOptionalParameter("over", "true")
        else:
            pd.SetOptionalParameter("over", "false")
```

So obviously we're not trying `over` on lambert and it still fails on macs.

**Comment by doutriaux1** [comment]
i think the issue could be coming from:
```python
            setProjectionParameters(pd, projection)
```

**Comment by danlipsa** [comment]
@doutriaux1 What is the test that is failing on macs? Is it failing on annie as well?

**Comment by doutriaux1** [comment]
only on mac, if you look at CMakeList.txt it is commented out if it's an apple. test_vcs_lambert I believe is the name. I "think" it passes on annie, but it could also be luck :wink:

**Comment by danlipsa** [comment]
Interesting. I tried this test on my mac - which had problems with +over and polar non gctp and it passes. I will create a branch where I activate this test and see where it fails.
