### ISSUE TITLE
proj4 acting up on macs and ubuntu mesa

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1777]
polar (non gctp) and lambert exhibit this behaviour best.

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat/pull/1790

**Comment by danlipsa** [comment]
The new VTK brought in by
https://github.com/UV-CDAT/uvcdat/pull/1827
has a fix for this issue.
