### ISSUE TITLE
Update VTK

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1784]

**Comment by aashish24** [comment]
My VTK merge request: https://gitlab.kitware.com/vtk/vtk/merge_requests/1206

**Comment by aashish24** [comment]
Still need to
- [ ] PROJ4 @danlipsa is working on that
- [ ] Get FFMPEG fixes - @aashis24 will push a branch for it

**Comment by aashish24** [comment]
FFMPEG merge request: https://gitlab.kitware.com/vtk/vtk/merge_requests/1237

**Comment by aashish24** [comment]
@danlipsa @doutriaux1

**Comment by doutriaux1** [comment]
@aashish24 can you please run the PR on github as well?

**Comment by aashish24** [comment]
@doutriaux1 do you mean that have a PR to update VTK in UVCDAT/VTK?
