### ISSUE TITLE
vcs_test_init_open_sizing fails on small monitors

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1792]
When I run  vcs_test_init_open_sizing  on a small laptop screen, the test fails. I believe this is the same issue that @williams13 ran into when testing the new build. I'll see what I can dig up.

**Comment by aashish24** [comment]
thanks @chaosphere2112 I added it to the ready queue.

**Comment by durack1** [comment]
@aashish24 is the `0 - backlog` through `4 - Done` the way you plan to better label issues/PRs? Is this documented somewhere?

**Comment by chaosphere2112** [comment]
@durack1 They're a side effect of https://huboard.com/UV-CDAT/uvcdat , which we're trying out for project management.
