### ISSUE TITLE
ratio="autot" fails to correctly generate the initial ratio

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1795]
If you plot something with `ratio="autot"` as the very first action you take with a canvas, the plot defaults to using the default window size, rather than the size that the canvas will actually have. This is because the call to determine the ratio happens *prior* to any calls to `createRenWin()` in the backend, so default values are retrieved using the `canvasinfo()` function.

Any future plots (or ones triggered by `canvas.update()`) will be the correct proportions.

**Comment by chaosphere2112** [comment]
I've sort-of got a fix for this worked out; it needs work, though. I'm running a full test suite on it and sending it out the the dashboard.

**Comment by chaosphere2112** [comment]
@doutriaux1 https://open.cdash.org/viewTest.php?onlyfailed&buildid=4197349 Getting closer...

**Comment by doutriaux1** [comment]
looks like the diags doesn't set the bg dims and throws the tests off.

**Comment by chaosphere2112** [comment]
Does diags use Multi? Because almost all of the multi tests failed as well

**Comment by chaosphere2112** [comment]
@doutriaux1 So Multi was using "x.portrait" and "x.landscape", which triggered a call to canvasinfo prior to plot, which meant that bg wasn't set. I'll wager it's something similar in the diagnostics.

https://open.cdash.org/viewTest.php?onlyfailed&buildid=4197441

**Comment by doutriaux1** [comment]
@chaosphere2112 , according to @mcenerney1 diags are using Multi

**Comment by chaosphere2112** [comment]
Going to open a PR for this, though it's not quite ready for release. Changed milestone to 2.4.1.

**Comment by doutriaux1** [comment]
@chaosphere2112 I changed the milestone to 2.6 if it makes it to 2.4.1 ok, but 2.4.1 is a uvcmetrics targeted release.

**Comment by chaosphere2112** [comment]
@doutriaux1 :+1:

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 Since this is a pretty minor issue, I'm going to backburner it for now while I get my GUI on. I'll come back to the PR in a month.

**Comment by aashish24** [comment]
Roger that @chaosphere2112

**Comment by danlipsa** [comment]
@chaosphere2112 This seems to work in my tests. Can you try it with the master branch . I fixed something that sounds like your problem in
https://github.com/UV-CDAT/uvcdat/pull/1896

**Comment by aashish24** [comment]
@doutriaux1 can you confirm if this is fixed?

**Comment by chaosphere2112** [comment]
Works!
