### ISSUE TITLE
2.4.1 Tagging

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1807]
- [ ] Validate version info is correctly written (UV-CDAT version should be `2.4.1`)
- [ ] Prepare and publish release notes.
- [x] Update dependencies so that checkout tag points are set and match `2.4.1` release: `CMOR_BRANCH="uvcdat-2.4.1"; LIBCDMS_BRANCH="uvcdat-2.4.1"; VISTRAILS_BRANCH="uvcdat-2.4.0"; VTK_BRANCH="uvcdat-2.4.1"; UVCMETRICS_BRANCH="uvcdat-2.4.1"`
- [x] Update `README.md` with updated `Stable version` info (should be `2.4.1`)
- [x] Set `2.4.1` tag point for UV-CDAT/uvcdat repo
- [ ] Obtain Zenodo DOI
- [ ] Finalise `README.md` with updated `Zenodo DOI` info
- [ ] Move `2.4.1` tag point to new commit
- [ ] Update wiki so correct tag points (`2.4.1`) are noted for build notes: [linux](https://github.com/UV-CDAT/uvcdat/wiki/Build-on-Linux), [MacOS X](https://github.com/UV-CDAT/uvcdat/wiki/Build-on-Mac-OS-X) etc

**Comment by durack1** [comment]
Closed by 232870dfe4c5afe8c3d24afbf292c856335c1bd7
