### ISSUE TITLE
2.6 Tagging

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1808]
- [ ] Validate version info is correctly written (UV-CDAT version should be `2.6.0`)
- [ ] Prepare and publish release notes.
- [ ] Update `README.md` with updated `Stable version` info (should be `2.6.0`)
- [ ] Set `2.6.0` tag point for UV-CDAT/uvcdat repo
- [ ] Obtain Zenodo DOI
- [ ] Finalise `README.md` with updated `Zenodo DOI` info
- [ ] Move `2.6.0` tag point to new commit
- [ ] Update wiki so correct tag points (`2.6.0`) are noted for build notes: [linux](https://github.com/UV-CDAT/uvcdat/wiki/Build-on-Linux), [MacOS X](https://github.com/UV-CDAT/uvcdat/wiki/Build-on-Mac-OS-X) etc
- [ ] After `2.6.0` tag point set, reset all `master` checkout tag points to point back to `uvcdat-master` tags.
- [ ] Increment `uvcdat-master` to `2.7.0` (odd minor [major.minor.patch] number indicating development version)

**Comment by durack1** [comment]
@dnadeau4 this may be useful for `CMOR` tagging - just outlying the step-by-step

**Comment by durack1** [comment]
@doutriaux1 I assume this should be closed - as `2.6` is tagged and out?

**Comment by durack1** [comment]
@doutriaux1 the master README.md is still showing `2.4.1` is latest along with the old `2.4.1` DOI..

**Comment by durack1** [comment]
Closed by 91141a6bc512e6b0baff37f980f99b7f43dfeef8
