### ISSUE TITLE
Fix projected click

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1811]
Once #1806 goes into master.

**Comment by aashish24** [comment]
Ref: #1800

**Comment by danlipsa** [comment]
This was partially fixed by
https://github.com/UV-CDAT/uvcdat-testdata/pull/117/commits
We still have to implement this for point datasets.

**Comment by danlipsa** [comment]
This implements point info for point datasets.
https://github.com/UV-CDAT/uvcdat/pull/1966
