### ISSUE TITLE
Update UV-CDAT to use buildbot/kwbot

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1835]

**Comment by sankhesh** [comment]
Sub-tasks:

- [ ] Setup a separate buildbot instance with the existing KWRobot instance to listen to merge requests on https://gitlab.kitware.com/UV-CDAT/uvcdat
- [ ] Setup the current version of GitRobot on a VM with a test deployment of Gitlab and a test project.
- [ ] Use the infrastructure setup in the previous step as a guide for development of the Github version of GitRobot.
- [ ] Once, GitRobot works with GitHub, make Kitware's fork of Buildbot work with Github.
- [ ] Deploy GitRobot + Buildbot on a sysadmin allocated machine in DMZ such that Github can send event notifications to it.

**Comment by sankhesh** [comment]
The buildbot + GitRobot system has been deployed with @cdatrobot doing content checks and scheduling tests. Documentation can be found here:

- [Buildbot](https://github.com/UV-CDAT/uvcdat/wiki/Buildbot)
- [Add a build slave](https://github.com/UV-CDAT/uvcdat/wiki/add-a-buildslave)
