### ISSUE TITLE
animation save does not preserve the colormap

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1845]
```python
import vcs
import cdms2
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt")
x=vcs.init()
x.setcolormap("AMIP")
x.plot(s)
x.interact()
```

**Comment by doutriaux1** [comment]
@lee1043 does this work for you?

**Comment by lee1043** [comment]
@doutriaux1 Colormap changes immediately after I click "save animation". Bluemarble image is also disappearing.

**Comment by doutriaux1** [comment]
@lee1043 yes I would expect the bluemarble to disappear. I'll take a look at the colormap issue

**Comment by doutriaux1** [comment]
@chaosphere2112 did you fix this? I can't reproduce.

**Comment by doutriaux1** [comment]
```python
import vcs
import cdms2
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt",slice(0,12))
x=vcs.init()
gm = x.createisofill()
x.setcolormap("bl_to_darkred")
x.plot(s,gm)
x.animate.create()
x.animate.run()
```

works perfectly as well for me.

**Comment by chaosphere2112** [comment]
@doutriaux1 Looks like @lee1043 was doing it through my interaction bits, rather than from code. Must be something dumb I did in there.

**Comment by doutriaux1** [comment]
nope i tried that too and it works perfectly.

**Comment by chaosphere2112** [comment]
K. Weird.

**Comment by doutriaux1** [comment]
it is the `save` that fails, looking into it now. Thanks @lee1043
