### ISSUE TITLE
Taylor diagram capability needs more expansive example or documentation

### ISSUE THREAD

**Issue by gleckler1** [UV-CDAT/uvcdat#1846]
Having the Taylor Diagram capability in UV-CDAT is a big advantage.  The example I have found (http://uv-cdat.github.io/cdat-site/taylordiag.html) provides a good start but requires a few more basic things to make is useful.   The most important is explaining how to control where the symbol legends (Td.Marker.id) are placed which are by default placed centered on the symbol.   A good example is at http://www.arm.gov/science/highlights/images/R00424_2.jpg

A good solution would be to expand upon http://uv-cdat.github.io/cdat-site/taylordiag.html and or put it in the gallery.

**Comment by durack1** [comment]
@chaosphere2112 could you take a look at this and provide some feedback? I think it'd be a nice new feature to prioritise, and UV-CDAT should "own" this plot format

**Comment by durack1** [comment]
@gleckler1 pinging you on this

**Comment by gleckler1** [comment]
@durack1 11 days...  maybe this is not be the right path to support?   I am seeking guidance on basically one line of code.

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 any chance you could answer the queries of @gleckler1 or give a likely timeline/path forward?

**Comment by doutriaux1** [comment]
@gleckler what is it you need really? By reading the issue it seems you just want to add more taylor diagrams to the gallery, that's not a high priority isse for UV-CDAT and you shouldn't expect anything to happen on this right away.

**Comment by gleckler1** [comment]
@chaosphere2112 @doutriaux1 Neither doc provides an example of how to control the location of the legend as in http://www.arm.gov/science/highlights/images/R00424_2.jpg where the legend is left justified and to the right (outside) of the polar plot.

**Comment by doutriaux1** [comment]
that's because I don't think it does it, you will have to construct the legend by hand

**Comment by gleckler1** [comment]
@doutriaux1 OK, we can use matplotlib solution

**Comment by durack1** [comment]
@gleckler1 there are many matplotlib solutions available: 
https://gist.github.com/ycopin/3342888
https://www.google.com/search?q=matplotlib+taylor+diagram

**Comment by doutriaux1** [comment]
@durack1 the issue is not the taylor daigram itself, just that @gleckler1 wants a customized legend.
