### ISSUE TITLE
world coordinate do not respect datawc_x1/x2 

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1849]
@danlipsa we need urgently to fix the datawc_x1/x2/y1/y2 issue this affects I isolated the issue (in meshfill at least which appear in: https://github.com/PCMDI/pcmdi_metrics/issues/296 ) to be coming from: https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/vcsvtk/meshfillpipeline.py#L53

Looking at the issue above when runnig it with the EXACT same template and datawc_x1/x2 4 times but slightly different "mesh" coordinatesI get:
```
MESH: -0.5 15.5 0.0 9.5
MESH: -0.5 15.0 -0.5 9.5
MESH: -0.5 15.5 -0.5 9.0
MESH: 0.0 15.5 -0.5 9.5
```
which leads to the ugglyness in the issues (ticks offsets, triangle on top of each others)

Another example would be:

```python
import cdms2
import vcs
f=cdms2.open(vcs.sample_data+"/sampleCurveGrid4.nc")
s=f("sample")
x=vcs.init()
m=x.createmeshfill()
m.datawc_x1 = -20
m.datawc_x2 = 20
m.datawc_y1 = -20
m.datawc_y2 = 20
x.plot(s,m)
x.png("bad")
```

png, far from being the requested bounds

![bad](https://cloud.githubusercontent.com/assets/2781425/13193372/06eaa826-d72c-11e5-91e9-699b7dd20f22.png)

**Comment by danlipsa** [comment]
@doutriaux1 Could I get the original script/data from https://github.com/PCMDI/pcmdi_metrics/issues/296? I have seen and solved something similar for plots of boxfill + vector. There, the bounds for boxfill data were slightly larger than the bounds for vector the vector which resulted in similar duplication of labels.

**Comment by danlipsa** [comment]
Does this fix the issue?
https://github.com/UV-CDAT/uvcdat/pull/1855
