### ISSUE TITLE
Fix tag 2.5

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1850]
It seems that its on the wrong commit. 

@doutriaux1 @williams13  I will fix it soon. Thanks for reporting it.

**Comment by dnadeau4** [comment]
@aashish24 can we use calibrated language in these issues please. To me "soon" means promptly, and not many weeks or greater than one month later.

**Comment by aashish24** [comment]
@dnadeau4 my bad. I will fix it today.

**Comment by aashish24** [comment]
So I looked into it few days ago and didn't find anything wrong. It is on the master branch and seems to be on the right SHA. I am closing it now and will re-open it again once I have more information.
