### ISSUE TITLE
Change the default in uvcdat so that data is not deformed/stretched

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/uvcdat#1880]
By default, images in uvcdat are stretched to fit the window. This is highly unusual in scientific visualization. Continents/and projected datasets don't have the correct shape. In my opinion images don't look professional.

**Comment by danlipsa** [comment]
@doutriaux1 Any reasons why images are deformed? What was the option that triggers vcs to show un-deformed images? Can we get you on board with this? :-)

**Comment by doutriaux1** [comment]
@danlipsa I think it is mainly for historical reason. Also the "stretching" only really occurs for plots with continents (for a time/lev plot for example there is no correct aspect ratio). @taylor13 and I implemented the `ratio='autot'` solution to make plots pretty for lat/lon plots.

**Comment by doutriaux1** [comment]
anyhow turning "on" the auto ratio all the time will break existing script. I think that the main reason why it's not on. If we turn it on by default we will need to make sure that we can turn it off again to ensure users can get the old functionality back.

**Comment by danlipsa** [comment]
@doutriaux1 Do you mean we'll need to upgrade existing baselines? It makes sense to keep the option to get the old behavior (stretching) around for compatibility reasons and also to enable the correct ratio only for lat/lon plots.

**Comment by doutriaux1** [comment]
Yes we will probably need to update our baselines as well, that's not such a big deal.

**Comment by danlipsa** [comment]
@doutriaux1 What is the existing script that is going to be broken by turning on auto ratio? Can we fix that? I think images in uvcdat would look a lot nicer. I look forward to seeing the correct shapes for various projections we have and the correct continent shapes as the go through various projections. I 'volunteer' to work on this. @aashish24  is already on board.

**Comment by doutriaux1** [comment]
@danlipsa I don't know specifically but we have many many users here that have been using vcs to plot for many years. Some of these will have "autot" in them if the user added it manually, but most of the others will not. Granted they will probably have manually tweaked their templates to do their own `autot` so it might be very minimal, but the point is some script will break/look different and the users will complain that `vcs is broken`. I think it's ok if w emake sure that we can tell them `simply add ratio='off'` or similar  to fix their issue. Do you get my point?

**Comment by danlipsa** [comment]
@doutriaux1 Makes sense. We should definitely communicate this very clearly and make sure users can revert to the old behavior if they want to.

**Comment by danlipsa** [comment]
@doutriaux1 It turns out that autot is passed to plots from the interface, but for some reason the plots don't follow that. vcs_test_autot_axis_titles works fine though. I'll take a close look at this.

**Comment by danlipsa** [comment]
This is the same as https://github.com/UV-CDAT/uvcdat/issues/1795

**Comment by danlipsa** [comment]
The pull request is:
https://github.com/UV-CDAT/uvcdat/pull/1896

**Comment by danlipsa** [comment]
ratio=autot is only a default in uvcdat interface. At the plot() level we have the same default as before for backward compatibility.
