### ISSUE TITLE
polar plot boxfill cannot be plotted with north pole up

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1886]
```python
gm = x.createboxfill()
x.plot(s(latitude=(90,-90)),gm)
x.plot(s(latitude=(-90,90)),gm)
```
produces the same plot with souh pole at center

**Comment by aashish24** [comment]
weird :cry:

**Comment by doutriaux1** [comment]
also:

```python
gm.datawc_y2 = -90
gm.datawc_y1 = 90
```
does not do the job.

**Comment by danlipsa** [comment]
@doutriaux1 What is the rule here? if y1 < y2 you look from the south pole otherwise you look from the north pole? What if you have latitude [80, 90] do still look from the south pole? Thanks.

**Comment by doutriaux1** [comment]
@danlipsa the rule is the y1 is the center one. so if y1<y2 then south pole centered, if y1>y2 then north pole centered

**Comment by doutriaux1** [comment]
```python
x.plot(s(latitude=(80,90)),b)
```
![80_90](https://cloud.githubusercontent.com/assets/2781425/14158371/87d6b6e2-f684-11e5-9df3-bba1cf47c269.png)

**Comment by doutriaux1** [comment]
```python
x.plot(s(latitude=(90,80)),b)
```
![90_80](https://cloud.githubusercontent.com/assets/2781425/14158386/9df7123c-f684-11e5-96a0-3251549136e1.png)

**Comment by danlipsa** [comment]
@doutriaux1 So, you just look at y1. If y1 > 0 it is north pole centered, if y1 < 0 it is south pole centered. Is this the rule? Does this mean that (80, 90) is the same as (90, 80)?

**Comment by danlipsa** [comment]
@doutriaux1 What if y1 is 0?

**Comment by doutriaux1** [comment]
@danlipsa no I just look at y1 vs y2 see examples above

**Comment by danlipsa** [comment]
@doutriaux1 Sorry, I don't get the rule. Looking at the examples:
(80, 90) . Looks like the view is from -90. (south pole)

(90, 80). Looks like the view is from 90. (north pole)
So we are back to my original rule: if y1 < y2 you look from the south pole otherwise you look from the north pole? 

> the rule is the y1 is the center one. so if y1y2 then north pole centered
For (80, 90). 80 is the center one. What does this mean? Is the view form 90 or -90? It seems these are the only possibilities for polar projection.

**Comment by doutriaux1** [comment]
@danlipsa you are right there are only two possibilities North Pole or South Pole Centered.
y1<y2 -> South Pole
y1>y2 -> North Pole

**Comment by danlipsa** [comment]
@doutriaux1 So we have the following algorithm:
y1 <= y2 -> South Pole
y1 > y2   -> North Pole

**Comment by doutriaux1** [comment]
exactly

**Comment by doutriaux1** [comment]
if y1==y2 we may want to error exit

**Comment by danlipsa** [comment]
Great. Thanks Charles!

**Comment by danlipsa** [comment]
Fix on:
https://github.com/UV-CDAT/uvcdat/pull/1904

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat/pull/1904
