### ISSUE TITLE
Evaluate conda for packaging uvcdat

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1889]

**Comment by dnadeau4** [comment]
conda.anaconda.org/uvcdat will be the website for uvcdat.   I still don't have access to uvcdat organization, so I put all packages (linux-64) in my personal repository for now.  

https://conda.anaconda.org/nadeau1/

**Comment by dnadeau4** [comment]
https://conda.anaconda.org/uvcdat/

**Comment by aashish24** [comment]
@dnadeau4 @doutriaux1 has forked your repo here: https://github.com/UV-CDAT/conda-recipes

thanks @dnadeau4

**Comment by aashish24** [comment]
Open issues:

* Running regression tests using Conda 
* Submission of tests and coverage result to dashboards 
* Offline build - I believe this should be possible as conda has offline mode
* Building on HPC systems - Use of system MPI (Mostly for conda its about full control)
* Packaging (RPM / DMZ) - I don't not believe that conda can do this but not sure. 

It is possible that I missed something important here. Please feel free to update as needed.

**Comment by doutriaux1** [comment]
@aashish24 please do not open issues there yet, it's still only for @dnadeau4 and I.

**Comment by aashish24** [comment]
> @aashish24 please do not open issues there yet, it's still only for @dnadeau4 and I.

@doutriaux1 why do you want to make it private?

**Comment by doutriaux1** [comment]
@aashish24 I'm too poor for this. You need a paying account for private repos.

**Comment by doutriaux1** [comment]
@aashish24 no need for private anyway. Just too early for anybody to start pushing issues, we know it's still all broken.

**Comment by aashish24** [comment]
> @aashish24 no need for private anyway. Just too early for anybody to start pushing issues, we know it's still all broken.

Sure, thanks @doutriaux1
