### ISSUE TITLE
Cleanup installation scripts in UVCDAT

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1890]
These are scripts under installation directory.

**Comment by doutriaux1** [comment]
most of this will disappear when going to conda.

**Comment by aashish24** [comment]
@doutriaux1 these are the scripts inside the packages (setup.py) stuff.  I don't think that conda will replace them. May be you are thinking runtime scripts.

**Comment by doutriaux1** [comment]
@aashish24 what I meant is that I will do the cleaning as I move to conda.

**Comment by aashish24** [comment]
Sounds good @doutriaux1. I still see as a separate issue (meaning that conda vs cleaning the scripts in general which could be invoked by pip, cmake or conda). Feel free to link them if thats better.

**Comment by durack1** [comment]
@doutriaux1 @aashish24 while you're at it https://github.com/UV-CDAT/uvcdat/issues/788 and https://github.com/UV-CDAT/uvcdat/issues/1354 should also be wrapped in.. There used to be a couple of PRs that were closed attempting to solve these issues..

**Comment by doutriaux1** [comment]
@durack1 do not bother it all goes away when we switch to conda
