### ISSUE TITLE
Boxfill legend incorrect when there are fewer colors than levels

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1894]
When you plot a boxfill and use the `color_1` and `color_2` attributes (but leave `level_1` and `level_2` alone), the legend doubles up for the last level color. Also, the labeling on the legend is excessive (we probably don't need 10+ labels when there are only 4 levels).

```python
import vcs, cdms2
f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")
x = vcs.init()
box = vcs.createboxfill()
# Set them to the obnoxious end of the colormap so we can see the steps between each color
box.color_1 = 242
box.color_2 = 246
x.plot(s, box)
```

results in:

![out](https://cloud.githubusercontent.com/assets/718512/14052964/7eeb0828-f28b-11e5-9ac0-67036cd0c2cb.png)

I've got a PR incoming to fix this.

**Comment by doutriaux1** [comment]
@chaosphere2112 ia that finished?

**Comment by chaosphere2112** [comment]
@doutriaux1 I've been waiting for feedback from you and @aashish24 for 2 weeks
