### ISSUE TITLE
uvcdat interface you cannot switch ratio=autot on and off. It stays always on.

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/uvcdat#1900]
In the interface choose 'configure current plot' then '<plot> World Coordinates and Axes' then 'Aspect Ratio' uncheck 'Auto (lat/lon)' then push Apply. The plot is redrawn the same way and Auto is still checked.

**Comment by danlipsa** [comment]
@chaosphere2112 Please take a look at the issue after my ratio=autot branch gets merged.
https://github.com/UV-CDAT/uvcdat/pull/1896

**Comment by chaosphere2112** [comment]
@danlipsa Old GUI is in maintenance mode; crashing bugfixes only.

**Comment by danlipsa** [comment]
@chaosphere2112 Where is the new gui? Very interested to play with it.

**Comment by chaosphere2112** [comment]
Still very much under construction, but it's at UV-CDAT/cdatgui
