### ISSUE TITLE
Build error with all

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1907]
While building uvcdat with 
cmake ~/uvcdat -DCMAKE_INSTALL_PREFIX=/usr/local/uvcdat/04_04_16 -DCDAT_BUILD_MODE=ALL
I get the following 

 configure: WARNING: 'missing' script is too old or missing

  configure: error: in `/Users/mcenerney1/build_04_04_16/build/proj4':

  configure: error: C compiler cannot create executables

  See `config.log' for more details

  Config Errors detected:

  

  

  CMake Error at
  /Users/mcenerney1/build_04_04_16/CMake/cdatmpi_configure_step.cmake:19
  (message):

    Error in config

**Comment by danlipsa** [comment]
@mcenerney1 Can you post config.log as well? Do a 'find . -name config.log' in your home directory. Seems like a write permission error. Maybe you built the code using sudo in the past.

**Comment by mcenerney1** [comment]
I don't think I used sudo. 
[mcenerney1ml:~/xxxxx] mcenerney1% ls -l build/proj4/config.log
-rw-r--r--  1 mcenerney1  75327  10228 Apr  4 13:14 build/proj4/config.log
Here's the content.

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by PROJ.4 Projections configure 4.9.2, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ configure --prefix=/usr/local/uvcdat/xxxxx/Externals/proj4

## --------- ##
## Platform. ##
## --------- ##

hostname = mcenerney1ml.llnl.gov
uname -m = x86_64
uname -r = 14.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 248 tasks, 1039 threads, 8 processors
Load average: 5.57, Mach factor: 2.54
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/uvcdat/xxxxx/Library/Frameworks/Python.framework/Versions/2.7/bin
PATH: /usr/local/uvcdat/xxxxx/Externals/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /opt/X11/bin
PATH: /Library/TeX/texbin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2318: checking for a BSD-compatible install
configure:2386: result: /usr/bin/install -c
configure:2397: checking whether build environment is sane
configure:2452: result: yes
configure:2490: WARNING: 'missing' script is too old or missing
configure:2603: checking for a thread-safe mkdir -p
configure:2642: result: ./install-sh -c -d
configure:2649: checking for gawk
configure:2679: result: no
configure:2649: checking for mawk
configure:2679: result: no
configure:2649: checking for nawk
configure:2679: result: no
configure:2649: checking for awk
configure:2665: found /usr/bin/awk
configure:2676: result: awk
configure:2687: checking whether make sets $(MAKE)
configure:2709: result: yes
configure:2738: checking whether make supports nested variables
configure:2755: result: yes
configure:2881: checking whether to enable maintainer-specific portions of Makefiles
configure:2890: result: no
configure:2918: checking for style of include used by make
configure:2946: result: GNU
configure:3017: checking for gcc
configure:3044: result: mpicc
configure:3273: checking for C compiler version
configure:3282: mpicc --version >&5
configure: line 3284: mpicc: command not found
configure:3293: $? = 127
configure:3282: mpicc -v >&5
configure: line 3284: mpicc: command not found
configure:3293: $? = 127
configure:3282: mpicc -V >&5
configure: line 3284: mpicc: command not found
configure:3293: $? = 127
configure:3282: mpicc -qversion >&5
configure: line 3284: mpicc: command not found
configure:3293: $? = 127
configure:3313: checking whether the C compiler works
configure:3335: mpicc -I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include  -L/usr/X11R6/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10   -I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/usr/X11R6/include -m64 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -pipe    -L/usr/local/uvcdat/xxxxx/Externals/lib -L/usr/local/uvcdat/xxxxx/Externals/lib64  -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib64 -Wl,-rpath,/usr/local/uvcdat/xxxxx/lib -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib conftest.c  >&5
configure: line 3337: mpicc: command not found
configure:3339: $? = 127
configure:3377: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "PROJ.4 Projections"
| #define PACKAGE_TARNAME "proj"
| #define PACKAGE_VERSION "4.9.2"
| #define PACKAGE_STRING "PROJ.4 Projections 4.9.2"
| #define PACKAGE_BUGREPORT "warmerdam@pobox.com"
| #define PACKAGE_URL ""
| #define PACKAGE "proj"
| #define VERSION "4.9.2"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3382: error: in `/Users/mcenerney1/xxxxx/build/proj4':
configure:3384: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CC_set=set
ac_cv_env_CC_value=mpicc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include  -L/usr/X11R6/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10  '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/usr/X11R6/include -m64 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -pipe   '
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/usr/local/uvcdat/xxxxx/Externals/lib -L/usr/local/uvcdat/xxxxx/Externals/lib64  -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib64 -Wl,-rpath,/usr/local/uvcdat/xxxxx/lib -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=awk
ac_cv_prog_ac_ct_CC=mpicc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='aclocal-1.14'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='autoconf'
AUTOHEADER='autoheader'
AUTOMAKE='automake-1.14'
AWK='awk'
CC='mpicc'
CCDEPMODE=''
CFLAGS='-I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include  -L/usr/X11R6/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10  '
CPP=''
CPPFLAGS='-I/usr/local/uvcdat/xxxxx/Externals/include -I/usr/local/uvcdat/xxxxx/Externals/lib/libffi-3.1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/usr/X11R6/include -m64 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -pipe   '
CYGPATH_W='echo'
C_WFLAGS=''
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JNI_INCLUDE=''
LD=''
LDFLAGS='-L/usr/local/uvcdat/xxxxx/Externals/lib -L/usr/local/uvcdat/xxxxx/Externals/lib64  -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib64 -Wl,-rpath,/usr/local/uvcdat/xxxxx/lib -Wl,-rpath,/usr/local/uvcdat/xxxxx/Externals/lib'
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='makeinfo'
MANIFEST_TOOL=''
MKDIR_P='./install-sh -c -d'
MUTEX_SETTING=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='proj'
PACKAGE_BUGREPORT='warmerdam@pobox.com'
PACKAGE_NAME='PROJ.4 Projections'
PACKAGE_STRING='PROJ.4 Projections 4.9.2'
PACKAGE_TARNAME='proj'
PACKAGE_URL=''
PACKAGE_VERSION='4.9.2'
PATH_SEPARATOR=':'
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
THREAD_LIB=''
VERSION='4.9.2'
ac_ct_AR=''
ac_ct_CC='mpicc'
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/mcenerney1/xxxxx/build/proj4/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local/uvcdat/xxxxx/Externals/proj4'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "PROJ.4 Projections"
#define PACKAGE_TARNAME "proj"
#define PACKAGE_VERSION "4.9.2"
#define PACKAGE_STRING "PROJ.4 Projections 4.9.2"
#define PACKAGE_BUGREPORT "warmerdam@pobox.com"
#define PACKAGE_URL ""
#define PACKAGE "proj"
#define VERSION "4.9.2"

configure: exit 77

**Comment by danlipsa** [comment]
Seems that the problem results from the following lines:
configure:3017: checking for gcc
configure:3044: result: mpicc

So configure thinks that the compiler should be mpicc, however that executable does not exist on your machine.

On my Linux machine I get:
configure:3017: checking for gcc
configure:3044: result: /usr/bin/cc

Do you have a /usr/bin/cc on your machine? Maybe you don't have xcode installed?
https://github.com/UV-CDAT/uvcdat/wiki/System-Requirements

**Comment by mcenerney1** [comment]
/usr/bin/cc is there. I installed xcode before the build. In fact, I built without mpi successfully.

**Comment by doutriaux1** [comment]
@danlipsa then it's an easy fix, let's make proj4 dependent on mpi if // build

**Comment by doutriaux1** [comment]
yep that fixed it for me, will push a PR asap

**Comment by doutriaux1** [comment]
oops pushd to master directly! I need to re-run my safeguard script. Oh well... @aashish24 @danlipsa please review after the fact this last commit:  eb15408

**Comment by aashish24** [comment]
> oops pushd to master directly!

@doutriaux1 :angry: 

Changes looks good to me :+1:

**Comment by aashish24** [comment]
@doutriaux1 did you  run build all again to make sure? GDAL might run into same issue?

**Comment by danlipsa** [comment]
On my mac laptop I get:
configure:3017: checking for gcc
configure:3044: result: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
It is not clear why would proj4 need mpi.

**Comment by aashish24** [comment]
@danlipsa I am not either. I will investigate it further since I don't think proj4 can use MPI.

**Comment by danlipsa** [comment]
It is CDAT_BUILD_PARALLEL. If I pass that, I get the same error.

**Comment by aashish24** [comment]
thanks @danlipsa I re-opened the issue.

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I ran it with ALL on my ubuntu. Will update for mac.

**Comment by aashish24** [comment]
@doutriaux1 I am looking into it. There are some other issues as well.

**Comment by doutriaux1** [comment]
@aashish24 I'm on it as well. Let's race!

**Comment by aashish24** [comment]
you have time for race? :smile:

**Comment by doutriaux1** [comment]
that's all I have time for! racing for everything, all the time. I can't ever slow down @aashish24

**Comment by doutriaux1** [comment]
@aashish24  see #1909
