### ISSUE TITLE
make -j8 seems to sometimes disable matplotlib

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1913]
because of ridiculous setuptools eggs that cannot be built in //

example:
```
doutriaux1@omar:[uvcdat]:[fix_1894]:[7470]> ll /lgm/uvcdat/2016-03-30/lib/python2.7/site-packages/
total 7.5M
-rw-rw-r--  1 doutriaux1 doutriaux1  248 Mar 30 13:52 CMOR-2.0-py2.7.egg-info
drwxrwxr-x  2 doutriaux1 doutriaux1 4.0K Mar 30 10:13 ComparisonStatistics
-rw-rw-r--  1 doutriaux1 doutriaux1  228 Mar 30 13:52 ComparisonStatistics-1.1-py2.7.egg-info
drwxrwxr-x 12 doutriaux1 doutriaux1 4.0K Mar 30 10:01 Cython
drwxrwxr-x  2 doutriaux1 doutriaux1 4.0K Mar 30 10:01 Cython-0.23.4-py2.7.egg-info
drwxrwxr-x  3 doutriaux1 doutriaux1 4.0K Mar 30 10:12 DV3D
-rw-rw-r--  1 doutriaux1 doutriaux1  242 Mar 30 13:52 DV3D-0.0.0-py2.7.egg-info
drwxr-xr-x  8 doutriaux1 doutriaux1 4.0K Mar 30 13:52 ESMP
drwxrwxr-x  2 doutriaux1 doutriaux1 4.0K Mar 30 10:13 EzTemplate
-rw-rw-r--  1 doutriaux1 doutriaux1  221 Mar 30 13:52 EzTemplate-1.0-py2.7.egg-info
[snip]
-rw-rw-r--  1 doutriaux1 doutriaux1  295 Mar 30 10:00 libcf-1.0_beta11-py2.7.egg-info
-rw-rw-r--  1 doutriaux1 doutriaux1  182 Mar 30 13:52 lmoments-0.0.0-py2.7.egg-info
-rwxrwxr-x  1 doutriaux1 doutriaux1 468K Mar 30 10:12 lmoments.so
drwxrwxr-x  5 doutriaux1 doutriaux1 4.0K Mar 30 10:04 matplotlib-1.5.1-py2.7-linux-x86_64.egg
drwxrwxr-x  3 doutriaux1 doutriaux1 4.0K Mar 30 09:58 mccabe-0.3.1-py2.7.egg
```
so obviously matplotlib built happily BUT unfortunately as an egg
now 
```
doutriaux1@omar:[uvcdat]:[fix_1894]:[7473]> more /lgm/uvcdat/2016-03-30/lib/python2.7/site-packages/easy-install.pth 
import sys; sys.__plen = len(sys.path)
./setuptools-19.2-py2.7.egg
./pip-7.1.2-py2.7.egg
./singledispatch-3.4.0.3-py2.7.egg
./netCDF4-1.1.9-py2.7-linux-x86_64.egg
./windspharm-1.3.x-py2.7.egg
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
doutriaux1@omar:[uvcdat]:[fix_1894]:[7474]> 
```

no matplotlib... Arrrggggggggg.......

**Comment by aashish24** [comment]
So the matplotlib should have been listed in easy-install? Is this a  workaround (dependency issue) related problem where we manually set the dependencies to make sure it's not parallel?

**Comment by doutriaux1** [comment]
it's a dependency issue, all the pip ones need to be chained one after another, but it gets tricky as
 - some build trigger bits on/off
 - adding new package gets added at the wrong place

fortunately all this goes away when we switch to conda

**Comment by aashish24** [comment]
> adding new package gets added at the wrong place

that shouldn't do affect this issue since it's sorted by dependency. 

> some build trigger bits on/off

If the deps are setup correctly it shouldn't cause this issue.

Question: Are you going to push a fix for this?

**Comment by doutriaux1** [comment]
i think kitware is best positioned to do a fix for this. @chaosphere2112 was rightly suggesting to drop the deps chainlinking, just using the actual deps, and then have kitware take all the package that use pip and chainlink them automatically.

**Comment by doutriaux1** [comment]
Conda switch makes this irrelevant
