### ISSUE TITLE
isoline style not changing

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/uvcdat#1916]
From below code, bold part, which is for changing style of isoline, is not working and shows only solid line..

lines2 = vcs.createisoline()
lines2.linecolors = ['red']
**#lines2.line=['solid']
lines2.line=['dot']
#lines2.line=['dash']**
lines2.label = 'y'
lines2.textcolors=['red']
canvas.plot(data['ta'],lines2)

**Comment by aashish24** [comment]
@danlipsa could you please take a look at this ?

**Comment by chaosphere2112** [comment]
This issue is a side effect of #1944
