### ISSUE TITLE
autot tests seem to fail from master

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1930]
@danlipsa any idea why I get this on my mac from today's master:

I'm taking care of the diags ones

```
	115 - test_vcs_boxfill_robinson_wrap (Failed)
	425 - test_vcs_continents (Failed)
	427 - test_vcs_autot_axis_titles_foreground_boxfill_0.5 (Failed)
	429 - test_vcs_autot_axis_titles_foreground_mollweide_boxfill_0.5 (Failed)
	431 - test_vcs_autot_axis_titles_foreground_robinson_meshfill_0.5 (Failed)
	433 - test_vcs_autot_axis_titles_foreground_lambert_isofill_0.5 (Failed)
	435 - test_vcs_autot_axis_titles_foreground_robinson_isoline_0.5 (Failed)
	580 - diags_test_01 (Failed)
	582 - diags_test_03 (Failed)
	583 - diags_test_04 (Failed)
	584 - diags_test_41 (Failed)
	585 - diags_test_05 (Failed)
	587 - diags_test_07 (Failed)
	588 - diags_test_08 (Failed)
	589 - diags_test_09 (Failed)
	590 - diags_test_10 (Failed)
	592 - diags_test_12 (Failed)
	593 - diags_test_13 (Failed)
	594 - diags_test_15 (Failed)
```

**Comment by doutriaux1** [comment]
diff pngs
![test_autot_axis_titles_boxfill_0 5_0_diff](https://cloud.githubusercontent.com/assets/2781425/14551059/82486ae4-0283-11e6-98b6-08f21af350b2.png)
![test_autot_axis_titles_boxfill_0 5_0](https://cloud.githubusercontent.com/assets/2781425/14551060/8249dc80-0283-11e6-9b08-b5723682ed38.png)
![test_autot_axis_titles_lambert_isofill_0 5_0_diff](https://cloud.githubusercontent.com/assets/2781425/14551061/824b8fda-0283-11e6-976e-13be9f08e9b9.png)
![test_autot_axis_titles_lambert_isofill_0 5_0](https://cloud.githubusercontent.com/assets/2781425/14551062/824bd1d4-0283-11e6-80eb-3fcebb401dd2.png)
![test_autot_axis_titles_mollweide_boxfill_0 5_0_diff](https://cloud.githubusercontent.com/assets/2781425/14551063/824cff64-0283-11e6-8c07-00245721b88d.png)
![test_autot_axis_titles_mollweide_boxfill_0 5_0](https://cloud.githubusercontent.com/assets/2781425/14551064/824e8b68-0283-11e6-8899-e02034eadcf2.png)
![test_autot_axis_titles_robinson_isoline_0 5_0_diff](https://cloud.githubusercontent.com/assets/2781425/14551065/825c3aec-0283-11e6-94f5-8488cd7b5554.png)
![test_autot_axis_titles_robinson_isoline_0 5_0](https://cloud.githubusercontent.com/assets/2781425/14551066/825de9dc-0283-11e6-96bb-1a0efe7e31c1.png)
![test_autot_axis_titles_robinson_meshfill_0 5_0_diff](https://cloud.githubusercontent.com/assets/2781425/14551067/825f83e6-0283-11e6-9f19-7da7a2b6afbe.png)
![test_autot_axis_titles_robinson_meshfill_0 5_0](https://cloud.githubusercontent.com/assets/2781425/14551070/8263e922-0283-11e6-9e6a-b6ff7acc80ed.png)
![test_continents_diff](https://cloud.githubusercontent.com/assets/2781425/14551068/8261abe4-0283-11e6-94e3-1cfd5326f912.png)
![test_continents](https://cloud.githubusercontent.com/assets/2781425/14551069/82639f94-0283-11e6-9b18-c52fd2199150.png)
![test_robinson_wrap_diff](https://cloud.githubusercontent.com/assets/2781425/14551071/826fb194-0283-11e6-831b-8cb4f589583c.png)

**Comment by doutriaux1** [comment]
interestingly removing my pre-exisiting uvcmetrics_test_data directory and re-installing it leads:
```
doutriaux1@maryam:[~/build]:[2263]> ctest -R diags 
Test project /Users/doutriaux1/build
      Start 580: diags_test_01
 1/15 Test #580: diags_test_01 ....................   Passed    8.51 sec
      Start 581: diags_test_02
 2/15 Test #581: diags_test_02 ....................   Passed   17.08 sec
      Start 582: diags_test_03
 3/15 Test #582: diags_test_03 ....................   Passed   10.14 sec
      Start 583: diags_test_04
 4/15 Test #583: diags_test_04 ....................   Passed   19.45 sec
      Start 584: diags_test_41
 5/15 Test #584: diags_test_41 ....................   Passed   20.01 sec
      Start 585: diags_test_05
 6/15 Test #585: diags_test_05 ....................   Passed   11.48 sec
      Start 586: diags_test_06
 7/15 Test #586: diags_test_06 ....................   Passed   10.49 sec
      Start 587: diags_test_07
 8/15 Test #587: diags_test_07 ....................   Passed   12.97 sec
      Start 588: diags_test_08
 9/15 Test #588: diags_test_08 ....................   Passed   18.68 sec
      Start 589: diags_test_09
10/15 Test #589: diags_test_09 ....................   Passed   11.89 sec
      Start 590: diags_test_10
11/15 Test #590: diags_test_10 ....................   Passed   16.88 sec
      Start 591: diags_test_11
12/15 Test #591: diags_test_11 ....................   Passed   22.13 sec
      Start 592: diags_test_12
13/15 Test #592: diags_test_12 ....................   Passed   17.09 sec
      Start 593: diags_test_13
14/15 Test #593: diags_test_13 ....................***Failed   10.59 sec
      Start 594: diags_test_15
15/15 Test #594: diags_test_15 ....................   Passed   17.86 sec

93% tests passed, 1 tests failed out of 15

Total Test time (real) = 225.33 sec

The following tests FAILED:
	593 - diags_test_13 (Failed)
Errors while running CTest
```
I think the md5 checking fails

**Comment by danlipsa** [comment]
No, I don't. While images seem to be correct, everything seems to be shifted a little. Maybe it is some sort of round up difference. What kind of mac is that? What os?

**Comment by danlipsa** [comment]
I am rebuilding everything fresh on my laptop from master. I will let you know the results.

**Comment by danlipsa** [comment]
It is interesting that only the tall version of the tests fail not the long ones.

**Comment by danlipsa** [comment]
I just run the tests master on my laptop. This is what fails:
	425 - test_vcs_continents (Failed)
	581 - diags_test_02 (Failed)
	582 - diags_test_03 (Failed)
	583 - diags_test_04 (Failed)
	584 - diags_test_41 (Failed)
	585 - diags_test_05 (Failed)
	586 - diags_test_06 (Failed)
	587 - diags_test_07 (Failed)
	588 - diags_test_08 (Failed)
	589 - diags_test_09 (Failed)
	590 - diags_test_10 (Failed)
	591 - diags_test_11 (Failed)
	592 - diags_test_12 (Failed)
	593 - diags_test_13 (Failed)
	594 - diags_test_15 (Failed)

**Comment by doutriaux1** [comment]
@chaosphere2112 I see that you observe the same failures

I think that

```
x = vcs.init(bg=bg, geometry=(xSize, ySize))
```
Might not work I'm going to add the x.setbgoutputdimension command as well just to be sure

@chaosphere2112 I remember you saying something about geometry and bg mode

**Comment by doutriaux1** [comment]
yes I think that that is it I see the log on cdash:
```
- /Users/doutriaux1/build/uvcdat-testdata/baselines/vcs/test_vcs_autot_axis_titles_boxfill_0.5.png
Comparing test_autot_axis_titles_boxfill_0.5_0.png  /Users/doutriaux1/build/uvcdat-testdata/baselines/vcs/test_vcs_autot_axis_titles_boxfill_0.5.png ...ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageDifference.cxx, line 397
vtkImageDifference (0x7f80d2b82400): ExecuteInformation: Input are not the same size.
 Input1 is: 0,399,0,784,0,0
 Input2 is: 0,399,0,799,0,0
```

image do not have the same size.

**Comment by doutriaux1** [comment]
I do get a gazillion of these now though:

```
Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.
```

**Comment by chaosphere2112** [comment]
@doutriaux1 Currently in VTK any renderers associated with a render window that is in background mode when it is resized will not resize. The render window itself will, and dumping it into a PNG should still output at the correct dimensions. So, probably not the same issue.

**Comment by doutriaux1** [comment]
In any case the picture generated by my mac are not the same size as the baselines from @danlipsa so I'm looking into this right now.

**Comment by danlipsa** [comment]
If size is the issue, just resize the pictures. I assume my laptop has higher resolution than yours, that is why it works on mine. I had to resize the pictures when going from the desktop to the laptop as well.

I think this is related to 
https://github.com/UV-CDAT/uvcdat/issues/1740

**Comment by doutriaux1** [comment]
@danlipsa but we need to make sure they consistently get out at the same size accross device, will push a fix in a minute
