### ISSUE TITLE
Non-ASCII character '\xe2' in file

### ISSUE THREAD

**Issue by davidedelvento** [UV-CDAT/uvcdat#1935]
```
File "uv_cdat/lib/python2.7/site-packages/vcs/VTKAnimate.py", line 287
SyntaxError: Non-ASCII character '\xe2' in file uv_cdat/lib/python2.7/site-packages/vcs/VTKAnimate.py on line 288, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
nimate.py on line 288, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Easy to remove the offending character from https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/vcs/VTKAnimate.py#L287 (the one after draw), but pretty annoying

**Comment by doutriaux1** [comment]
I believe this has been removed already. Which version are you using?

**Comment by davidedelvento** [comment]
@doutriaux1 -- I believe?? Can't you check the link that I conveniently added to the report and see that the problem is still there?

**Comment by davidedelvento** [comment]
Upon closer examination, you are correct. I was misguided into my previous comment by:
1) your use of "I believe" which sounded to me as not 100% sure
2) the fact that the offending character has not been deleted, but replaced by a dash (i.e. "-") which looked similar on the web compared to \xe2 in my editor

The version I'm running is the one https://anaconda.org/uvcdat/ provides

**Comment by doutriaux1** [comment]
@davidedelvento  no problem. I was pretty sure it was fixed because the anaconda is what actually made me discover these issues, but with so many PR approved in he last few days it's always possible that one re-introduced the issue. @chaosphere2112 thanks for fixing these.
