### ISSUE TITLE
Problem running unzip

### ISSUE THREAD

**Issue by davidedelvento** [UV-CDAT/uvcdat#1939]
Using an external program with subprocess just to run unzip is overkill, not portable and it fails on our system (because unzip needs a different version of GLIBC than what uvcdat binaries need.

But regardless, why one would like to rely on an external piece of software when you can get the same result with less effort and more robustness in python itself? The https://docs.python.org/2/library/zipfile.html module has been in the python standard library since we entered the Cenozoic Era after the dinosaurs got extinct at the end of the Cretaceous Period.

Anyway, here is the patch for that change.

```
vistrails/vistrails/core/system/unix.py
@@ -80,6 +83,13 @@
         assert type(el) in [str,unicode]
     return subprocess.list2cmdline(lst)

+import zipfile,os.path
+def unzip(source_filename, dest_dir):
+    with zipfile.ZipFile(source_filename) as zf:
+        zf.extractall(dest_dir)
+        return 0
+    return 1
+

vistrails/vistrails/db/services/io.py
@@ -38,6 +38,7 @@
 from core.bundles import py_import
 from core.system import get_elementtree_library, temporary_directory,\
      execute_cmdline, systemType, get_executable_path
+from core.system.unix import unzip
 from core.utils import Chdir
 from core.log.log import Log
 from core.mashup.mashup_trail import Mashuptrail
@@ -617,8 +618,7 @@

     vt_save_dir = tempfile.mkdtemp(prefix='vt_save')
     output = []
-    cmdline = ['unzip', '-q','-o','-d', vt_save_dir, filename]
-    result = execute_cmdline(cmdline, output)
+    result = unzip(filename, vt_save_dir)

     if result != 0 and len(output) != 0:
         raise VistrailsDBException("Unzip of '%s' failed" % filename)
```

**Comment by doutriaux1** [comment]
same thing, we are dropping Vistrails, please report on their main repo.

**Comment by davidedelvento** [comment]
Done https://github.com/VisTrails/VisTrails/issues/1171
