### ISSUE TITLE
Status of ESMPy in UV-CDAT ?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#1954]
Can somebody tell me what are the plans for **integrating ESMPy in UV-CDAT**? I have seen it mentioned in a year old open issue (https://github.com/UV-CDAT/uvcdat/issues/1151)

I'm not good at correctly handling non-regular grids, and I believe that the availability of a good and documented regridding package in UV-CDAT is important.

I have never really used ESMP, because the documentation on COG was not easy to use and I only had a small summary ppt as an extra documentation

I have discovered ESMPy (the new version of ESMP, if I understood correctly) in a PICO (the interactive 'posters') EGU last week and had an enlightening chat with @rokuingh (Ryan O'Kuinghttons). I also told him what I was expecting from a regridding package (as an end-user), e.g. reasonable memory usage, automatic recognition of the ORCA xx grid, ...

The link to his (including @bekozi and many co-authors) nice 'poster' (and examples) is http://presentations.copernicus.org/EGU2016-10050_presentation.ppt

**Comment by doutriaux1** [comment]
it's still on the agenda, we need to move to the newer nupmy first I believe. @rokuingh and I are in touch

**Comment by jypeter** [comment]
OK, thanks!

**Comment by doutriaux1** [comment]
@jypeter It's in the nightlies now.
