### ISSUE TITLE
bad contouring algorithm

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1959]
using clt data
```python
iso = x.createisoline()
iso.line = ["dot","dash-dot","long-dash"] * 100
x.plot(s/10000.,iso)
x.png("bad_contours")
```

gives us:

![bad_contours](https://cloud.githubusercontent.com/assets/2781425/14989823/8dc76a98-110e-11e6-9151-081197679ea8.png)

around -55South the dots are not dotted everywhere, but looks like most line are badly drawn everywhere anyway. @lee1043 noticed this.

**Comment by doutriaux1** [comment]
@danlipsa any chance you could tackle this one?

**Comment by danlipsa** [comment]
Sure, after I am done with streamlines I can take a look

**Comment by aashish24** [comment]
@doutriaux1 is this something we need asap? What you think of the priority of this task?

**Comment by doutriaux1** [comment]
it's holding up @lee1043 work, @lee1043 how badly do you need this? It is definitely needed for 2.6

**Comment by aashish24** [comment]
@danlipsa sounds like this is something needed soon. I would fix this one and then do the streamlines.

**Comment by danlipsa** [comment]
@aashish24 sounds good.

**Comment by doutriaux1** [comment]
Thanks. Yes I think it's more urgent than streamlines (but you know everything is important anyway)

**Comment by lee1043** [comment]
It would be nice if I can use this in this week. Thanks!

**Comment by danlipsa** [comment]
@doutriaux1 @lee1043 I can see that the lines do not respect the specifications (dot, dash-dot and long-dash). Is that the bug?

**Comment by doutriaux1** [comment]
@danlipsa yes more or less, we are not sure if the spaces are not respected or if that there are many short lines started next to each other making it look like one non-dotted/dashed line. Also it seems to be dependent on the actual data values (not 100% sure about that one)
