### ISSUE TITLE
vtk has hard links that seem to prevent anaconda libraries relocation

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1960]
using anaconda built vtk from our repo we cannot export svg any longer

```python
import vcs
x=vcs.init()
x.plot([1,2,3,4,3,2,1])
x.svg("fail")
```
results in:
```
----> 1 x.svg("fail")

/home/doutriaux1/anaconda2/lib/python2.7/site-packages/vcs/Canvas.pyc in svg(self, file, width, height, units)
   4719         if not file.split('.')[-1].lower() in ['svg']:
   4720             file += '.svg'
-> 4721         return self.backend.svg(file, W, H)
   4722 
   4723     def _compute_margins(

/home/doutriaux1/anaconda2/lib/python2.7/site-packages/vcs/VTKPlots.pyc in svg(self, file, width, height, units)
   1118 
   1119     def svg(self, file, width=None, height=None, units=None):
-> 1120         return self.vectorGraphics("svg", file, width, height, units)
   1121 
   1122     def gif(self, filename='noname.gif', merge='r', orientation=None,

/home/doutriaux1/anaconda2/lib/python2.7/site-packages/vcs/VTKPlots.pyc in vectorGraphics(self, output_type, file, width, height, units)
   1069         self.hideGUI()
   1070 
-> 1071         gl = vtk.vtkOpenGLGL2PSExporter()
   1072 
   1073         # This is the size of the initial memory buffer that holds the transformed

AttributeError: 'module' object has no attribute 'vtkOpenGLGL2PSExporter'
```

**Comment by doutriaux1** [comment]
@danlipsa @sankhesh please take a look and provide any input, this is really important. Thanks.

**Comment by sankhesh** [comment]
@doutriaux1 When conda compiles VTK, does it enable the module `Module_vtkIOExportOpenGL` ? That is the module that provides `vtkGL2PSExporter`.

**Comment by doutriaux1** [comment]
@sankhesh I passed it the exact same options as we do for our build. If I build with these options it seems to work, it's a relocation issue I think. Looks like some path are hard coded.

**Comment by doutriaux1** [comment]
@sankhesh I will try to manually turn this on anyway, thanks for the pointer.

**Comment by doutriaux1** [comment]
ok I see it in the log, we'll see if it picks it up
```
-- Backend OpenGL modules: vtkIOExportOpenGL;vtkRenderingVolumeOpenGL;vtkRenderingContextOpenGL;vtkRenderingLIC;vtkRenderingOpenGL;vtkRenderingGL2PS
```

**Comment by doutriaux1** [comment]
@sankhesh that was it! You're a genius!

**Comment by doutriaux1** [comment]
@sankhesh is there an option to turn on ALL modules? Thanks

**Comment by sankhesh** [comment]
@doutriaux1 Awesome. 

There is an option to enable all modules : `VTK_BUILD_ALL_MODULES`

However, I would suggest not to use it. That would build a whole LOT MORE code than required.

**Comment by doutriaux1** [comment]
@sankhesh I'll give it a try, since it's for anaconda we only build it once in a long while so that might be worth it.

**Comment by aashish24** [comment]
@doutriaux1 please do not use / turn "VTK_BUILD_ALL_MODULES" it will increase the binary size unnecessarily.

**Comment by doutriaux1** [comment]
yes I noticed and it also needs mpi and all that we don't necessarily want on.
