### ISSUE TITLE
use EGL instead of X for windowing system

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1961]

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa any progress on this? Should we close?

**Comment by danlipsa** [comment]
@doutriaux1 VTK has the capability to use EGL (graphics hardware on NVidia cards) for offscreen rendering. This is an alternative to OSMesa that provides better performance. We may have discussed this in the context of cdat web.

**Comment by doutriaux1** [comment]
feel free to close then.
