### ISSUE TITLE
vector plots may be wrong

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1977]
script:
```python
import vcs
import MV2
import cdms2
f=cdms2.open("/usr/local/uvcdat/1.5.0/sample_data/clt.nc")
s=f("clt")
u=f("u")[...,::3,::3]
v=f("v")[...,::3,::3]
x=vcs.init()
gm = x.createvector()
x.plot(u,v,gm)
x.png("crap")
raw_input("press enter")
```

Using current version I get:
![new](https://cloud.githubusercontent.com/assets/2781425/15377305/a0ccef02-1d0f-11e6-932f-f7a048e1d40f.png)

Using the pre-VTK (1.5.0) I get:

![old](https://cloud.githubusercontent.com/assets/2781425/15377311/adf5007a-1d0f-11e6-9569-962f8775fde7.png)

new is black but all arrows on screen are same size (try it) whweras not in old version

**Comment by aashish24** [comment]
@doutriaux1 using my current branch (which is on current origin/master), I am getting the correct image (attached) on Ubuntu 14.04. 

![crap](https://cloud.githubusercontent.com/assets/146527/15382633/ed33caec-1d59-11e6-9f2e-4ae795becf46.png)

**Comment by doutriaux1** [comment]
@aashish24 this is NOT correct, all arrows have the same length, look at the good one above, length of arrows changes. I think the "black" issue for me might be due to upgrading to ubuntu 16 (i should rebuild from scratch probably)

**Comment by aashish24** [comment]
FYI: @doutriaux1 this is what I said:

```
@doutriaux1 using my current branch (which is on current origin/master), I am getting the image (attached) on Ubuntu 14.04. We (I) changed the scaling factor on vector a while ago so I will have a look at the different arrow sizes
```

**Comment by doutriaux1** [comment]
@aashish24 sorry, like I said too many fires going on at once today :stuck_out_tongue_winking_eye: glad we are on the same page.

**Comment by aashish24** [comment]
> I said too many fires going on at once today  glad we are on the same page.

no prob :smile_cat:

**Comment by aashish24** [comment]
@doutriaux1 @williams13 @danlipsa I need to clean up some stuff but how this one looks as far as scaling is concerned: 

![new_vector](https://cloud.githubusercontent.com/assets/146527/15479370/e03f51ac-20ed-11e6-8ecb-89f925a9c806.png)

**Comment by aashish24** [comment]
This time with slightly bigger scale:
![new_vector](https://cloud.githubusercontent.com/assets/146527/15479395/f9f15104-20ed-11e6-96e6-3e15be94127d.png)
