### ISSUE TITLE
Conda channel nightly updates not up-to-date

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#1997]
It seems that the nightly conda channel is not automagically updating.. It'd be great if this channel was available for testing the `master` branch changes before official releases are uploaded
![160531_uvcdatcondachannel](https://cloud.githubusercontent.com/assets/3229632/15681877/f3f1a470-270f-11e6-8f94-0562b50778fe.png)

**Comment by durack1** [comment]
@doutriaux1 just wondering whether this conda experience is what you'd expect:
```
(uvcdat)durack1@oceanonly:[LeyangFeng_CEDSEmissionsSO2]:[1251]> conda update uvcdat
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /export/durack1/anaconda2/envs/uvcdat:
#
uvcdat                    2.4.1                    UVCDAT    uvcdat
(uvcdat)durack1@oceanonly:[LeyangFeng_CEDSEmissionsSO2]:[1251]> conda update uvcdat -c uvcdat
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........
Warning: 2 possible package resolutions (only showing differing packages):
  - hdf5-1.8.16-0.tar.bz2
  - hdf5-1.8.16-UVCDAT.tar.bz2

Package plan for installation in environment /export/durack1/anaconda2/envs/uvcdat:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyspharm-1.0.8             |           UVCDAT         695 KB
    libcdms-2.6                |           UVCDAT         1.9 MB
    uvcdat-2.6                 |           UVCDAT           2 KB
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following NEW packages will be INSTALLED:

    basemap:  1.0.7-np19py27_0
    cycler:   0.10.0-py27_0
    geos:     3.3.3-0
    pyspharm: 1.0.8-UVCDAT

The following packages will be UPDATED:

    uvcdat:   2.4.1-UVCDAT     --> 2.6-UVCDAT

The following packages will be DOWNGRADED:

    libcdms:  2016.5.24-UVCDAT --> 2.6-UVCDAT

Proceed ([y]/n)?
```

**Comment by doutriaux1** [comment]
@durack1 you should use environments. The nightly are purposely versioned with the date so that they superseed any existing version. "upgrading" to a stable version hence is not possible.

**Comment by durack1** [comment]
@doutriaux1 I believe this is still not functioning - the latest master PR merge is dated 5 days ago, whereas the [UV-CDAT conda channel nightly is showing 2016.6.27 as latest](https://anaconda.org/uvcdat/uvcdat/labels)

**Comment by durack1** [comment]
@zshaheen @doutriaux1 @dnadeau4 I've just trying to update my `uvcdatNightly` conda environment and it seems that the `conda nightly` UV-CDAT channel no longer exists..

https://anaconda.org/uvcdat/uvcdat/labels - only `main`

Am I doing something wrong here, or have you changed things?

**Comment by dnadeau4** [comment]
It seems that uvcdat/uvcdat is not updated since it has no build.sh.  Should we create a nightly uvcdat package so that `conda install uvcdat -c uvcdat/label/nightly` update to the latest?

**Comment by zshaheen** [comment]
@durack1 @dnadeau4 I don't think the nightly building from Travis that's in PMP is implemented in UV-CDAT. I'm looking [here](https://github.com/UV-CDAT/conda-recipes/tree/master/uvcdat).

**Comment by durack1** [comment]
@zshaheen that's what I thought.. But the weird thing is the last time I installed UV-CDAT I was directed to a nightly channel that has since been deleted..

**Comment by doutriaux1** [comment]
the nightly channel exists for each individual channels, not for uvcdat. You pick up each individual packages nightlies by passing the nighlty channel . You do not need a uvcdat nightly
`conda install uvcdat -c uvcdat/label/nightly` is bad by the way @dnadeau4 we are trying hard to have user use environments exclusively
to get nighlties you need:
`conda create -n NAME -c uvcdat/label/nightly -c uvcdat uvcdat`

**Comment by doutriaux1** [comment]
with that said we need nightlies for pmp , vcs and cdms2 do not seem to happen automagically. @zshaheen do you mind taking a look?

**Comment by dnadeau4** [comment]
@doutriaux1 I though @durack1 wanted to update a package into an existing environment.  In that case you need `install` not `create`.

**Comment by doutriaux1** [comment]
@dnadeau4 I see in this case let's post:
`conda install -n MYENV package -c channel`

**Comment by dnadeau4** [comment]
@doutriaux1 sounds good!

**Comment by zshaheen** [comment]
@doutriaux1 I though pmp was working? Did you want to get vcs and cdms2 working as well?

**Comment by doutriaux1** [comment]
i got cdms2 to work for sure will push vcs soon.

**Comment by durack1** [comment]
@doutriaux1 @zshaheen it seems that `uvcdat` nightlies are having problems:
```
public1:/home/p1d/> conda create -n UVCDATNightly -c conda-forge -c uvcdat/label/nightly uvcdat
Fetching package metadata .............

PackageNotFoundError: Package not found: Conda could not find '
```
This is on a `redhat6` machine:
```
> uname -a
Linux public1 2.6.32-642.6.1.el6.x86_64 #1 SMP Thu Aug 25 12:42:19 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
> more /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
```

**Comment by doutriaux1** [comment]
@durack1 I think it's the lab that doesn't let you out. Did you see: https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda and also did you click on the lab banner before going out to the internet?

**Comment by zshaheen** [comment]
FYI, this may be an issue on Anaconda's side, since we're getting a truncated error message. If I remember correctly, the PackageNotFoundError was more verbose. 

`conda install` uses `conda search` to find the packages. `conda search` currently doesn't work for me.

**Comment by zshaheen** [comment]
I also get the same error message as @durack1 on aims2, which is runnin RHEL 7.

**Comment by durack1** [comment]
@doutriaux1 this is happening at GFDL, so nothing to do with the LLNL cert/authentication stuff

**Comment by durack1** [comment]
@doutriaux1 @zshaheen if you want to test things out you can use:
```
conda create -n UVCDATNightly --verbose --verbose --verbose -c conda-forge -c uvcdat/label/nightly uvcdat
```
You should get a similar error to me..

**Comment by durack1** [comment]
@doutriaux1 @zshaheen, my question then, is this an anaconda issue, or are one of the UV-CDAT dependencies not there, and so things fail

**Comment by doutriaux1** [comment]
ok you forgot a `-c uvcdat` so it cant find some package that are on the uvcdat channel only (like `uvcdat` for instance)

You can pester conda team about having a better message

bottom line you want:

 ```
conda create -n UVCDATNightly --verbose --verbose --verbose -c conda-forge -c uvcdat/label/nightly -c uvcdat uvcdat
```

**Comment by durack1** [comment]
@doutriaux1 can you label this one "*user error*" please? :)
