### ISSUE TITLE
cdutil.ANNUALCYCLE.departures lopping off the final month

### ISSUE THREAD

**Issue by mzelinka** [UV-CDAT/uvcdat#2014]
[LWP_forCharles.nc.zip](https://github.com/UV-CDAT/uvcdat/files/305834/LWP_forCharles.nc.zip)

@doutriaux1 
There seems to be an issue with cdutil.ANNUALCYCLE.departures.  It is lopping off the final month, like so:

In [1]: import cdms2 as cdms

In [2]: f=cdms.open('LWP_forCharles.nc')

In [5]: LWP_grd.shape
Out[5]: (252, 45, 180)

In [9]: anomLWP_grd = cdutil.ANNUALCYCLE.departures(LWP_grd)

In [10]: anomLWP_grd.shape
Out[10]: (251, 45, 180)

In [11]: LWP_grd.getTime()
Out[11]: 
   id: axis_229493
   Designated a time axis.
   units:  months since 1988-01-01
   Length: 252
   First:  0.0
   Last:   251.0
   Other axis attributes:
      calendar: gregorian
      axis: T
      realtopology: linear
   Python id:  0x7fa604766890

In [12]: anomLWP_grd.getTime()
Out[12]: 
   id: time
   Designated a time axis.
   units:  months since 1988-01-01
   Length: 251
   First:  0.0
   Last:   250.0
   Other axis attributes:
      calendar: gregorian
      axis: T
   Python id:  0x7fa60431ee90

Note how the first dimension is shortened by 1.

**Comment by dnadeau4** [comment]
@mzelinka it seems that you time bounds are wrong.  The first bounds is `[0,0]` which make the departure off by one month.  

```
ncdump -v bounds_axis_229493  LWP_forCharles.nc
 bounds_axis_229493 =
  0, 0,
  0, 1,
  1, 2,
  2, 3,
```

**Comment by dnadeau4** [comment]
@mzelinka This is solved!
