### ISSUE TITLE
lambert baselines are wrong

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#2019]
https://github.com/UV-CDAT/uvcdat-testdata/blob/master/baselines/vcs/test_vcs_autot_axis_titles_lambert_isofill_2_1.png

These are not lamber projected.

**Comment by danlipsa** [comment]
@doutriaux1 Looks similar with
https://en.wikipedia.org/wiki/Lambert_cylindrical_equal-area_projection
first image.  I think I got that with 'a_lambert_isofill'.

**Comment by doutriaux1** [comment]
ok. I just thought you couldn't plot "global" maps with lambert projections. My bad.
