### ISSUE TITLE
lambert azimuthal proj seem to ignore user custom parameters

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#2059]
reported by @lee1043

``` python
import vcs
import cdms2
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt",slice(0,1))
x=vcs.init()
p=x.createprojection()
p.type="lambert azimuthal"
gm=x.createboxfill()
gm.projection=p
x.plot(s2,gm)
```

gives:
![lambert](https://cloud.githubusercontent.com/assets/2781425/16821298/453017a6-490a-11e6-8f34-07d3065cdb43.png)

manipulating the parameters on projection do not seem to change anything:

``` python
p.centerlongitude=0
#or
p.centerlongitude=45
```

**Comment by danlipsa** [comment]
We fixed this but there is an issue remaining. 
https://github.com/UV-CDAT/vcs/issues/181
