### ISSUE TITLE
vcs.displayplot.Dp.script() does not generate .json ouput

### ISSUE THREAD

**Issue by embrown** [UV-CDAT/uvcdat#2061]
In the source for the script() function for the Dp class, it looks like the function can only ever output a Python object.

**Comment by doutriaux1** [comment]
@embrown @chaosphere2112 I'm not sure we should save Dp object at all. I'd vote to remove the `script` function all together.

**Comment by chaosphere2112** [comment]
@doutriaux1 That's fine by me. It doesn't really make a lot of sense (given the presence of the `array` object) to persist them.

**Comment by chaosphere2112** [comment]
@embrown Nuke it from orbit.

**Comment by embrown** [comment]
@doutriaux1 @chaosphere2112  Sounds good to me. I'll take out the script function.

**Comment by embrown** [comment]
@doutriaux1 @chaosphere2112 Whenever we get the vcs documentation PR in, this will be good to close
