### ISSUE TITLE
utils.generate_time_labels(), wrong conversion to seconds?

### ISSUE THREAD

**Issue by embrown** [UV-CDAT/uvcdat#2068]
@charlesdoutriaux 
In vcs.utils.get_time_labels(), when checking the 'units' argument:
```python
    u = units.split('since')[0].strip().lower()
    # ...
    elif u in ['minute', 'minutes']:
         delta = (d2 - d1) / 24. / 60.
    elif u in ['second', 'seconds']:
         delta = (d2 - d1) / 24. / 60.
```
Shouldn't the calculation for seconds be 
```python
        delta = (d2 - d1) / 24. / 60. / 60. 
```
?

**Comment by doutriaux1** [comment]
yep looks like some copy/pasting that went bad. Go ahead and fix it please.

**Comment by embrown** [comment]
@charlesdoutriaux You got it.

**Comment by embrown** [comment]
This PR was incorporated in #2117. Calculation is fixed.
