### ISSUE TITLE
export patterns / hatches as vectors for vector formats 

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#2072]

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 

Could you please validate if these images are good:

[test_fillarea.pdf](https://github.com/UV-CDAT/uvcdat/files/439464/test_fillarea.pdf)

[test_fillarea_list.pdf](https://github.com/UV-CDAT/uvcdat/files/439466/test_fillarea_list.pdf)

**Comment by aashish24** [comment]
@sankhesh this is close but I see one problem. You see that image is "bitmap" so you see these jagged edges. what we need is a smoothing filter. Talk to Will or David Gobi about it.

**Comment by sankhesh** [comment]
@aashish24 Figured out why there were those jagged edges. That area was still being exported raster graphics. After my fix, the file size is tremendously huge. The test_fillarea.pdf file is ~ 287MB and test_fillare_list.pdf is ~ 498MB. Any ideas to reduce the size?

**Comment by aashish24** [comment]
Can you drop one of the files on google drive? 

I think the fix would be to exact the edges and export them vs exporting the triangles. Although it may not help all the patterns since each triagle may still be a separate. I guess one other thing would be to get rid of complete transparent triangles (this should be doable). Do you want to try that?

**Comment by sankhesh** [comment]
https://drive.google.com/file/d/0Bxgq5zla1NcFc2Q3T1FPb2JJamM/view?usp=sharing

**Comment by sankhesh** [comment]
@aashish24 I get rid of transparent triangles and the file size **reduced to half** but these are still pretty large files. See PR #2115.

The test script I use is listed here: https://github.com/UV-CDAT/uvcdat/issues/541#issue-39712768

**Comment by aashish24** [comment]
great @sankhesh. Can you tel me the diff

1) file size exported from master of cdat
2) file size exported from your branch

I am wondering if the diff between 1) and 2) is not that much and 1) is large itself.

**Comment by danlipsa** [comment]
@aashish24 @sankhesh 
It seems that uvcdat 1.5.1 did not generate vectors for hatches either. See the attached pdfs.
[test_fillarea_list.pdf](https://github.com/UV-CDAT/uvcdat/files/449839/test_fillarea_list.pdf)
[test_fillarea.pdf](https://github.com/UV-CDAT/uvcdat/files/449840/test_fillarea.pdf)

**Comment by doutriaux1** [comment]
@danlipsa but hey were happy with the quality of the output. That's the main difference, current pdf are `unusable` (only quoting)

**Comment by sankhesh** [comment]
@aashish24 Based on our discussion, I am looking at alternative ways to vectorize the output graphics. I looked at [potrace](http://potrace.sourceforge.net/#usage), but that only works for black and white graphics and has no color support.

Next, I found [autotrace](http://autotrace.sourceforge.net/). That seems like it may work for our needs. Here are some example outputs generated using `autotrace`:

- [test_fillarea-aliased-autotrace.pdf](https://github.com/UV-CDAT/uvcdat/files/452723/test_fillarea-aliased-autotrace.pdf)

- [test_fillarea_list-aliased-autotrace.pdf](https://github.com/UV-CDAT/uvcdat/files/452730/test_fillarea_list-aliased-autotrace.pdf)

Seems like it works good and the size is also not exorbitant, except that text is not rendered well. Is there a way to disable font hinting?

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 @williams13 Just wanted to post a quick update on this issue:

Here is a test pdf: 
[test_fillarea_list.pdf](https://github.com/UV-CDAT/uvcdat/files/494124/test_fillarea_list.pdf)

You can see that it is merely 3.5MB and renders the patterns/hatches as vectors. 

There are a few issues that I am working my way through but should have this ready soon.

**Comment by aashish24** [comment]
@doutriaux1 what you think?

**Comment by doutriaux1** [comment]
@aashish24 thx for pinging I didn't see that
3.5Mb seems right
@sankhesh let me know when I can test

**Comment by doutriaux1** [comment]
@sankhesh @bonfils2 noted the following:
* only 4 patterns shown
* line width/distance seems to be not constant
* triangles are not perfect

* Can we control the size of squares/lines?

**Comment by doutriaux1** [comment]
FYI @bonfils2 needs to submit her paper within 2 weeks, so we need it in a branch more or less functional as soon as possible. Thanks!

**Comment by sankhesh** [comment]
@bonfils2 

> * only 4 patterns shown

I am currently looking into some issues with the pattern generation. Once done, I plan to add more patterns

> * line width/distance seems to be not constant

Hmm. Not sure I see that. Could you please point out where this issue is?

> * triangles are not perfect

Yes, we've noticed that too. I'll fix it soon.

> * Can we control the size of squares/lines?

Currently, there is no such API in VCS. @doutriaux1 Should I just go ahead and add some properties to `fillarea`?

> FYI @bonfils2 needs to submit her paper within 2 weeks, so we need it in a branch more or less functional as soon as possible. Thanks!

Sure, I'll try to get it done this week. Will have to work with you when selecting what kind of patterns.

**Comment by doutriaux1** [comment]
@sankhesh I thought we were going to be able to send a fillarea object to the pattern, wouldn't that allow use to control the size of the patterns?

**Comment by doutriaux1** [comment]
@sankhesh on horizontal lines the 5th and 6th lines (from bottom) seem to have different thickness

**Comment by bonfils2** [comment]
Hello, There is progress with the patterns. Here is the figure I generated.
As you can see, however, is that underneath the patterns, the background color is white while it should be light brown or light green. Thanks for looking into it!
[Bonfils_etal_droughts_Jan32017_FINAL_FIG2.pdf](https://github.com/UV-CDAT/uvcdat/files/688572/Bonfils_etal_droughts_Jan32017_FINAL_FIG2.pdf)

**Comment by sankhesh** [comment]
@bonfils2 Thank you. I'll try to reproduce the issue on my end too. But just so I fully understand it, you add a solid fillarea (with the background color) and then a pattern on top it, right?

**Comment by doutriaux1** [comment]
@sankhesh yes she has data and she wants to see them bellow the hatching.

**Comment by sankhesh** [comment]
@bonfils2 @doutriaux1 I just created the attached pdf using the latest VTK master and it seems like all issues (including hatch over solid fillarea) have been resolved.

[vcs_patterns_index_10.pdf](https://github.com/UV-CDAT/uvcdat/files/705172/vcs_patterns_index_10.pdf)

![vcs_patterns_index_10](https://cloud.githubusercontent.com/assets/936354/21943310/b78c1762-d99e-11e6-9170-5ca4cb506de9.png)

**Comment by williams13** [comment]
Fantastic! Can we get this checked out for the next release?

-Dean
