### ISSUE TITLE
VCS: vcs.utils.getcolors provides a default value for colors parameter

### ISSUE THREAD

**Issue by embrown** [UV-CDAT/uvcdat#2097]
![huge_range](https://cloud.githubusercontent.com/assets/5880275/17864738/25c886f0-6854-11e6-9e20-e1ecb2dfe0eb.png)
This makes the documentation horrible to look at, and is probably bad practice anyway. 
I'm going to set colors=None and put an if statement in the function that assigns it to this range if colors=None, to clean it up.

**Comment by doutriaux1** [comment]
what about colors to `range(16,240)`
