### ISSUE TITLE
vcs.Gfb.rename() seems to destroy the object that it's renaming

### ISSUE THREAD

**Issue by embrown** [UV-CDAT/uvcdat#2116]
Here's a session example that I'm running in ipython now:

``` python
>>> b = vcs.createboxfill()
>>> b
<vcs.boxfill.Gfb at 0x1021f5ec0>
>>> b.name
'__boxfill_419032409050676'
>>> b.rename("test")
>>> vcs.elements['boxfill']['test']
<vcs.boxfill.Gfb at 0x1021f5ec0>
>>> vcs.show('boxfill')
*******************Boxfill Names List**********************
a_boxfill            a_lambert_boxfill    a_mollweide_boxfill 
a_polar_boxfill      a_robinson_boxfill   default             
polar                quick                robinson            
test                
*******************End Boxfill Names List**********************
>>> new_b = vcs.getboxfill('test')
>>> new_b
<vcs.boxfill.Gfb at 0x1021f5ec0>
>>> new_b.name
'__boxfill_419032409050676'
# assume we have a cdms2 variable named 's', and a Canvas named 'a'
>>> a.boxfill(s,b)
vcsError: Error source boxfill object (__boxfill_419032409050676) does not exist!
```

As we can see from the example, this leaves behind a reference to the renamed boxfill in the names list while making that boxfill unusable, because it is deleted.

I think the issue is that we should just be creating a new boxfill here, instead of using vcs.elements to re-assign things:
![gfb_rename](https://cloud.githubusercontent.com/assets/5880275/18143709/2021182c-6f78-11e6-907e-d048cb781b2d.png)

Not sure if this is a widespread problem (affecting more than just Gfb).

**Comment by embrown** [comment]
@doutriaux1 wasn't sure if you'd seen this yet.

**Comment by doutriaux1** [comment]
@embrown I didn't see it but i think I remember you talking to me about it.

I'll take a look.

**Comment by embrown** [comment]
@doutriaux1 I think I solved this problem. Want me to make a test and submit the new rename() code with a PR?

**Comment by doutriaux1** [comment]
sure, but on the vcs repo please. I opened an issue for this there at: https://github.com/UV-CDAT/vcs/issues/2

**Comment by embrown** [comment]
@doutriaux1 should we close this? It was fixed in vcs.

**Comment by doutriaux1** [comment]
@embrown please re-open if I have the wrong commit
fixed by: https://github.com/embrown/vcs/commit/b76a435b9b74b45b247c1cc4c5a1628b5a75c98f
