### ISSUE TITLE
Conda install failing on OS X

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#2138]
The command `conda create -n uvcdat261 -c uvcdat uvcdat` is currently failing on `OS X 10.11.6`, see https://github.com/ContinuumIO/anaconda-issues/issues/1209

**Comment by doutriaux1** [comment]
hum... works for me...
my conda version is:
```
conda 4.2.11
```

**Comment by doutriaux1** [comment]
@durack1 can you please try to update your conda and let me know.

Thanks

**Comment by durack1** [comment]
@doutriaux1 can you confirm the conda command line for the latest official, and the latest nightly (including cd77 for both please)

**Comment by durack1** [comment]
@doutriaux1 it seems that `2.6.1` is not currently available in the main channel for `linux`, it's only there for `OS X`: https://anaconda.org/uvcdat/uvcdat/files

**Comment by doutriaux1** [comment]
@durack1 in the process of updating nightlies to newer version, so let's wait on this. In the mean time  and for future reference it's all at:
https://github.com/UV-CDAT/uvcdat/wiki/install
and
https://github.com/UV-CDAT/uvcdat/wiki/Obtain-UV-CDAT-nightly-packages

**Comment by doutriaux1** [comment]
I believe `2.6.1` simply has better conda dependencies on mac, no actual code difference from `2.6`

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 it would be great to keep these versions in sync, regardless of the platform the files page looks a little linux lonely..
![uvcdat-no261linux](https://cloud.githubusercontent.com/assets/3229632/19909193/ba84348e-a043-11e6-8f99-b497c4b6e506.png)

**Comment by doutriaux1** [comment]
i can confirm `lats` `cd77` `ezget` will not be part of `uvcdat` they are PCMDI specific really.

**Comment by durack1** [comment]
@doutriaux1 will these continue to be supported going forward? And in the UV-CDAT channel right?

**Comment by doutriaux1** [comment]
yes they will, just not distributed as part of uvcdat

**Comment by durack1** [comment]
@doutriaux1 @mattben can this be documented on the wiki if possible - just so we don't lose this information buried in closed issues or emails.. An "Additional AIMS software" page or similar would certainly be useful..

**Comment by doutriaux1** [comment]
I think it's the kind of thing that should go on askbot.

**Comment by durack1** [comment]
@doutriaux1 I'm completely unfamiliar with the askbot service.. The wiki would be more natural to me..
