### ISSUE TITLE
Add a wiki page listing the different versions of CDAT

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#2158]
When you go to the https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda _Install_ page, you have the _Installing_ section that says

-   _conda create -n uvcdat-**2.x.y** -c conda-forge -c uvcdat uvcdat_
-   _source activate uvcdat-**2..x.y**_

It would be **a great help for users** to have here a link to the new page I'm suggesting, that would help people know which value to use for **2.x.y** and which are the different options. Since you don't know what version will be available when the users do the installation, you may want to have something like:

_conda create -n uvcdat-**SelectedVersion**-c conda-forge -c uvcdat uvcdat=**SelectedVersion**_

e.g. _conda create -n uvcdat-2.8.0 -c conda-forge -c uvcdat uvcdat=2.8.0_

With what you have now, the user has to do **some (too much?) guesswork**, based on
- the changelog: https://uvcdat.llnl.gov/changelog.html#2.8 . But the changelog gives **2.8** and not **2.8.0**
- the search on the anaconda web site: https://anaconda.org/search?q=uvcdat
- maybe this page: https://github.com/UV-CDAT/uvcdat/releases. I have just (re)discovered this **nice page** by chance and it seems the _UV-CDAT 2.8 is out_ mail @doutriaux1 sent at the end of November is a copy of that page. That's a nice page, but I don't think there is a link to it from the main web site (@chaosphere2112 ?) or from the uvcdat wiki pages
- maybe some other github pages that have some release/tags information?
- the _nightly_ page: https://github.com/UV-CDAT/uvcdat/wiki/Obtain-UV-CDAT-nightly-packages

I have read several conda-related pages (because I was totally new to it), but I'm still not familiar with some things that could also be explained shortly (in the _cdat_ context) on that page:
- what's the best order for specifying the conda channels when you use cdat: conda-forge, uvcdat, pcmdi, other channels
- what does _-c uvcdat/label/nightly_ mean (compared to just _-c uvcdat_)

Also I have seen several issues (often raised by @durack1 ) mentioning **-nox**. What are those versions for?

What would I do to get _older_ releases of cdat if I wanted to test some specific things?

**Comment by doutriaux1** [comment]
@jypeter 2.x.y is whatever you want, you can replace this with `best` or `#sad` if you want it's the name of your conda environment

**Comment by doutriaux1** [comment]
@jypeter all of this is really conda related 
```
anaconda search -t conda uvcdat
```
would show you which version of uvcdat you would get.

**Comment by doutriaux1** [comment]
@jypeter `nightlies` are built against the date as version so you can usually use this to go back in time
conda files/version are listed at http://anaconda.org/uvcdat/vcs/files
the order of channels is used to in case of versioning ties. conda will always install the most recent version but in case of ties it will use the one from the first channel in the list.

**Comment by durack1** [comment]
@jypeter the `*nox` versions are built without `X11` hooks, so that you can happily generate graphics on a headless machine with no `opengl` confusion.. For operational systems that are often difficult to get an interactive session on this is best. For interactive plotting, you just want the vanilla (not the `*-nox`) version

**Comment by durack1** [comment]
@jypeter I think you have some really good suggestions.. @doutriaux1 would you be willing to allow @jypeter to contribute to the install pages on this repo? I think his ideas, and his detail would certainly help out here.. It may also lead to a quicker path to better install docs, as rather than generating a new issue, the pages themselves are just updated.. many hand make light work??
