### ISSUE TITLE
lat-lon plot got reverse axis

### ISSUE THREAD

**Issue by Rex-Diego** [UV-CDAT/uvcdat#2161]
It seems easy to plot a lat-lon variable using vcs, but when it comes to Hadley sst data, something went wrong like this:
![hadley](https://cloud.githubusercontent.com/assets/7078058/24229090/ccc1067a-0fb2-11e7-8536-077cee40beac.png)

This is my code:
``` python
import cdms2, vcs

f=cdms2.open("/home/haha/data/sst/HadSST.3.1.1.0.climatology.1.nc")
s=f["sst"][5,:,:]
x=vcs.init()
bg=True
x.plot(s,bg=bg)
```

and the file ```HadSST.3.1.1.0.climatology.1.nc``` could be found [here](http://www.metoffice.gov.uk/hadobs/hadsst3/data/HadSST.3.1.1.0/netcdf/HadSST.3.1.1.0.climatology.1_to_10_netcdf.zip)(it's not large, only 824kB)
I've checked the axis information. Nothing seems wrong to me. And other data all works the right way when I plot it like this.

Any idea about how to avoid this?Thanks!

**Comment by doutriaux1** [comment]
@Rex-Diego data is stored that way in the file, you have a few options
* Option 1 : at read time
```python
s=f("sst",slice(5,6),latitude=(-90,90)) # This will work not matter how data is stored in file
# You can also control any other dimension via their names
s=f("sst",time=slice(5,6),latitude=(-90,90),longitude=(-180,180))
```
* Option 2: You know it needs flipping, do it manually
```python
s=f["sst"][5,::-1] # This will need logic depending on which dataset you read, not recommended
```
* Option 3, via vcs graphic method
```python
b=x.createboxfill()
b.datawc_y1 = -90.
b.datawc_y2 = 90.
b.list() # This shows other options you can control on boxfill
x.plot(s,b,bg=bg)
```

More info on boxfill can be found in tutorial: https://uvcdat.llnl.gov/iPython/boxfill/boxfill.html
I also recommend: https://uvcdat.llnl.gov/iPython/Basic_VCS_demo/Basic_VCS_demo.html

Hope this helps

**Comment by Rex-Diego** [comment]
@doutriaux1 Thanks soooooo much! 

I never thought about option 1or2 should work, because I'm familiar with NCL, and NCL will always plot data according to its axis(cordinate). So I paied more attention to what's going wrong with the axises.
Option 3 is elegant, I learned a lot from you!

**Comment by doutriaux1** [comment]
@Rex-Diego yes uv-cdat is *better* that way that we **NEVER EVER** assume we are smarter than the user. If the user provides data going North to South the we plot it that way, unless the user actually tells us otherwise.
