### ISSUE TITLE
fix location of legend with EzTemplate

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcdat#2164]
I'm using EzTemplate to make 2 plots on a page and I have nearly everything but I can' figure out how to move the legend away from plot.
 I can't tell if there are more controls on the legend than the list below:
![ua](https://cloud.githubusercontent.com/assets/14208252/24335964/fcf4abfe-123b-11e7-89e3-74b75358c6c9.png)

Type:        Legend
String form:
direction = horizontal
stretch = 0.8
thickness = 0.3
fat = 0.1

**Comment by doutriaux1** [comment]
You can either move it by yourself on your input template to EzTemplate
Or move it after the fact.

Also you can control a few more elements when initializing the Multi object:


    def __init__(self,columns=2,rows=3,

                 template='default',

                 top_margin=.05,bottom_margin=.075,left_margin=.033,right_margin=.05,

                 horizontal_spacing=0.05,vertical_spacing=0.035,

                 legend_thickness=.2,legend_direction='horizontal',legend_stretch=.8,legend_fat=0.05,

                 x=None

                 ):
