### ISSUE TITLE
setting custom range

### ISSUE THREAD

**Issue by stott** [UV-CDAT/uvcdat#2167]

**Comment by doutriaux1** [comment]
Can we have more details please?

**Comment by stott** [comment]
I'm sorry Charles. My note was truncated before hitting send.

I'm attempting to configure a module in VisTrails with an isofill plot. To
create the plot I'mve used a CDMSBinary Variable Operation to make a simple
calculation and produce a new variable. This works fine. But, when I add a
DMSIsofill module and attempt to set a custom range, everytime I hit
"Generate Ranges" the module returns to the default setting [1e+20, 1e+20].
And it gets stuck in a repetitive "save" and will not complete.

I hope this is clear enough

On Thu, Mar 30, 2017 at 8:19 AM, Charles Doutriaux <notifications@github.com
> wrote:

> Can we have more details please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2167-23issuecomment-2D290444352&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=t0Yuh9fr2Zod8Jas4XjlCzoXN1vgi6ltqededd0tyb4&s=yxwEMOg3vzThVSIo7hWwmKeodxIKqwzjMUiF6eqOac8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwoXUbx6KaGitf7NQGn1Ww409S8ZKks5rq8f9gaJpZM4MufyE&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=t0Yuh9fr2Zod8Jas4XjlCzoXN1vgi6ltqededd0tyb4&s=eKNEsactWftkBg42xjNxB8TmeW9DimkBxJIdAfaxVCs&e=>
> .
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089
