### ISSUE TITLE
Setting custom ranges

### ISSUE THREAD

**Issue by stott** [UV-CDAT/uvcdat#2168]
I'm sorry Charles. My previous post was truncated before hitting send. 

I'm attempting to configure a module in VisTrails with an isofill plot. To create the plot I've used a CDMSBinary Variable Operation to make a make a simple calculation and to produce a new variable. This works fine. But, when I add a DMSIsofill module and attempt to set a custom range, every time I hit "Generate Ranges" the module returns to the default setting [1e+20, 1e+20]. And then it gets stuck in a endless loop of "Configuration panel contains unsaved changes" pop-up window and will not complete. 

I hope this is clear enough

**Comment by doutriaux1** [comment]
@stott sorry for the late reply. We are in the process of deprecating vistrails (in 3.0), so while 2.12 will still ship with vistrails we pretty dropped support for it.
