### ISSUE TITLE
cdat_info has debug print statement

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#2169]
The output of `cdat_info.version()` has a print statement that I assume was included for debugging and should be removed:
```python
>>> import cdat_info
>>> cdat_info.version()
VERSION: 2.8.2
['', '2.8.2']
```
It's [here](https://github.com/UV-CDAT/uvcdat/blob/master/Packages/cdat_info/Lib/cdat_info.py#L10)

**Comment by doutriaux1** [comment]
fixed in master will be in next release.
