### ISSUE TITLE
Opendap with cdms2

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcdat#2176]
UVCDAT won’t open opendap addresses generated by a thredds server (not ESGF) - there is a certificate issue with the computer with grads.

For example:
https://esgf.nccs.nasa.gov/thredds/dodsC/CREATE-IP/reanalysis/NASA-GMAO/GEOS-5/MERRA2/mon/atmos/tas/tas_Amon_reanalysis_MERRA2_201501-201512.nc

using uvcdat 2.10:

Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
>>> f=cdms2.open('https://esgf-data.jpl.nasa.gov/thredds/dodsC/esg_dataroot/obs4MIPs/observations/atmos/taNobs/mon/grid/NASA-JPL/AIRS/v20110608/taNobs_AIRS_L3_RetStd-v5_200209-201105.nc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/potter/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/dataset.py", line 399, in openDataset
    raise SchemeNotSupported(scheme)
TypeError: 'str' object is not callable

**Comment by dnadeau4** [comment]
Jerry is this working? if so can you close it.  It works fine here.

**Comment by glpotter** [comment]
I need to check the ESGF opendap files

**Comment by doutriaux1** [comment]
@glpotter I tihnk it's working, please re-open if not.
