### ISSUE TITLE
Tangled 2.10.0 conda install

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#2181]
@doutriaux1 I have just tried to get the latest `2.10.0` installation via conda using:
```
$ conda create -n uvcdat2100 -c conda-forge -c uvcdat uvcdat
```
The packages I get using this are:
```
...
    cdat_info:                          2.10-py27_3        conda-forge
    cdms2:                              2.10-np111py27_3   conda-forge
    cdtime:                             2.10-np111py27_0   conda-forge
    cdutil:                             2.10-py27_0        conda-forge
...           
    cssgrid:                            2.10-np111py27_0   uvcdat     
...
    distarray:                          2.10-py27_0        conda-forge
...
    dsgrid:                             2.10-np111py27_0   uvcdat     
    dv3d:                               2.6-UVCDAT         uvcdat     
...
    eofs:                               1.2.0-py27_0       conda-forge
    esmf:                               7.0.0-6            conda-forge
    esmpy:                              7.0.0-py27_1       conda-forge
...
    genutil:                            2.10-np111py27_0   conda-forge
...
    hdf4:                               4.2.12-0           conda-forge
    hdf5:                               1.8.17-10          conda-forge
    hdf5tools:                          2.10-np111py27_0   uvcdat     
...
    libcdms:                            2.10-2             conda-forge
    libcf:                              1.0-py27_0         conda-forge
    libdrs:                             2.10-1             conda-forge
    libdrs_f:                           2.10-py27_0        conda-forge
...
    uvcdat:                             2.10-1             uvcdat
...
    vcs:                                2.6-UVCDAT         uvcdat
    vcsaddons:                          2.10-py27_0        uvcdat
...
    vtk:                                7.0.0-py27_1       conda-forge
...
    zonalmeans:                         2.10-np111py27_0   uvcdat
```
Looks to me like `vcs`, `vtk` and `dv3d` are getting older versions..

Full disclosure:
```
conda --version
conda 4.3.17
```

**Comment by durack1** [comment]
This is most likely due to conda/conda#5295

**Comment by doutriaux1** [comment]
@durack1 yes it's a conda bug, the web page instructions indicate this. You need to downgrade your conda as indicated on web page: https://github.com/UV-CDAT/uvcdat/wiki/install

**Comment by durack1** [comment]
@doutriaux1 the downgrade is a real pain, particularly when it triggers conflicts with other packages.. Did you get any suggestion of date for a likely fix in conda?

**Comment by doutriaux1** [comment]
@durack1 not sure what you mean. I downgraded on many machines it was painless. Just yank the bad uv-cdat environment an re-create one with the downgraded conda. It should not affect any other envs. Can you please provide some details?

**Comment by durack1** [comment]
@doutriaux1 I'd be really surprised if you don't get a whole bunch of users who neglect to read your guidance about having to degrade their conda install and hit the same issue as I have in this issue.. It'll have to be really cleanly described in the announcement - and a quick new release (or follow up announcement) when they fix the conda bug

**Comment by doutriaux1** [comment]
yes sir

**Comment by doutriaux1** [comment]
no need for a new release when they fix conda. Since it has nothing to do with the release.

**Comment by durack1** [comment]
Just my suggestion.. Do as you like. I've hit weird conflicts updating some packages, which have then upgraded/downgraded the conda version for the environment.. It's also suggested that updates had to occur in order to install packages with newer conda. I hope they fix it all soon, these tangles are a pain to deal with - as I know you are very aware..

**Comment by doutriaux1** [comment]
@durack1 fixed by moving vtk on uvcdat channel on a deidcated `2.6` label. Works now
