### ISSUE TITLE
Boxfill does not follow levels

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/uvcdat#2188]
While I was able to adjust color levels for isofill, I was not able to do this with the boxfill.

```
import cdms2, vcs

infile='clt.nc'
f=cdms2.open(infile)
d=f('clt')

x=vcs.init()
box=x.createboxfill()
x.plot(d)
```

![test1](https://user-images.githubusercontent.com/17091564/29384939-c04d3666-828a-11e7-9a26-ba0d9420a377.png)

```
box.levels=[0, 90]  ## This usage is mismatching to usage information given from https://uvcdat.llnl.gov/documentation/vcs/vcs-5.html
x.clear()
x.plot(d,box)
```
![test2](https://user-images.githubusercontent.com/17091564/29384966-dafa274e-828a-11e7-855d-6d67af34985c.png)

No change on color bar regarding setting box.levels

**Comment by doutriaux1** [comment]
@lee1043 this is because `boxfill` acts a little differently, please see tutorial at: https://uvcdat.llnl.gov/iPython/boxfill/boxfill.html

Basically in order to have `boxfill`  behave like a `isofill` use:
```python
box.boxfill_type = 'custom'
```
otherwise you have to use `color1` / `color2` and `level1` / `level2`

**Comment by doutriaux1** [comment]
@lee1043, in the future,  you might also want to report vcs bugs on the vcs repo issue tracker.

**Comment by lee1043** [comment]
@doutriaux1 Thanks!
