### ISSUE TITLE
.vt doesn't have all the steps

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#283]
I did a multiple step problem. select variables, recalculate F to C, used climate tools to average axes, I did not get any errors or exceptions. I plotted a number of plots, erased several and plotted more. Then I saved the workflow. I have attached the .vt file to an email to Ben.

**Comment by doutriaux1** [comment]
@potter2 @vvpalav what's the status on this?

**Comment by vvpalav** [comment]
I tried to reproduce but didn't get the error .. @potter2 can you please try and confirm if this still exists.

**Comment by vvpalav** [comment]
@potter2 .. can you please verify this issue .. its has been hanging around for a long time.

**Comment by doutriaux1** [comment]
@potter2 use the uvcdat branch Yosemite_rebased to test this on 10.10
```
cd [sources]
git fetch --all -p
git checkout Yosemite_rebased
cd
mkdir build_Yosemite
cd !$
cmake [sources]
make -j4
```

**Comment by potter2** [comment]
Charles,
Thanks, I’ll try it tomorrow

Jerry

Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

On Feb 27, 2015, at 3:17 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> use the uvcdat branch Yosemite_rebased to test this on 10.10

cd [sources]
git fetch --all -p
git checkout Yosemite_rebased
cd
mkdir build_Yosemite
cd !$
cmake [sources]
make -j4

**Comment by williams13** [comment]
If we get everything into master then all we need to do is clone master to test everything.

**Comment by potter2** [comment]
I will try to build it on 10.10 tomorrow

Sent from my iPhone

On Feb 27, 2015, at 2:15 PM, Vinayak Palav <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> .. can you please verify this issue .. its has been hanging around for a long time.

**Comment by doutriaux1** [comment]
yes and no. 
1- Sam's branch not quite ready
2- Yosemite branch needs to be tested a bit more on macs and also on non-mac to make sure I didn't break anything.

**Comment by vvpalav** [comment]
@potter2 @doutriaux1  .. Can we close this issue?

**Comment by potter2** [comment]
I haven't tested it yet. Should I build it and try it or do you have a 10.10 binary I could try?

**Comment by vvpalav** [comment]
I tried on my ubuntu but didn't really get any error. Maybe exact steps are little different than what I did. 
@doutriaux1 .. can you please answer this about 10.10 branch?

**Comment by doutriaux1** [comment]
@potter2 I will stick a binary on dropbox for you asap.

**Comment by doutriaux1** [comment]
@potter2 I just shared a build with you on dropbox with a 10.10 binary

**Comment by potter2** [comment]
Charles,
Thanks, I'll try it on the morning.

Jerry

Sent from my iPad

On Mar 2, 2015, at 10:29 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> I just shared a build with you on dropbox with a 10.10 binary

**Comment by doutriaux1** [comment]
Let me know

**Comment by potter2** [comment]
This is fixed

**Comment by vvpalav** [comment]
Thank you @potter2 .. closing this issue.

**Comment by potter2** [comment]
Charles,
The .vt file works now.  There are quite a few things that are broken 
now.. Is the version you sent me close to release?

Jerry




On 3/3/15 6:55 AM, Charles Doutriaux wrote:
>
> Let me know
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/UV-CDAT/uvcdat/issues/283#issuecomment-76959903>.
>

-- 
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by doutriaux1** [comment]
@potter2 yes
