### ISSUE TITLE
Add seawater package

### ISSUE THREAD

**Issue by stefraynaud** [UV-CDAT/uvcdat#421]
Maybe it would be a good idea to add the little seawater package to uvcdat:

https://pypi.python.org/pypi/seawater/

**Comment by doutriaux1** [comment]
@durack1 you know how to add packages now (as soon as @aashish24 fixed h5py) I'm assigning this one to you. Thanks!

**Comment by durack1** [comment]
@doutriaux1 sure, there are two candidates:
https://github.com/TEOS-10/python-gsw
https://github.com/ocefpaf/python-seawater

Both are housed in git repos - can we just clone the master branches (or a specific tag point) rather than housing the source.tar.gz ourselves?

**Comment by doutriaux1** [comment]
there are example for downloading from git, but I really don't like it. It breaks often. Anyhow look at uvcmetrics to inspire yourself. And yes please use a tag point (master keeps evolving and will not be compatible in 5 years if someone tries to still build 2.2 tag)

**Comment by durack1** [comment]
@doutriaux1 was there another package to add to this - you indicated "vacuum" or something similar? I'll try and get a PR issued soon so we can sneak into 2.2

**Comment by doutriaux1** [comment]
see https://github.com/UV-CDAT/uvcdat/issues/423

**Comment by durack1** [comment]
@doutriaux1 you might want to review this and reset it back to a 2.2 milestone if all goes well with travis

**Comment by durack1** [comment]
@doutriaux1 you might want to review this and reset it back to a 2.2 milestone if all goes well with travis
