### ISSUE TITLE
Add VACUMM to UV-CDAT

### ISSUE THREAD

**Issue by stefraynaud** [UV-CDAT/uvcdat#423]
How about adding VACUMM to UV-CDAT since mandatory dependecies are already satisfied ?
Here is the up-to-date web site:  http://relay.actimar.fr/~raynaud/vacumm/ (the officiel one is http://www.ifremer.fr/vacumm).
It makes an intensive usage of (UV-)CDAT and may have its place here too.

**Comment by durack1** [comment]
@doutriaux1 you might want to review this and reset it back to a 2.2 milestone if all goes well with travis

**Comment by durack1** [comment]
@doutriaux1 @aashish24 this also requires configobj and six to be installed - I'll issue another PR to bring this right up to date tomorrow

**Comment by durack1** [comment]
@doutriaux1 @aashish24 this issue should really be reopened until I've solved these additional dependencies..

**Comment by aashish24** [comment]
Ah, I checked the setup.py and I didn't see those requirements. Should I revert the merge?

**Comment by aashish24** [comment]
Okay, I have reset so that it is no longer in master now.

**Comment by durack1** [comment]
@aashish24 @doutriaux1 great, I'll fix this up and reissue a PR to bring things inline..

**Comment by durack1** [comment]
@aashish24 @doutriaux1 this should be good to go #1089

**Comment by durack1** [comment]
@aashish24 @doutriaux1 let's wait with #1089 until we get an all clear from @stefraynaud, apparently pytz was needed in the most recent vacumm version.
