### ISSUE TITLE
several vcs canvas problems

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#437]
I have several problems with the simple code below

* When I plot on 2 canvases in bg=1 mode, the content of the second canvas is not displayed with y.showbg() (blank canvas), even if I resize it to force a redraw. But the pdf and the png of both canvases are OK
* in bg=0 mode, the content of the second canvas is not displayed initially, but resizing the window will display it
* When I close the canvases with .close() on my LOCAL machine, I crash python and get _Crashpython: Fatal IO error 11 (Resource temporarily unavailable) on X server :0_. No crash when closing the canvases on a remote machine
* If I close on of the FIRST canvas by clicking on the X icon in the windows corner, I crash python with _python: Fatal IO error 11 (Resource temporarily unavailable) on X server :0._
*  If I close on of the SECOND canvas by clicking on the X icon in the windows corner, I get instead _ICE default IO error handler doing an exit(), pid = 11484, errno = 11_

My apologies for having several bugs in a single issue...

````
#!/usr/bin/env/python

import cdms2, numpy, vcs

bgmode=0
#bgmode=1
#datamode=0
datamode=1

x = vcs.init()
y = vcs.init()

if datamode:
    f = cdms2.open('sample_data/clt.nc')
    v = f('clt', time=slice(0,1), squeeze=1)
    f.close()
else:
    v = numpy.arange(100)

print 'Making 2 plots in bg=%i mode' % (bgmode,)
x.plot(v, bg=bgmode)
y.plot(v*v, bg=bgmode)

if bgmode:
    raw_input('Displaying the 1st plot with showbg()')
    x.showbg()
    raw_input('Displaying the 2nd plot with showbg() ==> oops! Blank')
    y.showbg()

raw_input('Saving png and pdf')
x.png('x_test')
y.png('y_test')
x.pdf('x_test')
y.pdf('y_test')
raw_input('Closing 1st canvas')
x.close()
raw_input('Closing 2nd canvas ==> oops! Crash')
y.close()

# The end
````

**Comment by chaosphere2112** [comment]
@jypeter This script seems to run fine (with some a tweak to the sample_data string); let me know if you're still having any issues with this.
