### ISSUE TITLE
cmake does not pick up the correct fortran compiler for ESMF (UVCDAT 1.5.1)

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#438]
I have run ccmake after defining gfortran44 for FC/F77/F90 (gfortran 4.4) in order to override the default gfortran which is a bit too old

This is correctly taken info account by ccmake
_CMAKE_Fortran_COMPILER => /usr/bin/gfortran44_

BUT ESMF seems to still pick gfortran
_CDAT_BUILD_ESMF_COMPILER => gfortran_

and I end up with the following error message
```
[INFO] Skipping ESMF

 [INFO] gfortran version needs to be at least 4.3 to install ESMF

 [INFO] You have

 Could not detect matplotlib,
```

**Comment by chaosphere2112** [comment]
Since RH5 isn't supported any more, I'm going to close this one.
