### ISSUE TITLE
ctest 'fails' if python has not been run interactively at least once (anonymous logging problem)

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#456]
If python has not been run interactively at least once (with some modules from PCMDI imported?), there is no *anonymouslog* file

    ~/.uvcdat/.anonymouslog

and running ctest in the build directory ends up with all tests failing  (except CDMS_Test_09)
```
54/71 Test #54: CDMS_Test_08 .......................***Failed    0.12 sec
      Start 55: CDMS_Test_09
55/71 Test #55: CDMS_Test_09 .......................   Passed    0.11 sec
      Start 56: CDMS_Test_10
56/71 Test #56: CDMS_Test_10 .......................***Failed    0.55 sec
[...]
71/71 Test #71: CDMS_Test_pack .....................***Failed    0.12 sec

1% tests passed, 70 tests failed out of 71

Total Test time (real) =  18.17 sec

The following tests FAILED:
	  1 - run_uvcdat (Failed)
	  2 - cdms_test (Failed)

```

I'm not sure when the file is created. I have had to import several modules before I was prompted about the anonymous logging
```
>>> import re
>>> import cdtime
>>> import numpy
>>> import genutil
Allow anonymous logging usage to help improve UV-CDAT? (you can also set the environment variable UVCDAT_ANONYMOUS_LOG to yes or     no) [yes/no]no
>>> 
```

What do you do with the anonymous logging? How do you send the results to PCMDI? Is there a chance that this may induce some lag when using uv-cdat based scripts? Logging seems like a tempting idea that could have unforeseen side-effects

**Comment by doutriaux1** [comment]
@aashish24 we should add this for 2.2

**Comment by aashish24** [comment]
yes.. this is problemetic.
