### ISSUE TITLE
Support for all_leap/366_day calendar in cdms2/cdtime?

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#463]
There does not seem to be any support for the _all_leap/366_day_ calendar in cdms2/cdtime, which would make it compatible with the calendars listed in the CF document

http://cfconventions.org/1.6.html#calendar

 - Is the _366_day_ support hidden somewhere?
 - Is any model using a _366_day_ calendar?

Note: cdo seems to support _366_day_ since version 1.6.0

https://code.zmaw.de/news/179

**Comment by doutriaux1** [comment]
@jypeter  how important is this? I'm doubtful I will ever get time for this

**Comment by jypeter** [comment]
I confess I have not met a case of **all_leap** data. Maybe mentioning it in the CF convention was an error? Could you ask some other MIP and CF experts like Peter and Karl what they think about this calendar?

We can keep this issue open in case somebody else worries about the problem, but it is low priority *as long as no CMIPn model uses this particular calendar*

**Comment by durack1** [comment]
@gleckler1 @taylor13 I think your perspectives are requested here..

**Comment by gleckler1** [comment]
I'm with you jypeter, I am not familiar with a case were the "all_leap" option has been exercised.   I don't think it is worth effort to try and build such and example.

**Comment by doutriaux1** [comment]
all right @gleckler1 and @jypeter sold it to me. closing until someone cares enough to re-open. And that does NOT include you @durack1 :wink:

**Comment by durack1** [comment]
@doutriaux1 "cares enough" doesn't sound much like me..
