### ISSUE TITLE
text rotation in VTK different from vcs way

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#503]
If I "left justify" a text, and then rotate it, the "justify" seems to be applied to the rotated text.
Trying to show this here, I have a vertical centered and left justified text.

First putting 3 points on the same "y" location I would expect (with the letter rotated 90 degrees)
```
A     A
B     B
C  A  C
D  B  D
```
But in fact I get
```
A     A
B  A  B
C  B  C
D     D
```

**Comment by durack1** [comment]
This is still an issue in master - can it be set as a 2.2 milestone.

PNG files seem fine, PS files have problems on the x-axis and PDF files have problems for both.

**Comment by durack1** [comment]
@dlonie - @doutriaux1 and I are wondering where these tweaks are in the queue for VTK? Are we likely to see these changes in place for the 2.2 milestone?

**Comment by dlonie** [comment]
They're in VTK's master at the moment. @aashish24, are we still planning to just bump the VTK version in uvcdat at some point? Or should these commits just be cherry-picked into the uvcdat fork of VTK?

**Comment by aashish24** [comment]
yes, I will merge release into the master today, update the SHA and the version, and then will update the VTK after I build it successfully with it. I have to sync up with @doutriaux1 but yes, we need to move forward

**Comment by durack1** [comment]
@aashish24 these changes wont make it into 2.1.0 will they?

**Comment by aashish24** [comment]
@durack1 I am sorry, they won't since it has significant changes and we already froze 2.1.0. We will do it in 2.1.1 though (or 2.2) depending on what Dean and Charles has to suggest.

**Comment by durack1** [comment]
@aashish24 ok.. It'd be great if you can tag a 2.1.1 fairly soon with this VTK change implemented.. We're trying to lock down some code against a known UV-CDAT version, and this text rotation stuff is an important tweak we'd like to include..

**Comment by aashish24** [comment]
Roger that. That is my intention as well. I will talk to @doutriaux1 about it.

**Comment by durack1** [comment]
@aashish24 it would also be good for us to test out the new code too, and make sure that it faithfully addresses the issue highlighted above (and my test case which shows differing results for outputs saved to png, ps and pdf)

**Comment by doutriaux1** [comment]
@aashish24 @dlonie let me know when it's in @durack1 and i will test it here.

**Comment by durack1** [comment]
@aashish24 @dlonie are these text rotation changes in master yet? @doutriaux1 and I are keen to test out the new code..

**Comment by aashish24** [comment]
I have one more branch to review and then I will bump the VTK. Sorry for some delay on this.

**Comment by durack1** [comment]
@aashish24 @dlonie no problem.. Looking forward to testing this so please do let both @doutriaux1 and I know when there's a PR or it's in master..

**Comment by aashish24** [comment]
VTK has been updated. @durack1 could you please verify if you are still seeing these issues. Make sure you build current master of UV-CDAT

**Comment by doutriaux1** [comment]
@durack1 I will start a build on crunchy.

**Comment by doutriaux1** [comment]
I ran the above test, here are the results:
Postscript:
Ok
PNG:
top alignment does seem to be a bit off
bottom right if off as well
PDF
right alignment wrong
top alignment wrong

**Comment by doutriaux1** [comment]
@aashish24 @dlonie PS is h best one right now. We really need to make sure they ALL produce the SAME plots.

**Comment by doutriaux1** [comment]
overall we're getting closer

**Comment by doutriaux1** [comment]
oh also just checked svg
top alignment is wrong

**Comment by doutriaux1** [comment]
hum.. .now looking at VTK sha we might still not be using the right VTK
```
2c7d13c885a67971201ab743205f988e60d6a37b
```
It does say it's uvcdat-master
@aashish24 are you sure you updated the sha?

**Comment by doutriaux1** [comment]
looking on github this sha is 1 ahead and 4 behind kitware, so yep I'm getting the right VTK. But the output are still wrong.. Sorry...

**Comment by dlonie** [comment]
No worries, I half expected that -- text labels in PDFs don't support alignment, but I have a couple tricks up my sleeve. I'll see what I can come up with.

**Comment by doutriaux1** [comment]
thanks @dlonie pdf is used a lot!

**Comment by dlonie** [comment]
After #1013 and UV-CDAT/VTK@9760973 are applied, the results are consistent across backends for me.

@doutriaux1 @durack1 can you try again?

@aashish24 I need you to review / merge http://review.source.kitware.com/#/t/5428 into VTK master, as the UVCDAT fonts uncovered a bug in our path renderer.
