### ISSUE TITLE
Failed packages in 2.0.beta (and 1.5.1)

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#533]
When installing 2.0.beta, I get
```
2 Packages reported as FAILED, see logs
                contrib/pyclimate
                contrib/MSU
```
It's an improvement over 1.5.1, where I got 3 FAILED packages, with the additional
```
contrib/windspharm
```

More details in my 2.0.beta and 1.5.1 installation log files:

https://wiki.lsce.ipsl.fr/pmip3/doku.php/other:uvcdat:installed

**Comment by jypeter** [comment]
I'm closing this issue, since it seems unlikely that it will be taken care of now that we have a 2.2.0 version

Notes
- I get the impression that **windspharm** disappeared between 1.5.1 and 2.x
- The problem I got when trying to manually install windspharm in 1.5.1 and 2.1.0, where you have to type 'yes' to accept the license, may explain why windspharm did not install in 1.5.1
- My notes and solution for installing windspharm in 1.5.1 and 2.x are available in https://github.com/ajdawson/windspharm/issues/44

**Comment by ajdawson** [comment]
>The problem I got when trying to manually install windspharm in 1.5.1 and 2.1.0, where you have to type 'yes' to accept the license, may explain why windspharm did not install in 1.5.1

I'd just like to reiterate that this is an issue with **pyspharm**, which is only evident if you try to `pip install windspharm` without first installing the pyspharm dependency.

**Comment by durack1** [comment]
@jypeter we've got a new PR #1074 which will hopefully resolve this issue.. It's been held up due to a dependency on spherepack if I recall.. @doutriaux1 was going to look at this next week..
