### ISSUE TITLE
GUI is not tested well

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#585]

**Comment by hgohil2805** [comment]
Is this something that still needs to be looked at??

**Comment by doutriaux1** [comment]
@hgohil2805 it actually got worst since then. There is absolutely no tests for the GUI. Zero, None, NULL.

So yes it is desperately needed!

**Comment by hgohil2805** [comment]
Got it. I think we can work on it soon and add some soon. thanks

**Comment by remram44** [comment]
Duplicate of #1214
