### ISSUE TITLE
Isofill does not work with mercator if given lat coordinates values -90, 90 (the edges)

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#587]
I suggest we try every template that is exposed.

**Comment by doutriaux1** [comment]
i think @dlonie has almost a fix for these sort of things in #1043 reassigning to him

**Comment by dlonie** [comment]
Right, #1043 should address the continent wrapping issues. But only the continents.

Do you know what script produced the last plot in this issue (the one with the continent wrapping artifacts)? I'm looking for a test case for that patch.

**Comment by doutriaux1** [comment]
@dlonie quick examples for mercator
The following works (see png)
```
import vcs,cdms2
import os,sys
f=cdms2.open(os.path.join(sys.prefix,"sample_data","clt.nc"))
s=f("clt")
iso=x.createisofill()
iso.projection="mercator"
x.plot(s(latitude=(-80,80)),iso)
```
![ok](https://cloud.githubusercontent.com/assets/2781425/6280349/62c90e6c-b860-11e4-8c4e-8bbda5e209e0.png)

the following does NOT work
``
x.plot(s(latitude=(-90,90)),iso)
```

![bad](https://cloud.githubusercontent.com/assets/2781425/6280350/68114f4c-b860-11e4-84f1-aa5882af7d2e.png)

**Comment by doutriaux1** [comment]
and yes labels/tickmarks are wrong will work on this tomorrow

**Comment by doutriaux1** [comment]
on the bright side, note that the continents seems to be ok now...

**Comment by doutriaux1** [comment]
I'll make "robinson", "Molleweide", "polar" work for this version, will turn off the others.

**Comment by doutriaux1** [comment]
@williams13 @aashish24 ok so we now only have the 3 above.
Mercator still doesn't work so moving to 2.3

**Comment by doutriaux1** [comment]
@aashish24 I think it's the same as #1462

**Comment by aashish24** [comment]
talked to @doutriaux1 some more on this. The only fix is to inform user what went wrong other than that its not really fixable since the math does not work if the the number are not right for projections (nothing specific to VTK, VCS or PROJ4).

**Comment by aashish24** [comment]
@doutriaux1 I confirmed. With proj4 you don't get any error (pure proj4). You get a tuple (1e+30, 1e+30) back but these numbers are not NAN's they are just bad numbers. I think this is one the case we were agreeing on that user need to know the projection. One thing I was suggesting is masking the data if the projection is mercator (past 85,-85). Let me know what you think of that..

**Comment by aashish24** [comment]
@doutriaux1 is there an option in vcs that can mask data that has grid data point values within certain range?

**Comment by aashish24** [comment]
@doutriaux1 more specifically, is there a method on transient variable for clipping the grid?

**Comment by doutriaux1** [comment]
@aashish24 when getting the data into VTK simply do data=data(latitude=(-85,85))

**Comment by doutriaux1** [comment]
of course you should first check that the user lats are beyond that range

**Comment by aashish24** [comment]
Yup.. thanks for the hint. I think I have a fix now. I will push a branch.
