### ISSUE TITLE
The vectors are not drawn when using projection other than plat-caree.

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#653]

**Comment by dlonie** [comment]
I'm looking into this, and it's difficult to figure out what data is in what coordinate system, what coordinate system it should be in, etc.

I'm using the test command:

```python "/ssd/src/uvcdat/testing/vcs/test_vcs_basic_gms.py" "--gm_type=vector" "--projection=-3" "--lat1=-90" "--lat2=0" "--source=/ssd/src/uvcdat-build/uvcdat-testdata/baselines/vcs/test_vcs_basic_vector_-3_proj_SH.png" --show```

Prior to calling doWrap on the vector data, the vector data bounds are similar to the final continent bounds (Roughly `(-9782112.62778627, 9772957.562484365, -9759498.0, 8568893.0)`). After calling doWrap, the vector dataset is empty, as there is no data that lies within the clip box.

If there is a missing projection, where should that projection take place? Should each worker function (plotVector, plot2D, plot[...], etc) take care of projecting the data, or should this be handled somewhere higher up the stack?

I guess what I'm looking for is sort of a high level description of how data comes into vcs (e.g. what coordinate system), and what transformations are expected to take place, what order the transformations should be performed in, and where the transformations are expected to occur.

**Comment by doutriaux1** [comment]
@dlonie I think you're onto something. doWrap maniuplates the inputData ut in the case of vectors we are not using this we are using some other array. I can we need to update  doWrap to also alter the "Vectors array"

**Comment by dlonie** [comment]
I'll reassign this as it's a VCS issue, and you have a better understanding of what that code should be doing ;)

**Comment by doutriaux1** [comment]
@dlonie taking out doWrap does make any diff the bounds are big as soon as I do the geo (projection). The numbers are probably ok too, they are in m on the earth sphere. I just think the fitToViewPort might be the issue here. Not sure.

**Comment by doutriaux1** [comment]
when fixing this we should turn back on vector tests for projections

**Comment by doutriaux1** [comment]
@aashish24 @dlonie is one f you taking a look at this?

**Comment by dlonie** [comment]
@doutriaux1 I haven't looked at it since it was reassigned.

**Comment by doutriaux1** [comment]
``python
import vcs
import os
import cdsm2
f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))
u=f("u")
v=f("v")
V=x.createvector()
p=x.createprojection()
p.type="polar"
V.projection=p
x.plot(u,v,V)
```

**Comment by aashish24** [comment]
I am getting close in solving the mystery..

![vector](https://cloud.githubusercontent.com/assets/146527/9974028/bf99bc84-5e4d-11e5-9760-07e44a9a2567.png)

**Comment by doutriaux1** [comment]
Nice!

**Comment by aashish24** [comment]
Still some more work to do but here is the latest image:

![vectors](https://cloud.githubusercontent.com/assets/146527/9978404/3550d83e-5efa-11e5-882a-ca2c5f506ba9.png)

[] Need to fix doWrap
[] Fix failing tests
[] Add notes and squash commits

**Comment by aashish24** [comment]
Also, I think I may have found a bug in vtkGeoTransform. Will confirm it on Monday, since I am having a hard time to believe that we had this bug all along.
