### ISSUE TITLE
Install problems on kubuntu 14.04

### ISSUE THREAD

**Issue by tom-redd** [UV-CDAT/uvcdat#678]
Hello,

hope I'm in the right forum fo rproblems when installing uv-cdat.

Tried to install uv-cdat 2.0 1.5.1 and 1.5.0 

on kubuntu 14.04 i386 (pre-requistes as given in wiki checked)

Always run into configure error (from CMakeError.log):

...   /CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_MAC’ was not declared in this scope
   return ((int*)(&Q_WS_MAC))[argc];

Any idea what's missing?

Thanks a lot for help

Thomas

**Comment by doutriaux1** [comment]
I guess we can close this right?

**Comment by tom-redd** [comment]
On 24.02.2015 20:02, Charles Doutriaux wrote:
>
> I guess we can close this right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UV-CDAT/uvcdat/issues/678#issuecomment-75822268>.
>
Thanks for asking. I didn't succeed to install uvcdat on the mentioned
computer and gave up. I switched to anaconda and installed cdat-lite
which fits perfectly for my application.

Many greetings Thomas

-- 
KITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKIT

Dr. Thomas Reddmann
Karlsruhe Institute of Technology (KIT) 
Institute for Meteorology and Climate Research
Atmospheric Trace Gases and Remote Sensing

Postf. 3640
76021 Karlsruhe

Phone: 0049(0)721 6082 3008
email: thomas.reddmann@kit.edu

KITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKITKIT
