### ISSUE TITLE
Cannot Load a Variable between Projects

### ISSUE THREAD

**Issue by williams13** [UV-CDAT/uvcdat#69]
1) Read in a variable "clt", then plot with it, VCS Boxfill ASD. Then save the project. Close UV-CDAT. Bring UV-CDAT back up and load the saved project. Now remove the saved project. Now try to read in the "clt" variable and you will get the error saying that "clt" already exists.

2) Read in variable "clt", then start a new project. Now try to load "clt". You get the error that "clt" already exists.

3)Read in variable "clt", then close the project. Now try to load "clt". You get the error that "clt" already exists.

**Comment by vvpalav** [comment]
will need more time cause busy with other issues, moving this to 2.3 as its not a showstopper

**Comment by vvpalav** [comment]
Looked into issue 2) I think this is how it should behave as keeping variables copies for different projects make sense as users can use this in calculator. if we want to make variables unique in global dictionary then we need to compromise on calculator function. just creating new variable with diff name is much simpler and can avoid ambiguities. 

Please let me know if we need to work on this. I can reopen the issue make changes
