### ISSUE TITLE
Out of source detection is broken

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#713]
The `BUILDINSOURCE` check in the main [CMakeLists.txt](https://github.com/UV-CDAT/uvcdat/blob/70a0fd33e7e66c428584ad9ca4b7ed499ba16dbb/CMakeLists.txt#L12) is broken; building in `/home/vagrant/build-uvcdat` when the source is in `/vagrant` makes it think I'm building in the source. Very annoying, since it always affects Vagrant.

**Comment by doutriaux1** [comment]
@remram44 is that fixed now?

**Comment by remram44** [comment]
Was fixed by #973
