### ISSUE TITLE
polar plot in isofill is not an option and isoline polar plot has wrong tic marks

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#729]
see attached. Notice the menu for polar in isofill is missing and the tic marks on the isofill shouldn't be on the box. 
![polar](https://cloud.githubusercontent.com/assets/2963950/4494125/0c86a962-4a4f-11e4-9dfe-c62440c58087.png)

**Comment by doutriaux1** [comment]
moving this to 2.3 because I think it's going to be redone when we re-implement the VTK filters.

**Comment by doutriaux1** [comment]
works on master
