### ISSUE TITLE
uvcdat "executable" should unset env or it might be using the "Wrong" python

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#730]
```
~ (140) uvcdat --output=""
UVCDAT setup already sourced for this install location.
```

@jbeezley are you still in charge of setup_runtime or should I re-assign this to @aashish24 or @dlonie

**Comment by doutriaux1** [comment]
ok this issue has become very convoluted, not really sure what it was about any more... I thnk @remram44 addressed this already. If anybody is not satisfied with current status please open a new issue

**Comment by remram44** [comment]
This issue is before #747 so probably outdated.
The warning itself was removed recently with #1069.
