### ISSUE TITLE
Robinson projection does not quite work for continent lines

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#734]
It seems to me that we have data that might be outside the 180. Need to make a standlone test for this.

**Comment by dlonie** [comment]
@aashish24 Walked through this with a debugger, and the wrapping is happening solely within the PROJ4 code. All the VTK layer does is transform the points.

Indeed, it looks like some of the data is outside of 180 degrees:

Input bounds:
	X: -253.5 --> 180
	Y: -85.58 --> 83.65
	Z :0.0001 --> 0.0001
Output bounds:
	X: -1.62063e+07 --> 1.67919e+07
	Y: -8.4492e+06 --> 8.34338e+06
	Z :0.0001 --> 0.0001

**Comment by doutriaux1** [comment]
@dlonie @aashish24 I guess we should have VTK do the wrapping, or VCS, whichever is easier.
