### ISSUE TITLE
esgf search gui needs to click on each category in order

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#767]
can't jump straight to models and pick one

**Comment by doutriaux1** [comment]
@vvpalav feel free to reassign to someone else on the GUI team.

**Comment by vvpalav** [comment]
Looking into this one, but not a showstopper so moving this to 2.3

**Comment by vvpalav** [comment]
@doutriaux1 Can you please provide more information. also provide steps to recreate and whats the expectation.

**Comment by doutriaux1** [comment]
@vvpalav i will try to load it up and provide pngs to make it clearer give me a day or two though...

**Comment by vvpalav** [comment]
@doutriaux1 Sure .. Thanks :)

**Comment by doutriaux1** [comment]
@vvpalav it seems to work now. I tried to select things in random order and it was responsive. So I guess we are good. Closing

**Comment by vvpalav** [comment]
:+1:
