### ISSUE TITLE
PyClimate uses old Numeric code

### ISSUE THREAD

**Issue by tammasloughran** [UV-CDAT/uvcdat#800]
Hi,
UVCDAT includes the pyclimate module that has some functions for doing PCA and CCA that I would like to use. This module is getting a bit old now seeing as though it still uses the old Numeric code via the numpy.oldnumeric module in most of its features. It seems with the latest release of numpy support for numpy.oldnumeric has been dropped which means that importing most of the pyclimate modules results in:
ImportError: No module named oldnumeric.

Cheers

**Comment by doutriaux1** [comment]
@aashish24 I can't seem to be able to trigger the build of pyclimate, assiging this to you.

**Comment by doutriaux1** [comment]
@aashish24 i think this suffers the same issue as the h5py the cdat_add_package_denedent never triggers it.
see comment sin https://github.com/UV-CDAT/uvcdat/pull/1035

**Comment by aashish24** [comment]
Okay, I will have a look at it.

**Comment by durack1** [comment]
@doutriaux1 #1071 duplicates this so I think it's a candidate for closure

**Comment by durack1** [comment]
@doutriaux1 @aashish24 #1071 duplicates this so I think it's a candidate for closure
