### ISSUE TITLE
Update udunits to 2.2.x branch

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#847]
We are a minor release behind the udunits latest (2.1.24 vs 2.2.17). I also note that they've migrated across to a git repo: https://github.com/Unidata/UDUNITS-2, switching to this would avoid having to manage the source tar balls

@doutriaux1 @aashish24 want to assign this task as a 2.1 milestone?

**Comment by dlonie** [comment]
Removing the patch step breaks compilation on travis builds. Ref #769.

The patch just drops in a new configure script that removes the checks for flex (as detection is broken on the travis builds and udunits doesn't actually use any lexers, anyway).

Looks like a new patched configure file is needed for the new version.

**Comment by aashish24** [comment]
@dlonie can push a brach with the fix?

**Comment by aashish24** [comment]
Actually the new udunits should have CMake. May be we should use it instead?

**Comment by dlonie** [comment]
Sure, I'll look into it.

On Wed, Jan 21, 2015 at 9:42 AM, Aashish Chaudhary <notifications@github.com

**Comment by durack1** [comment]
@doutriaux1 wanna add the enhancement label (for @chaosphere2112's readme: #913)

**Comment by doutriaux1** [comment]
done and you now have permissions to add labels on the repo, so feel free to do it.

**Comment by durack1** [comment]
@doutriaux1 currently doing that now.. thanks..
