### ISSUE TITLE
UV-CDAT Label on VCS 1D and 2D Plots

### ISSUE THREAD

**Issue by williams13** [UV-CDAT/uvcdat#857]
The UV-CDAT label in the lower right corner disappear when the canvas is resized. This is noticed on the GUI.

**Comment by doutriaux1** [comment]
@williams13 I think it works now that the new logo is in, let's try again when gui is fixed. Checked from comamnd line, after a 
```
x.interact()
```
and it works.

**Comment by williams13** [comment]
As soon as I hear back from Aashish and the GUI team that it is safe to build and run with the GUI, I will give it a try.
