### ISSUE TITLE
Update numpy to 1.10

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#885]
They've just released a bugfix update to the 1.9.x branch: http://docs.scipy.org/doc/numpy/release.html

I'll update the sources and issue an pull request when I deal with the other issues #856, #847, #846 (which is going to need some testing), and #841 and #814

**Comment by durack1** [comment]
@doutriaux1 another candidate for a move to 2.3 - and likely we'll just skip 1.9.1 and go straight to 1.9.2 when it's out (soon - 1.9.2rc1 is out)

**Comment by durack1** [comment]
@doutriaux1 can you add build and cdms2 labels please?

**Comment by doutriaux1** [comment]
please no issue if you have the PR ;)

**Comment by durack1** [comment]
You don't want both?

**Comment by doutriaux1** [comment]
well... usually you create an issue to remind to fix it and THEN issue the PR. Once the PR is in, there's no need for the issue any longer. Except maybe for the README file that @chaosphere2112 auto-generates.

**Comment by durack1** [comment]
That's exactly why I generated both.. First issue to outline problem (issue) and then the PR to "solve" it.. Having both means that it'd be easier for @chaosphere2112 to then just poll the closed issues directly rather than having to generate an issue from an orphan PR..

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 another candidate for 2.4 - and likely just skip 1.9.1 and go straight to 1.10 when it's out soon ([1.10.0b1 is out](https://github.com/numpy/numpy/releases/tag/v1.10.0b1))

**Comment by durack1** [comment]
@dnadeau4 just FYI [`numpy 1.10.0` just landed](https://github.com/numpy/numpy/releases/tag/v1.10.0) so should be available for starting to migrate `cdms2/3` across..

**Comment by durack1** [comment]
@dnadeau4 - fixed by #1607?

**Comment by doutriaux1** [comment]
@durack1 eventually yes.

**Comment by dnadeau4** [comment]
@durack1 I am trying to read all referenced ticket which bring me to more referenced tickets.  At this point I am not sure what the problem is with 1.10.0.   Can we discuss this?

**Comment by durack1** [comment]
@dnadeau4 the issue that @doutriaux1 encountered with an earlier `numpy` release (`1.9.2` from memory) was that the `cdms2TransientVariable.mean()` function wasn't returning a valid result.. The comment is documented in https://github.com/UV-CDAT/uvcdat/pull/915

**Comment by dnadeau4** [comment]
They are gaps in many data test due to numpy interpolation bug.  This is why many "diags" testing are failing with this numpy version.   I can't update to 1.10.1 until this is fixed.  https://github.com/numpy/numpy/issues/6468

**Comment by durack1** [comment]
@dnadeau4 this link (discussing cython vs numba and speedups using each) was interesting.. https://medium.com/@elgehelge/the-5-most-important-python-data-science-advancements-of-2015-a136482da89b#.4psi1vuqy
![](https://cdn-images-1.medium.com/max/800/1*FPTxvMefHjaoA8a5pdGoZw.png)

**Comment by durack1** [comment]
@dnadeau4 this was closed by UV-CDAT/cdms#59, but the comment above [link](https://github.com/UV-CDAT/uvcdat/issues/885#issuecomment-166439735) will be useful during the numba implementation.. If you have a numba issue already open it would be useful to copy this across
