### ISSUE TITLE
Disable 3D plotting tools for data with two spatial dimensions.

### ISSUE THREAD

**Issue by ThomasMaxwell** [UV-CDAT/uvcdat#889]
Dean asks: If I plot the 3D 'clt' variable with 3D_Scalar, there is a slider at the bottom of the plot "Slice Position", when I slide it from to the left and right nothing happens to the plot. Why have it if it does nothing? Is it suppose to do nothing?

Reply: The slider adjusts the vertical position of the horizontal slice, it is active by default when the 3D_scalar plot is instantiated.   When you drag the slider it is adjusting the vertical position of the slice, however, if the data has only one vertical level then nothing will change.   You should be able to turn off the slider using the configuration buttons.   I suppose it would be more clear to disable all the 3D plotting features if one is plotting a variable with only 2 spatial dimensions.

**Comment by ThomasMaxwell** [comment]
Fixed in the __vcs3D-hide_3d_controls_for_2d_plots__ branch.

**Comment by doutriaux1** [comment]
@ThomasMaxwell let's not close until merged. You can add fix #bla in a commit to close an issue automatically when merging. In the eman time adding the "gatekeeper" label is better (even better with an issue comment pointing to the branch in question, but if you use the "Commit" technic it will appear here anyway)
