### ISSUE TITLE
Color table error

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#937]
I was making a custom color table and tried to save it. Here is what I got:

Critical message:
Unexpected Exception

 
'NoneType' object has no attribute 'validate'
Traceback (most recent call last):
File "/Users/potter/uvcdat/build/install/vistrails/vistrails/gui/vistrail_controller.py", line 396, in change_selected_version
do_validate, from_root)
File "/Users/potter/uvcdat/build/install/vistrails/vistrails/core/vistrail/controller.py", line 3049, in do_version_switch
self.validate(pipeline)
File "/Users/potter/uvcdat/build/install/vistrails/vistrails/core/vistrail/controller.py", line 2891, in validate
pipeline.validate(raise_exception, vistrail_vars)
AttributeError: 'NoneType' object has no attribute 'validate'
 
 
Time:
2014-11-30 16:51:07,789
Location:
/Users/potter/uvcdat/build/install/vistrails/vistrails/gui/vistrail_controller.py, line 461

**Comment by vvpalav** [comment]
@williams13 @potter2 I was trying to recreate this one, but no success :-( 
(but got few other issues) Can you please give me exact steps cause that will really save me some time.

**Comment by doutriaux1** [comment]
@vvpalav I think they select a colortable, rename it , edit it and then save it.

**Comment by williams13** [comment]
That is it. Thanks Charles.

-Dean

**Comment by vvpalav** [comment]
@potter2 @williams13 I fixed some issues on colormap editor and it is merged into master now.
Can you please test this issue once again just in case to check if this one was a side effect of that other issue. 
Other issue :- #1104

**Comment by vvpalav** [comment]
@potter2 @williams13 can you please verify? I think this one also got fixed when I fixed #1104 . I tried couple of times but didn't get the mentioned error.

**Comment by remram44** [comment]
Feel free to reopen if you run into this again.
