### ISSUE TITLE
Bokeh: new browser-based visualization module

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#938]
This could be useful to consider for web-based graphics rendering:

http://bokeh.pydata.org/

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 I dropped this down just to make sure folks knew about it.. Closing to get it out of the to-do list..

**Comment by aashish24** [comment]
@durack1 I know bokeh really well. I had at one point integrated geojs (developed by Kitware) into it: 

https://github.com/opengeoscience/geojs

**Comment by durack1** [comment]
@aashish24 it popped up in a search back in Dec 2014 so I dropped that issue down just to grab the info and make folks aware of it.. As UV-CDAT web spins up, it would be interesting to know what is out there are usable..
