### ISSUE TITLE
MV2.array(0.).fill_value is NaN!

### ISSUE THREAD

**Issue by stefraynaud** [UV-CDAT/uvcdat#959]
In the `TransientVariable.__new__ method`, the following code assign a NaN value to the fill_value attribute:

```python

       fill_value = numpy.array(fill_value).astype(dtype),
```

So, for instance:

```python
>>> numpy.isnan(MV2.array(0.).fill_value)
True
```

**Comment by doutriaux1** [comment]
commented already onyuor other post. It gets really really bad in numpy 1.9.1 ... I think a huge overhaul is needed at this point...

**Comment by durack1** [comment]
@doutriaux1 as noted in #481 is the so called "VTK reader" a possible path forward here?

**Comment by doutriaux1** [comment]
Maybe.
