### ISSUE TITLE
x.close() brokn if more than one plot on

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#961]
```
import vcs
import os,cdms2
f=cdms2.open(os.path.join(sys.prefix,"sample_data","clt.nc"))
s=f("clt")
x=vcs.init()
y=vcs.init()
x.plot(s)
y.plot(s)
x.close() # only clears
y.close() # only clears
```

**Comment by williams13** [comment]
This worked for earlier releases and there is a CTEST for this. Is the CTEST not setup properly?

-Dean

**Comment by doutriaux1** [comment]
I don't think it ever worked properly. Celine just spotted that the labels are erroneous by default. They are correct if set manually (so diags are ok). I's just the "Auto" one. ctest passes because baselines are wrong. Once I fix this I expect most ctest to fail.

**Comment by williams13** [comment]
Aashish worked on this months ago with the release of v2.0.0. We all confirmed that it was working correctly.

**Comment by doutriaux1** [comment]
sorry my comment is for #960 for this case it works if you have only ONE canvas open. assigning @aashish24 to it then.

**Comment by durack1** [comment]
@doutriaux1 I am happy to test this within the VNC environment with spyder that I'm using, it would seem to be a continuing issue..

**Comment by doutriaux1** [comment]
seems to work again
