### ISSUE TITLE
Fix udunits on mac / travis

### ISSUE THREAD

**Issue by dlonie** [UV-CDAT/uvcdat#977]
PR #847 updated the udunits version and removed the patch that fixed compilation on Travis's mac boxes (the failing flex issue, #769).

Either update the udunits compilation to use the new CMake support, or reapply the flex patch.

**Comment by dlonie** [comment]
@aashish24 Their CMake system won't work -- it doesn't install the udunits.h header, which is needed by UVCDAT/Packages/unidata to build the python udunits interface.

I'll remake the patch for their configure script.

**Comment by doutriaux1** [comment]
@dlonie I thought @jbeezley just updated their cmake to use 3.1 I guess the brew version is broken then?

If so it might be worth further editing @jbeezley patch to simply build CMake like we do for Linux?

**Comment by jbeezley** [comment]
I think he is referring to the `CMakeLists.txt` file provided by udunits.

**Comment by dlonie** [comment]
It's a problem with the way the udunits package has written their CMake build system -- it doesn't install the same files as their autoconf script does.
