### ISSUE TITLE
Multiple errors in vcs x.show

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#999]
You can get a list of *vcs objects types* (I don't remember the exact name!) with the following:
```
>>> x.show()
['1d', '3d_dual_scalar', '3d_scalar', '3d_vector', 'boxfill', 'colormap', 'display', 'fillarea', 'font',
'fontNumber', 'isofill', 'isoline', 'line', 'list', 'marker', 'meshfill',
'outfill',
'outline', 'projection', 'scatter',
'taylordiagram', 'template',
'textcombined', 'textorientation', 'texttable', 'vector', 'xvsy', 'xyvsy', 'yxvsx']
```
And you can see what's predefined in ~/.uvcdat/initial.attributes with eg
```
>>> x.show('texttable')
*******************Texttable Names List**********************
bigger         boldfont_tt15  default       
font1          font3          mwbotcenter   
qa             scatylab       std           
*******************End Texttable Names List**********************
```
Unfortunately, this seems broken for 'fontNumber', 'outfill', 'outline', 'taylordiagram' and 'textcombined'!

I don't know if there is a problem in the code or if the ~/.uvcdat/initial.attributes is broken/incomplete. I'm getting these errors with the default initial.attributes because I have erased the ~/.uvcdat directory before running my tests, and initial.attributes is re-created the first time I do a vcs.init()

'fontNumber', 'outfill', 'outline' and 'textcombined' fail with same error
```
>>> x.show('fontNumber')     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/Canvas.py", line 5622, in show
    return vcs.show(*args)
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/utils.py", line 207, in show
    m = max([len(e) for e in elts])+1
TypeError: object of type 'int' has no len()
```

'taylordiagram' has an error of its own
```
>>> x.show('taylordiagram')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/Canvas.py", line 5622, in show
    return vcs.show(*args)
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/utils.py", line 192, in show
    for t in vcs.taylordiagrams:
AttributeError: 'module' object has no attribute 'taylordiagrams'

```

**Comment by doutriaux1** [comment]
this error goes away if you remove ${HOME}/.uvcdat but so many ran into it I will push a fix.

**Comment by jypeter** [comment]
No, you get this error even if you start with no uvcdat directory! That's what I was checking 
-- 
JYP @ SGS 2

**Comment by doutriaux1** [comment]
oh yes! Thanks I mixed both errors. WIll fix right away.

**Comment by doutriaux1** [comment]
@jypeter outfill  and outline have been removed by the way

**Comment by jypeter** [comment]
I did not use *outfill* and *outline* very often, but they were useful to use instead of continents when you have a variable with 0/1 a land-sea mask and you are working with a paleo-geography (eg when continents are very different from the modern continents)

We can probably replicate outfill with boxfill, but **we can't replicate outline with isoline**
